import type { PreviewControlContract } from '@/modules/docs/preview';

import {
  axesPlaygroundCanonicalValues,
  axesPlaygroundRelatedApis,
  createAxesPlaygroundControls,
} from './axes-playground.control-builder';

/** Comprehensive English control panel for Axes public properties */
export const axesPlaygroundEnControls = createAxesPlaygroundControls({
  title: 'Axes controls',
  sections: {
    coordinate: 'Coordinate system',
    grid: 'Grid',
    gridGeometry: 'Grid geometry',
    gridStyle: 'Grid style',
    xAxis: 'x axis',
    yAxis: 'y axis',
    origin: 'Origin label',
  },
  fields: {
    axisMode: 'Visible axes',
    originX: 'Origin x',
    originY: 'Origin y',
    extentMode: 'Extent mode',
    extentX: 'x extent',
    extentY: 'y extent',
    xNegative: 'x negative extent',
    xPositive: 'x positive extent',
    yNegative: 'y negative extent',
    yPositive: 'y positive extent',
    gridEnabled: 'Show grid',
    gridSpacingMode: 'Grid spacing mode',
    gridSpacing: 'Uniform spacing',
    gridSpacingX: 'x spacing',
    gridSpacingY: 'y spacing',
    gridOffsetX: 'x lattice offset',
    gridOffsetY: 'y lattice offset',
    gridStroke: 'Grid color',
    gridStrokeWidth: 'Grid width',
    gridDash: 'Grid dash',
    gridDashOffset: 'Dash offset',
    gridLineCap: 'Line cap',
    gridOpacity: 'Grid opacity',
    gridSeparateDirections: 'Separate direction colors',
    gridVerticalStroke: 'Vertical color',
    gridHorizontalStroke: 'Horizontal color',
    originLabelEnabled: 'Show origin label',
    originLabelText: 'Origin text',
    originLabelOffset: 'Origin label offset',
    originLabelColor: 'Origin label color',
    originLabelSize: 'Origin label size',
    originLabelOpacity: 'Origin label opacity',
    xLineMode: 'x line and arrows',
    xLineStroke: 'x line color',
    xLineStrokeWidth: 'x line width',
    xLineDash: 'x line dash',
    xLineOpacity: 'x line opacity',
    xArrowShape: 'x arrow shape',
    xArrowScale: 'x arrow scale',
    xArrowLength: 'x arrow length',
    xArrowWidth: 'x arrow width',
    xArrowColor: 'x arrow color',
    xArrowOpacity: 'x arrow opacity',
    xTickMode: 'x tick source',
    xTickSpacing: 'x tick spacing',
    xTickExtent: 'x tick extent',
    xTickNegativeValue: 'x negative tick',
    xTickPositiveValue: 'x positive tick',
    xTickSide: 'x tick side',
    xTickEndpointGap: 'x endpoint gap',
    xTickLength: 'x tick length',
    xTickStroke: 'x tick color',
    xTickStrokeWidth: 'x tick width',
    xTickDash: 'x tick dash',
    xTickLabelNegativeText: 'x negative tick text',
    xTickLabelPositiveText: 'x positive tick text',
    xTickLabelOffset: 'x tick-label offset',
    xTickLabelColor: 'x tick-label color',
    xTickLabelSize: 'x tick-label size',
    xTickLabelOpacity: 'x tick-label opacity',
    xLabelMode: 'x label end',
    xLabelText: 'x label text',
    xLabelOffset: 'x label offset',
    xLabelColor: 'x label color',
    xLabelSize: 'x label size',
    xLabelOpacity: 'x label opacity',
    yLineMode: 'y line and arrows',
    yLineStroke: 'y line color',
    yLineStrokeWidth: 'y line width',
    yLineDash: 'y line dash',
    yLineOpacity: 'y line opacity',
    yArrowShape: 'y arrow shape',
    yArrowScale: 'y arrow scale',
    yArrowLength: 'y arrow length',
    yArrowWidth: 'y arrow width',
    yArrowColor: 'y arrow color',
    yArrowOpacity: 'y arrow opacity',
    yTickMode: 'y tick source',
    yTickSpacing: 'y tick spacing',
    yTickExtent: 'y tick extent',
    yTickNegativeValue: 'y negative tick',
    yTickPositiveValue: 'y positive tick',
    yTickSide: 'y tick side',
    yTickEndpointGap: 'y endpoint gap',
    yTickLength: 'y tick length',
    yTickStroke: 'y tick color',
    yTickStrokeWidth: 'y tick width',
    yTickDash: 'y tick dash',
    yTickLabelNegativeText: 'y negative tick text',
    yTickLabelPositiveText: 'y positive tick text',
    yTickLabelOffset: 'y tick-label offset',
    yTickLabelColor: 'y tick-label color',
    yTickLabelSize: 'y tick-label size',
    yTickLabelOpacity: 'y tick-label opacity',
    yLabelMode: 'y label end',
    yLabelText: 'y label text',
    yLabelOffset: 'y label offset',
    yLabelColor: 'y label color',
    yLabelSize: 'y label size',
    yLabelOpacity: 'y label opacity',
  },
  options: {
    axisMode: { both: 'x and y', x: 'x only', y: 'y only' },
    extentMode: { symmetric: 'Symmetric', directional: 'Per direction' },
    gridSpacingMode: { uniform: 'Uniform', separate: 'Per direction' },
    dash: { solid: 'Solid', dashed: 'Dashed', dotted: 'Dotted' },
    lineCap: { butt: 'Butt', round: 'Round', square: 'Square' },
    axisLineMode: {
      off: 'Hide line',
      none: 'No arrows',
      positive: 'Positive arrow',
      negative: 'Negative arrow',
      both: 'Both arrows',
    },
    tickMode: {
      none: 'Hidden',
      spacing: 'Regular spacing',
      spacingLabels: 'Spacing + labels',
      values: 'Explicit values',
      valuesLabels: 'Values + labels',
    },
    tickExtent: { positive: 'Positive only', negative: 'Negative only', both: 'Both directions' },
    tickSide: {
      x: { positive: 'Above only', negative: 'Below only', both: 'Above and below' },
      y: { positive: 'Right only', negative: 'Left only', both: 'Left and right' },
    },
    labelMode: { off: 'Hidden', positive: 'Positive', negative: 'Negative' },
    arrowShape: {
      normal: 'Solid triangle',
      open: 'Open triangle',
      stealth: 'Solid stealth',
      openStealth: 'Open stealth',
      diamond: 'Solid diamond',
      openDiamond: 'Open diamond',
      circle: 'Solid circle',
      openCircle: 'Open circle',
    },
  },
});

/** Stable documentation contract for the Axes playground */
export const previewControlContract = {
  controls: axesPlaygroundEnControls,
  canonicalValues: axesPlaygroundCanonicalValues,
  relatedApis: axesPlaygroundRelatedApis,
} satisfies PreviewControlContract;
