import type { PreviewControlContract } from '@/modules/docs/preview';

import {
  axesPlaygroundCanonicalValues,
  axesPlaygroundRelatedApis,
  createAxesPlaygroundControls,
} from './axes-playground.control-builder';

/** Axes 全量公开属性的中文控制面板 */
export const axesPlaygroundControls = createAxesPlaygroundControls({
  title: 'Axes 控制面板',
  sections: {
    coordinate: '坐标系',
    grid: '网格',
    gridGeometry: '网格几何',
    gridStyle: '网格样式',
    xAxis: 'x 轴',
    yAxis: 'y 轴',
    origin: '原点文字',
  },
  fields: {
    axisMode: '显示轴',
    originX: '原点 x',
    originY: '原点 y',
    extentMode: '范围模式',
    extentX: 'x 轴长度',
    extentY: 'y 轴长度',
    xNegative: 'x 负向长度',
    xPositive: 'x 正向长度',
    yNegative: 'y 负向长度',
    yPositive: 'y 正向长度',
    gridEnabled: '显示网格',
    gridSpacingMode: '网格间距模式',
    gridSpacing: '统一间距',
    gridSpacingX: 'x 方向间距',
    gridSpacingY: 'y 方向间距',
    gridOffsetX: 'x 起算偏移',
    gridOffsetY: 'y 起算偏移',
    gridStroke: '网格颜色',
    gridStrokeWidth: '网格线宽',
    gridDash: '网格线型',
    gridDashOffset: '虚线相位',
    gridLineCap: '线帽',
    gridOpacity: '网格透明度',
    gridSeparateDirections: '分别设置方向颜色',
    gridVerticalStroke: '竖线颜色',
    gridHorizontalStroke: '横线颜色',
    originEnabled: '显示原点文字',
    originText: '原点文字',
    originOffset: '原点文字距离',
    originColor: '原点文字颜色',
    originSize: '原点文字字号',
    originOpacity: '原点文字透明度',
    xLineMode: 'x 轴线与箭头',
    xLineStroke: 'x 轴线颜色',
    xLineStrokeWidth: 'x 轴线宽',
    xLineDash: 'x 轴线型',
    xLineOpacity: 'x 轴线透明度',
    xArrowShape: 'x 箭头形状',
    xArrowScale: 'x 箭头缩放',
    xArrowLength: 'x 箭头长度',
    xArrowWidth: 'x 箭头宽度',
    xArrowColor: 'x 箭头颜色',
    xArrowOpacity: 'x 箭头透明度',
    xTickMode: 'x 刻度来源',
    xTickSpacing: 'x 刻度间距',
    xTickExtent: 'x 刻度方向',
    xTickNegativeValue: 'x 负刻度位置',
    xTickPositiveValue: 'x 正刻度位置',
    xTickSide: 'x 刻度伸出侧',
    xTickEndpointGap: 'x 端点留白',
    xTickLength: 'x 刻度长度',
    xTickStroke: 'x 刻度颜色',
    xTickStrokeWidth: 'x 刻度线宽',
    xTickDash: 'x 刻度线型',
    xTickLabelNegativeText: 'x 负刻度文字',
    xTickLabelPositiveText: 'x 正刻度文字',
    xTickLabelOffset: 'x 刻度文字距离',
    xTickLabelColor: 'x 刻度文字颜色',
    xTickLabelSize: 'x 刻度文字字号',
    xTickLabelOpacity: 'x 刻度文字透明度',
    xLabelMode: 'x 轴名位置',
    xLabelText: 'x 轴名',
    xLabelOffset: 'x 轴名距离',
    xLabelColor: 'x 轴名颜色',
    xLabelSize: 'x 轴名字号',
    xLabelOpacity: 'x 轴名透明度',
    yLineMode: 'y 轴线与箭头',
    yLineStroke: 'y 轴线颜色',
    yLineStrokeWidth: 'y 轴线宽',
    yLineDash: 'y 轴线型',
    yLineOpacity: 'y 轴线透明度',
    yArrowShape: 'y 箭头形状',
    yArrowScale: 'y 箭头缩放',
    yArrowLength: 'y 箭头长度',
    yArrowWidth: 'y 箭头宽度',
    yArrowColor: 'y 箭头颜色',
    yArrowOpacity: 'y 箭头透明度',
    yTickMode: 'y 刻度来源',
    yTickSpacing: 'y 刻度间距',
    yTickExtent: 'y 刻度方向',
    yTickNegativeValue: 'y 负刻度位置',
    yTickPositiveValue: 'y 正刻度位置',
    yTickSide: 'y 刻度伸出侧',
    yTickEndpointGap: 'y 端点留白',
    yTickLength: 'y 刻度长度',
    yTickStroke: 'y 刻度颜色',
    yTickStrokeWidth: 'y 刻度线宽',
    yTickDash: 'y 刻度线型',
    yTickLabelNegativeText: 'y 负刻度文字',
    yTickLabelPositiveText: 'y 正刻度文字',
    yTickLabelOffset: 'y 刻度文字距离',
    yTickLabelColor: 'y 刻度文字颜色',
    yTickLabelSize: 'y 刻度文字字号',
    yTickLabelOpacity: 'y 刻度文字透明度',
    yLabelMode: 'y 轴名位置',
    yLabelText: 'y 轴名',
    yLabelOffset: 'y 轴名距离',
    yLabelColor: 'y 轴名颜色',
    yLabelSize: 'y 轴名字号',
    yLabelOpacity: 'y 轴名透明度',
  },
  options: {
    axisMode: { both: 'x / y 轴', x: '仅 x 轴', y: '仅 y 轴' },
    extentMode: { symmetric: '两侧等长', directional: '分别设置' },
    gridSpacingMode: { uniform: '统一间距', separate: '分方向间距' },
    dash: { solid: '实线', dashed: '虚线', dotted: '点线' },
    lineCap: { butt: '平直', round: '圆头', square: '方头' },
    axisLineMode: { off: '隐藏轴线', none: '无箭头', positive: '正端箭头', negative: '负端箭头', both: '双端箭头' },
    tickMode: {
      none: '不显示',
      spacing: '规则间距',
      spacingLabels: '规则间距 + 文字',
      values: '显式位置',
      valuesLabels: '显式位置 + 文字',
    },
    tickExtent: { positive: '仅正向', negative: '仅负向', both: '两个方向' },
    tickSide: {
      x: { positive: '仅上方', negative: '仅下方', both: '上下两侧' },
      y: { positive: '仅右侧', negative: '仅左侧', both: '左右两侧' },
    },
    labelMode: { off: '隐藏', positive: '正端', negative: '负端' },
    arrowShape: {
      normal: '实心三角',
      open: '空心三角',
      stealth: '实心锐箭',
      openStealth: '空心锐箭',
      diamond: '实心菱形',
      openDiamond: '空心菱形',
      circle: '实心圆点',
      openCircle: '空心圆点',
    },
  },
});

/** 当前 Axes playground 的稳定文档契约 */
export const previewControlContract = {
  controls: axesPlaygroundControls,
  canonicalValues: axesPlaygroundCanonicalValues,
  relatedApis: axesPlaygroundRelatedApis,
} satisfies PreviewControlContract;
