import type { ChartPresentationAuthoringRecord, IRChart } from '@retikz/chart';
import type { CreateChartInput } from '@retikz/chart-vanilla';
import type { IRChild } from '@retikz/core';
import type { ExternalDatasets } from '@retikz/data';
import type { IRPlotSpec } from '@retikz/plot';
import type { IRTableSpec } from '@retikz/table';
import type { AnyInputEmbedAdapter, InputChild } from '@retikz/vanilla';

import { ChartSchema } from '@retikz/chart';
import { createChart, renderChart } from '@retikz/chart-vanilla';
import {
  FlexLayoutDefinition,
  FlexLayoutSchema,
  GridLayoutDefinition,
  GridLayoutSchema,
  OverlayLayoutDefinition,
  OverlayLayoutSchema,
} from '@retikz/layout';
import {
  flexLayout,
  FlexLayoutInputEmbedAdapter,
  gridLayout,
  GridLayoutInputEmbedAdapter,
  overlayLayout,
  OverlayLayoutInputEmbedAdapter,
} from '@retikz/layout-vanilla';
import {
  ConnectorDefinition,
  ConnectorSchema,
  DecisionDefinition,
  DecisionSchema,
  JunctionDefinition,
  JunctionSchema,
  LogicFrameDefinition,
  LogicFrameSchema,
  StageDefinition,
  StageSchema,
  TerminalDefinition,
  TerminalSchema,
} from '@retikz/notation';
import {
  connector,
  ConnectorInputEmbedAdapter,
  decision,
  DecisionInputEmbedAdapter,
  junction,
  JunctionInputEmbedAdapter,
  logicFrame,
  LogicFrameInputEmbedAdapter,
  stage,
  StageInputEmbedAdapter,
  terminal,
  TerminalInputEmbedAdapter,
} from '@retikz/notation-vanilla';
import { PlotSpecSchema } from '@retikz/plot';
import { renderPlot } from '@retikz/plot-vanilla';
import {
  AxesDefinition,
  AxesSchema,
  FrameDefinition,
  FrameSchema,
  GridDefinition,
  GridSchema,
  LegendDefinition,
  LegendSchema,
  SurfaceDefinition,
  SurfaceSchema,
} from '@retikz/standard';
import {
  axes,
  AxesInputEmbedAdapter,
  frame,
  FrameInputEmbedAdapter,
  grid,
  GridInputEmbedAdapter,
  legend,
  LegendInputEmbedAdapter,
  surface,
  surfaceChild,
  SurfaceInputEmbedAdapter,
} from '@retikz/standard-vanilla';
import { TableSpecSchema, TableStructureKind } from '@retikz/table';
import { embedTable, TableInputEmbedAdapter } from '@retikz/table-vanilla';
import { renderToSvgString, scene, scope } from '@retikz/vanilla';

import type { PreviewIR } from '../utils/build-preview-ir';
import type { BuildVanillaPreviewOptions, VanillaPreviewArtifact } from './types';

import { PreviewThemeDefinitionBundle } from '../theme/presets';
import { collectPreviewDefinitions, formatVanillaValue, irToVanillaCode } from '../utils/ir-to-vanilla-code';

type CompositeChild = IRChild & { namespace: string; type: string };

const isComposite = (child: IRChild): child is CompositeChild => 'namespace' in child;

const collectComposites = (children: ReadonlyArray<IRChild>): Array<CompositeChild> => {
  const composites: Array<CompositeChild> = [];
  const visit = (child: IRChild): void => {
    if (isComposite(child)) {
      composites.push(child);
      return;
    }
    if (child.type === 'scope') child.children.forEach(visit);
  };
  children.forEach(visit);
  return composites;
};

const outputSize = (preview: PreviewIR): { width?: number; height?: number } => ({
  ...(typeof preview.width === 'number' ? { width: preview.width } : {}),
  ...(typeof preview.height === 'number' ? { height: preview.height } : {}),
});

const diagnostic = (message: string): VanillaPreviewArtifact => ({ code: `// ${message}` });

/** 把纯 Core IR child 转为不含运行时 authoring 的 Vanilla spec */
const convertCoreChild = (child: IRChild): InputChild => {
  if ('namespace' in child) throw new Error(`Unexpected Tier 2 composite "${child.namespace}.${child.type}".`);
  if (child.type !== 'scope') return child;
  return {
    ...child,
    children: child.children.map(convertCoreChild),
  };
};

const buildCorePreview = (preview: PreviewIR, options: BuildVanillaPreviewOptions): VanillaPreviewArtifact => {
  const input = scene({
    ...(options.theme === undefined ? {} : { theme: options.theme }),
    ...(preview.ir.viewBox !== undefined ? { viewBox: preview.ir.viewBox } : {}),
    ...(preview.ir.animations !== undefined ? { animations: preview.ir.animations } : {}),
    children: preview.ir.children.map(convertCoreChild),
  });
  return {
    code: irToVanillaCode(preview.ir),
    svg: renderToSvgString(input, { output: outputSize(preview) }),
  };
};

type StandardKind = 'grid' | 'axes' | 'frame' | 'surface' | 'legend';

type LayoutKind = 'flexLayout' | 'gridLayout' | 'overlayLayout';

type LibraryKind = StandardKind | LayoutKind;

type NotationKind = 'logicFrame' | 'terminal' | 'stage' | 'decision' | 'junction' | 'connector';

type LibraryConversionState = {
  counts: Record<LibraryKind, number>;
  adapters: Set<LibraryKind>;
  /** Canonical authored IDs to IDs generated by Vanilla embeds. */
  ids: Map<string, string>;
};

type NotationConversionState = {
  counts: Record<NotationKind, number>;
  adapters: Set<NotationKind>;
  /** Canonical authored IDs to IDs generated by Vanilla embeds. */
  ids: Map<string, string>;
};

const libraryCanonicalId = (kind: LibraryKind, embedId: string): string => {
  switch (kind) {
    case 'frame':
      return `${embedId}/frame`;
    case 'surface':
      return `${embedId}/surface`;
    default:
      return embedId;
  }
};

const notationCanonicalId = (kind: NotationKind, embedId: string): string =>
  kind === 'logicFrame' ? `${embedId}/${kind}` : embedId;

const nextLibraryId = (kind: LibraryKind, state: LibraryConversionState, authoredId?: string): string => {
  state.counts[kind] += 1;
  state.adapters.add(kind);
  const embedId = `preview-${kind}-${state.counts[kind]}`;
  if (authoredId !== undefined) {
    const generatedId = libraryCanonicalId(kind, embedId);
    state.ids.set(authoredId, generatedId);
    state.ids.set(generatedId, generatedId);
    if (kind === 'frame') {
      state.ids.set(`${authoredId}/${kind}`, generatedId);
    }
  }
  return embedId;
};

const nextNotationId = (kind: NotationKind, state: NotationConversionState, authoredId?: string): string => {
  state.counts[kind] += 1;
  state.adapters.add(kind);
  const embedId = `preview-${kind}-${state.counts[kind]}`;
  if (authoredId !== undefined) {
    const generatedId = notationCanonicalId(kind, embedId);
    state.ids.set(authoredId, generatedId);
    state.ids.set(generatedId, generatedId);
    if (kind === 'logicFrame') {
      state.ids.set(`${authoredId}/${kind}`, generatedId);
    }
  }
  return embedId;
};

const rewriteLogicTarget = (value: unknown, state: NotationConversionState): unknown => {
  if (typeof value !== 'object' || value === null || !('id' in value)) return value;
  const target = value as { id: string; [key: string]: unknown };
  const id = state.ids.get(target.id) ?? target.id;
  return id === target.id ? value : { ...target, id };
};

/** 只改写 Core Step 明确拥有的目标字段 */
const rewriteConnectorStep = (value: unknown, state: NotationConversionState): unknown => {
  if (typeof value !== 'object' || value === null) return value;
  const step = value as Record<string, unknown>;
  return {
    ...step,
    ...('to' in step ? { to: rewriteLogicTarget(step.to, state) } : {}),
    ...('from' in step ? { from: rewriteLogicTarget(step.from, state) } : {}),
    ...('center' in step ? { center: rewriteLogicTarget(step.center, state) } : {}),
    ...(Array.isArray(step.points) ? { points: step.points.map(point => rewriteLogicTarget(point, state)) } : {}),
  };
};

const rewriteLogicInput = (
  kind: NotationKind,
  input: Record<string, unknown>,
  state: NotationConversionState,
): Record<string, unknown> => {
  if (kind === 'connector') {
    return {
      ...input,
      ...(Array.isArray(input.children)
        ? { children: input.children.map(step => rewriteConnectorStep(step, state)) }
        : {}),
    };
  }
  return input;
};

const registerPreviewIds = (
  children: ReadonlyArray<IRChild>,
  libraryState: LibraryConversionState,
  notationState: NotationConversionState,
): void => {
  const visit = (child: IRChild): void => {
    if (isComposite(child)) {
      const authoredId = (child as { id?: unknown }).id;
      if (child.namespace === 'standard' && typeof authoredId === 'string') {
        const kind = child.type as StandardKind;
        if (['grid', 'axes', 'frame', 'surface', 'legend'].includes(kind)) {
          // Reserve deterministic IDs before converting child targets.
          nextLibraryId(kind, libraryState, authoredId);
          libraryState.counts[kind] -= 1;
          libraryState.adapters.delete(kind);
        }
      }
      if (child.namespace === 'layout' && typeof authoredId === 'string') {
        const kind = child.type as LayoutKind;
        if (['flexLayout', 'gridLayout', 'overlayLayout'].includes(kind)) {
          nextLibraryId(kind, libraryState, authoredId);
          libraryState.counts[kind] -= 1;
          libraryState.adapters.delete(kind);
        }
      }
      if (child.namespace === 'notation' && typeof authoredId === 'string') {
        const kind = child.type as NotationKind;
        if (['logicFrame', 'terminal', 'stage', 'decision', 'junction', 'connector'].includes(kind)) {
          nextNotationId(kind, notationState, authoredId);
          notationState.counts[kind] -= 1;
          notationState.adapters.delete(kind);
        }
      }
      return;
    }
    if (child.type === 'scope') child.children.forEach(visit);
  };
  children.forEach(visit);
};

const convertStandardChild = (
  child: CompositeChild,
  state: LibraryConversionState,
  notationState: NotationConversionState,
): InputChild => {
  const childId = (child as { id?: string }).id;
  switch (child.type) {
    case 'grid': {
      const { namespace: _namespace, type: _type, ...input } = GridSchema.parse(child);
      void _namespace;
      void _type;
      return grid(nextLibraryId('grid', state, childId), input);
    }
    case 'axes': {
      const { namespace: _namespace, type: _type, ...input } = AxesSchema.parse(child);
      void _namespace;
      void _type;
      return axes(nextLibraryId('axes', state, childId), input);
    }
    case 'frame': {
      const { namespace: _namespace, type: _type, id: _id, ...input } = FrameSchema.parse(child);
      void _namespace;
      void _type;
      void _id;
      return frame(nextLibraryId('frame', state, childId), input);
    }
    case 'legend': {
      const { namespace: _namespace, type: _type, title, content, ...input } = LegendSchema.parse(child);
      void _namespace;
      void _type;
      const normalizedContent =
        content.kind === 'items'
          ? {
              ...content,
              items: content.items.map(item => ({
                ...item,
                sample: convertPreviewChild(item.sample, state, notationState),
                ...(item.label === undefined ? {} : { label: convertPreviewChild(item.label, state, notationState) }),
              })),
            }
          : {
              ...content,
              sample: convertPreviewChild(content.sample, state, notationState),
              ticks: content.ticks.map(tick => ({
                ...tick,
                ...(tick.label === undefined ? {} : { label: convertPreviewChild(tick.label, state, notationState) }),
              })),
            };
      return legend(nextLibraryId('legend', state, childId), {
        ...input,
        ...(title === undefined ? {} : { title: convertPreviewChild(title, state, notationState) }),
        content: normalizedContent,
      });
    }
    case 'surface': {
      const { namespace: _namespace, type: _type, id: _id, child: nested, ...input } = SurfaceSchema.parse(child);
      void _namespace;
      void _type;
      void _id;
      return surface(nextLibraryId('surface', state, childId), {
        ...input,
        child: surfaceChild(convertPreviewChild(nested, state, notationState)),
      });
    }
    default:
      throw new Error(`Unsupported Standard composite "${child.namespace}.${child.type}".`);
  }
};

const convertLayoutChild = (
  child: CompositeChild,
  state: LibraryConversionState,
  notationState: NotationConversionState,
): InputChild => {
  const childId = (child as { id?: string }).id;
  switch (child.type) {
    case 'flexLayout': {
      const { namespace: _namespace, type: _type, children, ...input } = FlexLayoutSchema.parse(child);
      void _namespace;
      void _type;
      return flexLayout(nextLibraryId('flexLayout', state, childId), {
        ...input,
        children: children.map(item => ({
          ...item,
          child: convertPreviewChild(item.child, state, notationState),
        })),
      });
    }
    case 'gridLayout': {
      const { namespace: _namespace, type: _type, children, ...input } = GridLayoutSchema.parse(child);
      void _namespace;
      void _type;
      return gridLayout(nextLibraryId('gridLayout', state, childId), {
        ...input,
        children: children.map(item => ({
          ...item,
          child: convertPreviewChild(item.child, state, notationState),
        })),
      });
    }
    case 'overlayLayout': {
      const { namespace: _namespace, type: _type, children, ...input } = OverlayLayoutSchema.parse(child);
      void _namespace;
      void _type;
      return overlayLayout(nextLibraryId('overlayLayout', state, childId), {
        ...input,
        children: children.map(item => ({
          ...item,
          child: convertPreviewChild(item.child, state, notationState),
        })),
      });
    }
    default:
      throw new Error(`Unsupported Layout composite "${child.namespace}.${child.type}".`);
  }
};

const convertNotationChild = (child: CompositeChild, state: NotationConversionState): InputChild => {
  const childId = (child as { id?: string }).id;
  switch (child.type) {
    case 'logicFrame': {
      const { namespace: _namespace, type: _type, id: _id, ...input } = LogicFrameSchema.parse(child);
      void _namespace;
      void _type;
      void _id;
      return logicFrame(nextNotationId('logicFrame', state, childId), input);
    }
    case 'terminal': {
      const { namespace: _namespace, type: _type, id: _id, ...input } = TerminalSchema.parse(child);
      void _namespace;
      void _type;
      void _id;
      return terminal(nextNotationId('terminal', state, childId), input);
    }
    case 'stage': {
      const { namespace: _namespace, type: _type, id: _id, ...input } = StageSchema.parse(child);
      void _namespace;
      void _type;
      void _id;
      return stage(nextNotationId('stage', state, childId), input);
    }
    case 'decision': {
      const { namespace: _namespace, type: _type, id: _id, ...input } = DecisionSchema.parse(child);
      void _namespace;
      void _type;
      void _id;
      return decision(nextNotationId('decision', state, childId), input);
    }
    case 'junction': {
      const { namespace: _namespace, type: _type, id: _id, ...input } = JunctionSchema.parse(child);
      void _namespace;
      void _type;
      void _id;
      return junction(nextNotationId('junction', state, childId), input);
    }
    case 'connector': {
      const { namespace: _namespace, type: _type, id: _id, ...input } = ConnectorSchema.parse(child);
      void _namespace;
      void _type;
      void _id;
      return connector(
        nextNotationId('connector', state, childId),
        rewriteLogicInput('connector', input, state) as Parameters<typeof connector>[1],
      );
    }
    default:
      throw new Error(`Unsupported Notation composite "${child.namespace}.${child.type}".`);
  }
};

const convertPreviewChild = (
  child: IRChild,
  libraryState: LibraryConversionState,
  notationState: NotationConversionState,
): InputChild => {
  if (isComposite(child)) {
    if (child.namespace === 'standard') return convertStandardChild(child, libraryState, notationState);
    if (child.namespace === 'layout') return convertLayoutChild(child, libraryState, notationState);
    if (child.namespace === 'notation') return convertNotationChild(child, notationState);
    throw new Error(`Unsupported composite "${child.namespace}.${child.type}".`);
  }
  if (child.type !== 'scope') return child;
  const { children, type: _type, ...config } = child;
  void _type;
  return scope(
    config,
    children.map(nested => convertPreviewChild(nested, libraryState, notationState)),
  );
};

const standardAdapters = (state: LibraryConversionState): ReadonlyArray<AnyInputEmbedAdapter> => [
  ...(state.adapters.has('grid') ? [GridInputEmbedAdapter as AnyInputEmbedAdapter] : []),
  ...(state.adapters.has('axes') ? [AxesInputEmbedAdapter as AnyInputEmbedAdapter] : []),
  ...(state.adapters.has('frame') ? [FrameInputEmbedAdapter as AnyInputEmbedAdapter] : []),
  ...(state.adapters.has('surface') ? [SurfaceInputEmbedAdapter as AnyInputEmbedAdapter] : []),
  ...(state.adapters.has('legend') ? [LegendInputEmbedAdapter as AnyInputEmbedAdapter] : []),
];

const layoutAdapters = (state: LibraryConversionState): ReadonlyArray<AnyInputEmbedAdapter> => [
  ...(state.adapters.has('flexLayout') ? [FlexLayoutInputEmbedAdapter as AnyInputEmbedAdapter] : []),
  ...(state.adapters.has('gridLayout') ? [GridLayoutInputEmbedAdapter as AnyInputEmbedAdapter] : []),
  ...(state.adapters.has('overlayLayout') ? [OverlayLayoutInputEmbedAdapter as AnyInputEmbedAdapter] : []),
];

const notationAdapters = (state: NotationConversionState): ReadonlyArray<AnyInputEmbedAdapter> => [
  ...(state.adapters.has('logicFrame') ? [LogicFrameInputEmbedAdapter as AnyInputEmbedAdapter] : []),
  ...(state.adapters.has('terminal') ? [TerminalInputEmbedAdapter as AnyInputEmbedAdapter] : []),
  ...(state.adapters.has('stage') ? [StageInputEmbedAdapter as AnyInputEmbedAdapter] : []),
  ...(state.adapters.has('decision') ? [DecisionInputEmbedAdapter as AnyInputEmbedAdapter] : []),
  ...(state.adapters.has('junction') ? [JunctionInputEmbedAdapter as AnyInputEmbedAdapter] : []),
  ...(state.adapters.has('connector') ? [ConnectorInputEmbedAdapter as AnyInputEmbedAdapter] : []),
];

const standardDefinitionByName = {
  GridDefinition,
  AxesDefinition,
  FrameDefinition,
  SurfaceDefinition,
  LegendDefinition,
} as const;

const layoutDefinitionByName = {
  FlexLayoutDefinition,
  GridLayoutDefinition,
  OverlayLayoutDefinition,
} as const;

const notationDefinitionByName = {
  LogicFrameDefinition,
  TerminalDefinition,
  StageDefinition,
  DecisionDefinition,
  JunctionDefinition,
  ConnectorDefinition,
} as const;

const buildLibraryPreview = (preview: PreviewIR, options: BuildVanillaPreviewOptions): VanillaPreviewArtifact => {
  const ids = new Map<string, string>();
  const libraryState: LibraryConversionState = {
    counts: {
      grid: 0,
      axes: 0,
      frame: 0,
      surface: 0,
      flexLayout: 0,
      gridLayout: 0,
      overlayLayout: 0,
      legend: 0,
    },
    adapters: new Set(),
    ids,
  };
  const notationState: NotationConversionState = {
    counts: {
      logicFrame: 0,
      terminal: 0,
      stage: 0,
      decision: 0,
      junction: 0,
      connector: 0,
    },
    adapters: new Set(),
    ids,
  };
  registerPreviewIds(preview.ir.children, libraryState, notationState);
  const input = scene({
    ...(options.theme === undefined ? {} : { theme: options.theme }),
    ...(preview.ir.viewBox !== undefined ? { viewBox: preview.ir.viewBox } : {}),
    ...(preview.ir.animations !== undefined ? { animations: preview.ir.animations } : {}),
    children: preview.ir.children.map(child => convertPreviewChild(child, libraryState, notationState)),
  });
  const definitionNames = collectPreviewDefinitions(
    preview.ir.children,
    new Set(
      Array.from(libraryState.adapters).filter((kind): kind is StandardKind =>
        ['grid', 'axes', 'frame', 'surface', 'legend'].includes(kind),
      ),
    ),
    new Set(
      Array.from(libraryState.adapters).filter((kind): kind is LayoutKind =>
        ['flexLayout', 'gridLayout', 'overlayLayout'].includes(kind),
      ),
    ),
    new Set(notationState.adapters),
  );
  const definitions = [
    ...definitionNames.standard.map(name => standardDefinitionByName[name]),
    ...definitionNames.layout.map(name => layoutDefinitionByName[name]),
    ...definitionNames.notation.map(name => notationDefinitionByName[name]),
  ];
  const compile = definitions.length === 0 ? undefined : { composites: definitions };
  return {
    code: irToVanillaCode(preview.ir),
    svg: renderToSvgString(input, {
      adapters: [
        ...standardAdapters(libraryState),
        ...layoutAdapters(libraryState),
        ...notationAdapters(notationState),
      ],
      output: outputSize(preview),
      ...(compile === undefined ? {} : { compile }),
    }),
  };
};

/** 从已收集的 provider graph contribution 中读取一个 owner dataset */
const findProviderDataset = (
  preview: PreviewIR,
  namespace: string,
  reference: string,
  label: string,
): ExternalDatasets | null => {
  let dataset: unknown;
  let found = false;
  for (const contribution of preview.contributions) {
    for (const provider of contribution.providers) {
      if (
        provider.key.capability !== 'composite' ||
        provider.key.namespace !== namespace ||
        !Object.hasOwn(provider.datasets, reference)
      )
        continue;
      const candidate = provider.datasets[reference];
      if (found && dataset !== candidate) {
        throw new Error(`${label} dataset reference "${reference}" resolves to different values.`);
      }
      dataset = candidate;
      found = true;
    }
  }
  return found ? ({ [reference]: dataset } as ExternalDatasets) : null;
};

/** 读取 Plot provider-local dataset */
const findPlotDataset = (preview: PreviewIR, spec: IRPlotSpec): ExternalDatasets | null =>
  findProviderDataset(preview, 'plot', spec.data.reference, 'Plot');

const buildPlotCode = (spec: IRPlotSpec, datasets: ExternalDatasets, preview: PreviewIR): string => {
  const size = outputSize(preview);
  const options = Object.keys(size).length > 0 ? `, ${formatVanillaValue(size)}` : '';
  return `import { renderPlot } from '@retikz/plot-vanilla';\n\nconst spec = ${formatVanillaValue(spec)};\nconst datasets = ${formatVanillaValue(datasets)};\n\nexport const svg = renderPlot(spec, datasets${options});\n`;
};

const buildPlotPreview = (
  preview: PreviewIR,
  composite: CompositeChild,
  options: BuildVanillaPreviewOptions,
): VanillaPreviewArtifact => {
  const spec = PlotSpecSchema.parse(composite);
  const datasets = findPlotDataset(preview, spec);
  if (datasets === null) {
    return diagnostic(`Cannot generate Vanilla preview: Plot dataset "${spec.data.reference}" was not captured.`);
  }
  const size = outputSize(preview);
  return {
    code: buildPlotCode(spec, datasets, preview),
    svg: renderPlot(spec, datasets, {
      ...size,
      ...(options.theme === undefined ? {} : { theme: options.theme }),
    }),
  };
};

const findTableDatasets = (preview: PreviewIR, spec: IRTableSpec): ExternalDatasets | null => {
  if (spec.data === undefined) return {};
  return findProviderDataset(preview, 'table', spec.data.reference, 'Table');
};

type DatasetImportCode = {
  imports: string;
  expression: string;
};

const identifierPattern = /^[A-Za-z_$][\w$]*$/;

const buildDatasetImportCode = (
  datasets: ExternalDatasets,
  options: BuildVanillaPreviewOptions,
): DatasetImportCode | null => {
  const references = Object.keys(datasets);
  if (references.length === 0) return { imports: '', expression: '{}' };
  const bindings = references.map(reference => options.datasetImports?.[reference]);
  if (bindings.some(binding => binding === undefined)) return null;

  const importsBySource = new Map<string, Array<string>>();
  bindings.forEach(binding => {
    if (binding === undefined) return;
    if (!identifierPattern.test(binding.name)) {
      throw new Error(`Dataset import name "${binding.name}" is not a supported identifier.`);
    }
    const names = importsBySource.get(binding.from) ?? [];
    if (!names.includes(binding.name)) names.push(binding.name);
    importsBySource.set(binding.from, names);
  });
  const imports = Array.from(
    importsBySource,
    ([from, names]) => `import { ${names.join(', ')} } from ${formatVanillaValue(from)};`,
  ).join('\n');
  const expression = `{ ${references
    .map((reference, index) => {
      const key = identifierPattern.test(reference) ? reference : formatVanillaValue(reference);
      return `${key}: ${bindings[index]?.name ?? 'undefined'}`;
    })
    .join(', ')} }`;
  return { imports, expression };
};

/** 从 canonical children 恢复仅用于 Vanilla helper 的 authored order 与 top/bottom 分区。 */
const chartPresentationRecords = (chart: IRChart): Array<ChartPresentationAuthoringRecord> | undefined => {
  const children = chart.presentation?.children;
  if (children === undefined) return undefined;
  const plotIndex = children.findIndex(item => item.kind === 'plot');
  return children.flatMap((item, index) => {
    if (item.kind === 'plot') return [];
    const { kind: _kind, key: _key, ...record } = item;
    void _kind;
    void _key;
    return [{ ...record, position: index < plotIndex ? ('top' as const) : ('bottom' as const) }];
  });
};

/** 将 canonical Chart 还原为公开 Chart Vanilla authoring input。 */
const chartAuthoringInput = (chart: IRChart, datasets: ExternalDatasets): CreateChartInput => {
  const presentation = chartPresentationRecords(chart);
  return {
    plot: { spec: chart.plot },
    datasets,
    ...(chart.id === undefined ? {} : { id: chart.id }),
    ...(chart.chartThemeTokens === undefined ? {} : { chartThemeTokens: chart.chartThemeTokens }),
    ...(presentation === undefined ? {} : { presentation }),
  };
};

const buildChartCode = (
  chart: IRChart,
  datasets: ExternalDatasets,
  preview: PreviewIR,
  options: BuildVanillaPreviewOptions,
): string => {
  const datasetImport = buildDatasetImportCode(datasets, options);
  const importCode = datasetImport === null || datasetImport.imports.length === 0 ? '' : `${datasetImport.imports}\n`;
  const dataCode = datasetImport === null ? `const datasets = ${formatVanillaValue(datasets)};\n\n` : '';
  const dataExpression = datasetImport?.expression ?? 'datasets';
  const { datasets: _datasets, ...authoring } = chartAuthoringInput(chart, datasets);
  void _datasets;
  const inputCode = formatVanillaValue({
    ...authoring,
    datasets: '__DATASETS__',
    ...(options.theme === undefined ? {} : { theme: options.theme }),
    themeStyles: '__CORE_THEME_STYLES__',
    chartThemeStyles: '__CHART_THEME_STYLES__',
    lowerOptions: { plotThemeStyles: '__PLOT_THEME_STYLES__' },
  })
    .replace("'__DATASETS__'", dataExpression)
    .replace("'__CORE_THEME_STYLES__'", 'PreviewThemeDefinitionBundle.core')
    .replace("'__CHART_THEME_STYLES__'", 'PreviewThemeDefinitionBundle.chart')
    .replace("'__PLOT_THEME_STYLES__'", 'PreviewThemeDefinitionBundle.plot');
  const size = outputSize(preview);
  const renderOptions = {
    ...(Object.keys(size).length === 0 ? {} : { output: size }),
  };
  const renderOptionsCode = Object.keys(renderOptions).length === 0 ? '' : `, ${formatVanillaValue(renderOptions)}`;
  return `import { createChart, renderChart } from '@retikz/chart-vanilla';\nimport { PreviewThemeDefinitionBundle } from '@/modules/docs/components/component-preview/theme';\n${importCode}\n${dataCode}const chart = createChart(${inputCode});\n\nexport const svg = renderChart(chart${renderOptionsCode}).svg;\n`;
};

const buildChartPreview = (
  preview: PreviewIR,
  composite: CompositeChild,
  options: BuildVanillaPreviewOptions,
): VanillaPreviewArtifact => {
  const chart = ChartSchema.parse(composite);
  const datasets = findPlotDataset(preview, chart.plot);
  if (datasets === null) {
    return diagnostic(
      `Cannot generate Vanilla preview: Chart dataset "${chart.plot.data.reference}" was not captured.`,
    );
  }
  const size = outputSize(preview);
  const rendered = renderChart(
    createChart({
      ...chartAuthoringInput(chart, datasets),
      ...(options.theme === undefined ? {} : { theme: options.theme }),
      themeStyles: PreviewThemeDefinitionBundle.core,
      chartThemeStyles: PreviewThemeDefinitionBundle.chart,
      lowerOptions: { plotThemeStyles: PreviewThemeDefinitionBundle.plot },
    }),
    {
      ...(Object.keys(size).length === 0 ? {} : { output: size }),
    },
  );
  return {
    code: buildChartCode(chart, datasets, preview, options),
    svg: rendered.svg,
  };
};

const buildTableCode = (
  spec: IRTableSpec,
  datasets: ExternalDatasets,
  preview: PreviewIR,
  options: BuildVanillaPreviewOptions,
): string => {
  const hasDatasets = Object.keys(datasets).length > 0;
  const datasetImport = hasDatasets ? buildDatasetImportCode(datasets, options) : null;
  const importCode = datasetImport === null || datasetImport.imports.length === 0 ? '' : `${datasetImport.imports}\n`;
  const dataCode = hasDatasets && datasetImport === null ? `const datasets = ${formatVanillaValue(datasets)};\n\n` : '';
  const dataExpression = datasetImport?.expression ?? 'datasets';
  const embedOptions = hasDatasets ? `, { data: ${dataExpression} }` : '';
  const childrenCode = `[embedTable('preview-table-1', spec${embedOptions})]`;
  const figureCode = formatVanillaValue({
    ...(preview.ir.viewBox !== undefined ? { viewBox: preview.ir.viewBox } : {}),
    ...(preview.ir.animations !== undefined ? { animations: preview.ir.animations } : {}),
    children: '__CHILDREN__',
  }).replace("'__CHILDREN__'", childrenCode);
  const size = outputSize(preview);
  const renderOptions = {
    adapters: '__ADAPTERS__',
    ...(Object.keys(size).length > 0 ? { output: size } : {}),
  };
  const optionsCode = formatVanillaValue(renderOptions).replace("'__ADAPTERS__'", '[TableInputEmbedAdapter]');
  return `import { embedTable, TableInputEmbedAdapter } from '@retikz/table-vanilla';\nimport { renderToSvgString, scene } from '@retikz/vanilla';\n${importCode}\nconst spec = ${formatVanillaValue(spec)};\n${dataCode}const input = scene(${figureCode});\n\nexport const svg = renderToSvgString(input, ${optionsCode});\n`;
};

const buildTablePreview = (
  preview: PreviewIR,
  composite: CompositeChild,
  options: BuildVanillaPreviewOptions,
): VanillaPreviewArtifact => {
  const spec = TableSpecSchema.parse(composite);
  if (spec.structure.kind !== TableStructureKind.Detail && spec.structure.kind !== TableStructureKind.Manual) {
    return diagnostic(
      `Cannot generate Vanilla preview: Table structure "${spec.structure.kind}" requires runtime definitions that cannot be serialized.`,
    );
  }
  const datasets = findTableDatasets(preview, spec);
  if (datasets === null && spec.data !== undefined) {
    return diagnostic(`Cannot generate Vanilla preview: Table dataset "${spec.data.reference}" was not captured.`);
  }
  const resolvedDatasets = datasets ?? {};
  const input = scene({
    ...(options.theme === undefined ? {} : { theme: options.theme }),
    ...(preview.ir.viewBox !== undefined ? { viewBox: preview.ir.viewBox } : {}),
    ...(preview.ir.animations !== undefined ? { animations: preview.ir.animations } : {}),
    children: [
      embedTable('preview-table-1', spec, Object.keys(resolvedDatasets).length > 0 ? { data: resolvedDatasets } : {}),
    ],
  });
  return {
    code: buildTableCode(spec, resolvedDatasets, preview, options),
    svg: renderToSvgString(input, { adapters: [TableInputEmbedAdapter], output: outputSize(preview) }),
    replacePreviewRender: false,
  };
};

/** 从统一的预览 IR 上下文生成 Core、Library、Notation、Plot、Chart 或 Table 的 Vanilla 源码与真实 SVG。 */
export const buildVanillaPreview = (
  preview: PreviewIR,
  options: BuildVanillaPreviewOptions = {},
): VanillaPreviewArtifact => {
  const composites = collectComposites(preview.ir.children);
  try {
    if (composites.length === 0) return buildCorePreview(preview, options);
    const firstComposite = composites[0];
    if (
      composites.every(
        child => child.namespace === 'standard' || child.namespace === 'layout' || child.namespace === 'notation',
      )
    ) {
      return buildLibraryPreview(preview, options);
    }
    if (composites.length === 1 && firstComposite.namespace === 'plot' && firstComposite.type === 'plot') {
      return buildPlotPreview(preview, firstComposite, options);
    }
    if (composites.length === 1 && firstComposite.namespace === 'chart' && firstComposite.type === 'chart') {
      return buildChartPreview(preview, firstComposite, options);
    }
    if (composites.length === 1 && firstComposite.namespace === 'table' && firstComposite.type === 'table') {
      return buildTablePreview(preview, firstComposite, options);
    }
    const unsupported = composites.find(
      child =>
        child.namespace !== 'standard' &&
        child.namespace !== 'layout' &&
        child.namespace !== 'notation' &&
        !(child.namespace === 'plot' && child.type === 'plot') &&
        !(child.namespace === 'chart' && child.type === 'chart') &&
        !(child.namespace === 'table' && child.type === 'table'),
    );
    const child = unsupported ?? firstComposite;
    return diagnostic(`Cannot generate Vanilla preview for Tier 2 composite "${child.namespace}.${child.type}".`);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return diagnostic(`Failed to generate Vanilla preview: ${message}`);
  }
};
