/** Palmer Penguins 原始数据地址 */
export const PALMER_PENGUINS_SOURCE_URL = 'https://github.com/vega/vega-datasets/blob/main/data/penguins.json';

/** 数据许可：Palmer Station Antarctica LTER，CC0 */
export const PALMER_PENGUINS_LICENSE = 'CC0 1.0';

/** 原始 344 行中喙长与鳍长均有效的记录数 */
export const PALMER_PENGUINS_VALID_COUNT = 342;

/**
 * 确定性展示样本
 * @description 按源文件顺序从 Adelie、Chinstrap、Gentoo 的有效记录各取前 30 行，缺失喙长或鳍长的 2 行先移除
 */
export const penguinScatterData = [
  { species: 'Adelie', billLengthMm: 39.1, flipperLengthMm: 181 },
  { species: 'Adelie', billLengthMm: 39.5, flipperLengthMm: 186 },
  { species: 'Adelie', billLengthMm: 40.3, flipperLengthMm: 195 },
  { species: 'Adelie', billLengthMm: 36.7, flipperLengthMm: 193 },
  { species: 'Adelie', billLengthMm: 39.3, flipperLengthMm: 190 },
  { species: 'Adelie', billLengthMm: 38.9, flipperLengthMm: 181 },
  { species: 'Adelie', billLengthMm: 39.2, flipperLengthMm: 195 },
  { species: 'Adelie', billLengthMm: 34.1, flipperLengthMm: 193 },
  { species: 'Adelie', billLengthMm: 42, flipperLengthMm: 190 },
  { species: 'Adelie', billLengthMm: 37.8, flipperLengthMm: 186 },
  { species: 'Adelie', billLengthMm: 37.8, flipperLengthMm: 180 },
  { species: 'Adelie', billLengthMm: 41.1, flipperLengthMm: 182 },
  { species: 'Adelie', billLengthMm: 38.6, flipperLengthMm: 191 },
  { species: 'Adelie', billLengthMm: 34.6, flipperLengthMm: 198 },
  { species: 'Adelie', billLengthMm: 36.6, flipperLengthMm: 185 },
  { species: 'Adelie', billLengthMm: 38.7, flipperLengthMm: 195 },
  { species: 'Adelie', billLengthMm: 42.5, flipperLengthMm: 197 },
  { species: 'Adelie', billLengthMm: 34.4, flipperLengthMm: 184 },
  { species: 'Adelie', billLengthMm: 46, flipperLengthMm: 194 },
  { species: 'Adelie', billLengthMm: 37.8, flipperLengthMm: 174 },
  { species: 'Adelie', billLengthMm: 37.7, flipperLengthMm: 180 },
  { species: 'Adelie', billLengthMm: 35.9, flipperLengthMm: 189 },
  { species: 'Adelie', billLengthMm: 38.2, flipperLengthMm: 185 },
  { species: 'Adelie', billLengthMm: 38.8, flipperLengthMm: 180 },
  { species: 'Adelie', billLengthMm: 35.3, flipperLengthMm: 187 },
  { species: 'Adelie', billLengthMm: 40.6, flipperLengthMm: 183 },
  { species: 'Adelie', billLengthMm: 40.5, flipperLengthMm: 187 },
  { species: 'Adelie', billLengthMm: 37.9, flipperLengthMm: 172 },
  { species: 'Adelie', billLengthMm: 40.5, flipperLengthMm: 180 },
  { species: 'Adelie', billLengthMm: 39.5, flipperLengthMm: 178 },
  { species: 'Chinstrap', billLengthMm: 46.5, flipperLengthMm: 192 },
  { species: 'Chinstrap', billLengthMm: 50, flipperLengthMm: 196 },
  { species: 'Chinstrap', billLengthMm: 51.3, flipperLengthMm: 193 },
  { species: 'Chinstrap', billLengthMm: 45.4, flipperLengthMm: 188 },
  { species: 'Chinstrap', billLengthMm: 52.7, flipperLengthMm: 197 },
  { species: 'Chinstrap', billLengthMm: 45.2, flipperLengthMm: 198 },
  { species: 'Chinstrap', billLengthMm: 46.1, flipperLengthMm: 178 },
  { species: 'Chinstrap', billLengthMm: 51.3, flipperLengthMm: 197 },
  { species: 'Chinstrap', billLengthMm: 46, flipperLengthMm: 195 },
  { species: 'Chinstrap', billLengthMm: 51.3, flipperLengthMm: 198 },
  { species: 'Chinstrap', billLengthMm: 46.6, flipperLengthMm: 193 },
  { species: 'Chinstrap', billLengthMm: 51.7, flipperLengthMm: 194 },
  { species: 'Chinstrap', billLengthMm: 47, flipperLengthMm: 185 },
  { species: 'Chinstrap', billLengthMm: 52, flipperLengthMm: 201 },
  { species: 'Chinstrap', billLengthMm: 45.9, flipperLengthMm: 190 },
  { species: 'Chinstrap', billLengthMm: 50.5, flipperLengthMm: 201 },
  { species: 'Chinstrap', billLengthMm: 50.3, flipperLengthMm: 197 },
  { species: 'Chinstrap', billLengthMm: 58, flipperLengthMm: 181 },
  { species: 'Chinstrap', billLengthMm: 46.4, flipperLengthMm: 190 },
  { species: 'Chinstrap', billLengthMm: 49.2, flipperLengthMm: 195 },
  { species: 'Chinstrap', billLengthMm: 42.4, flipperLengthMm: 181 },
  { species: 'Chinstrap', billLengthMm: 48.5, flipperLengthMm: 191 },
  { species: 'Chinstrap', billLengthMm: 43.2, flipperLengthMm: 187 },
  { species: 'Chinstrap', billLengthMm: 50.6, flipperLengthMm: 193 },
  { species: 'Chinstrap', billLengthMm: 46.7, flipperLengthMm: 195 },
  { species: 'Chinstrap', billLengthMm: 52, flipperLengthMm: 197 },
  { species: 'Chinstrap', billLengthMm: 50.5, flipperLengthMm: 200 },
  { species: 'Chinstrap', billLengthMm: 49.5, flipperLengthMm: 200 },
  { species: 'Chinstrap', billLengthMm: 46.4, flipperLengthMm: 191 },
  { species: 'Chinstrap', billLengthMm: 52.8, flipperLengthMm: 205 },
  { species: 'Gentoo', billLengthMm: 46.1, flipperLengthMm: 211 },
  { species: 'Gentoo', billLengthMm: 50, flipperLengthMm: 230 },
  { species: 'Gentoo', billLengthMm: 48.7, flipperLengthMm: 210 },
  { species: 'Gentoo', billLengthMm: 50, flipperLengthMm: 218 },
  { species: 'Gentoo', billLengthMm: 47.6, flipperLengthMm: 215 },
  { species: 'Gentoo', billLengthMm: 46.5, flipperLengthMm: 210 },
  { species: 'Gentoo', billLengthMm: 45.4, flipperLengthMm: 211 },
  { species: 'Gentoo', billLengthMm: 46.7, flipperLengthMm: 219 },
  { species: 'Gentoo', billLengthMm: 43.3, flipperLengthMm: 209 },
  { species: 'Gentoo', billLengthMm: 46.8, flipperLengthMm: 215 },
  { species: 'Gentoo', billLengthMm: 40.9, flipperLengthMm: 214 },
  { species: 'Gentoo', billLengthMm: 49, flipperLengthMm: 216 },
  { species: 'Gentoo', billLengthMm: 45.5, flipperLengthMm: 214 },
  { species: 'Gentoo', billLengthMm: 48.4, flipperLengthMm: 213 },
  { species: 'Gentoo', billLengthMm: 45.8, flipperLengthMm: 210 },
  { species: 'Gentoo', billLengthMm: 49.3, flipperLengthMm: 217 },
  { species: 'Gentoo', billLengthMm: 42, flipperLengthMm: 210 },
  { species: 'Gentoo', billLengthMm: 49.2, flipperLengthMm: 221 },
  { species: 'Gentoo', billLengthMm: 46.2, flipperLengthMm: 209 },
  { species: 'Gentoo', billLengthMm: 48.7, flipperLengthMm: 222 },
  { species: 'Gentoo', billLengthMm: 50.2, flipperLengthMm: 218 },
  { species: 'Gentoo', billLengthMm: 45.1, flipperLengthMm: 215 },
  { species: 'Gentoo', billLengthMm: 46.5, flipperLengthMm: 213 },
  { species: 'Gentoo', billLengthMm: 46.3, flipperLengthMm: 215 },
  { species: 'Gentoo', billLengthMm: 42.9, flipperLengthMm: 215 },
  { species: 'Gentoo', billLengthMm: 46.1, flipperLengthMm: 215 },
  { species: 'Gentoo', billLengthMm: 44.5, flipperLengthMm: 216 },
  { species: 'Gentoo', billLengthMm: 47.8, flipperLengthMm: 215 },
  { species: 'Gentoo', billLengthMm: 48.2, flipperLengthMm: 210 },
  { species: 'Gentoo', billLengthMm: 50, flipperLengthMm: 220 },
];
