/** World Bank 国家截面的固定年份 */
export const WORLD_BANK_SCATTER_YEAR = 2023;

/** 基础 Scatter Showcase 使用的城市化与互联网普及指标 */
export type CountryScatterDatum = {
  /** ISO 3166-1 alpha-3 国家或地区代码 */
  code: string;
  /** 世界银行使用的国家或地区名称 */
  country: string;
  /** 城镇人口占总人口比例，单位为百分比 */
  urbanPopulationShare: number;
  /** 互联网使用人口比例，单位为百分比 */
  internetUseShare: number;
};

/**
 * 世界银行 2023 年国家截面
 *
 * @remarks 数据来自 World Bank Open Data 指标 `SP.URB.TOTL.IN.ZS`
 * （Urban population, % of total population）与 `IT.NET.USER.ZS`
 * （Individuals using the Internet, % of population），采用 CC BY 4.0 许可。
 * 通过世界银行 Country API 排除 `region.id === 'NA'` 的聚合地区后，
 * 按 ISO3 国家代码连接两个指标，省略缺失值，并将百分比四舍五入至一位小数
 */
export const countryScatterData: Array<CountryScatterDatum> = [
  { code: 'AFG', country: 'Afghanistan', urbanPopulationShare: 25.5, internetUseShare: 15.9 },
  { code: 'AGO', country: 'Angola', urbanPopulationShare: 69.9, internetUseShare: 37.9 },
  { code: 'ALB', country: 'Albania', urbanPopulationShare: 58.2, internetUseShare: 83.1 },
  { code: 'AND', country: 'Andorra', urbanPopulationShare: 88.8, internetUseShare: 94.2 },
  { code: 'ARE', country: 'United Arab Emirates', urbanPopulationShare: 85.7, internetUseShare: 100 },
  { code: 'ARG', country: 'Argentina', urbanPopulationShare: 92.2, internetUseShare: 89.2 },
  { code: 'ARM', country: 'Armenia', urbanPopulationShare: 65.7, internetUseShare: 80 },
  { code: 'ATG', country: 'Antigua and Barbuda', urbanPopulationShare: 24.5, internetUseShare: 72.1 },
  { code: 'AUS', country: 'Australia', urbanPopulationShare: 87.5, internetUseShare: 96.1 },
  { code: 'AUT', country: 'Austria', urbanPopulationShare: 69.2, internetUseShare: 95.3 },
  { code: 'AZE', country: 'Azerbaijan', urbanPopulationShare: 58.5, internetUseShare: 89 },
  { code: 'BDI', country: 'Burundi', urbanPopulationShare: 23.6, internetUseShare: 7.2 },
  { code: 'BEL', country: 'Belgium', urbanPopulationShare: 87.6, internetUseShare: 94.6 },
  { code: 'BEN', country: 'Benin', urbanPopulationShare: 51.7, internetUseShare: 32.4 },
  { code: 'BFA', country: 'Burkina Faso', urbanPopulationShare: 27.8, internetUseShare: 25.4 },
  { code: 'BGD', country: 'Bangladesh', urbanPopulationShare: 32.2, internetUseShare: 44.5 },
  { code: 'BGR', country: 'Bulgaria', urbanPopulationShare: 73.7, internetUseShare: 80.4 },
  { code: 'BHR', country: 'Bahrain', urbanPopulationShare: 100, internetUseShare: 100 },
  { code: 'BHS', country: 'Bahamas, The', urbanPopulationShare: 81.3, internetUseShare: 92.4 },
  { code: 'BIH', country: 'Bosnia and Herzegovina', urbanPopulationShare: 51.6, internetUseShare: 83.4 },
  { code: 'BLR', country: 'Belarus', urbanPopulationShare: 78.8, internetUseShare: 91.5 },
  { code: 'BLZ', country: 'Belize', urbanPopulationShare: 41.9, internetUseShare: 70.2 },
  { code: 'BOL', country: 'Bolivia', urbanPopulationShare: 70.9, internetUseShare: 77.3 },
  { code: 'BRA', country: 'Brazil', urbanPopulationShare: 87.6, internetUseShare: 84.2 },
  { code: 'BRB', country: 'Barbados', urbanPopulationShare: 59.4, internetUseShare: 69.7 },
  { code: 'BRN', country: 'Brunei Darussalam', urbanPopulationShare: 74.8, internetUseShare: 99 },
  { code: 'BTN', country: 'Bhutan', urbanPopulationShare: 41.7, internetUseShare: 90 },
  { code: 'CAF', country: 'Central African Republic', urbanPopulationShare: 43.7, internetUseShare: 13.8 },
  { code: 'CAN', country: 'Canada', urbanPopulationShare: 82.5, internetUseShare: 94.1 },
  { code: 'CHE', country: 'Switzerland', urbanPopulationShare: 85.2, internetUseShare: 97.3 },
  { code: 'CHL', country: 'Chile', urbanPopulationShare: 88.8, internetUseShare: 94.5 },
  { code: 'CHN', country: 'China', urbanPopulationShare: 65.5, internetUseShare: 90.6 },
  { code: 'CIV', country: 'Cote d\u0027Ivoire', urbanPopulationShare: 53.4, internetUseShare: 40.7 },
  { code: 'CMR', country: 'Cameroon', urbanPopulationShare: 55.1, internetUseShare: 42.2 },
  { code: 'COD', country: 'Congo, Dem. Rep.', urbanPopulationShare: 44.4, internetUseShare: 19 },
  { code: 'COG', country: 'Congo, Rep.', urbanPopulationShare: 63.7, internetUseShare: 43.2 },
  { code: 'COL', country: 'Colombia', urbanPopulationShare: 78.3, internetUseShare: 77.3 },
  { code: 'COM', country: 'Comoros', urbanPopulationShare: 33.2, internetUseShare: 31.9 },
  { code: 'CPV', country: 'Cabo Verde', urbanPopulationShare: 75.9, internetUseShare: 74.6 },
  { code: 'CRI', country: 'Costa Rica', urbanPopulationShare: 78.9, internetUseShare: 85.4 },
  { code: 'CUB', country: 'Cuba', urbanPopulationShare: 77.1, internetUseShare: 69.6 },
  { code: 'CYP', country: 'Cyprus', urbanPopulationShare: 66.7, internetUseShare: 91.2 },
  { code: 'CZE', country: 'Czechia', urbanPopulationShare: 72.7, internetUseShare: 86 },
  { code: 'DEU', country: 'Germany', urbanPopulationShare: 81.9, internetUseShare: 92.5 },
  { code: 'DJI', country: 'Djibouti', urbanPopulationShare: 72.8, internetUseShare: 64.8 },
  { code: 'DMA', country: 'Dominica', urbanPopulationShare: 73.1, internetUseShare: 81.3 },
  { code: 'DNK', country: 'Denmark', urbanPopulationShare: 88.6, internetUseShare: 98.8 },
  { code: 'DOM', country: 'Dominican Republic', urbanPopulationShare: 72.4, internetUseShare: 86.1 },
  { code: 'DZA', country: 'Algeria', urbanPopulationShare: 74.7, internetUseShare: 76.2 },
  { code: 'ECU', country: 'Ecuador', urbanPopulationShare: 63.1, internetUseShare: 72.7 },
  { code: 'EGY', country: 'Egypt, Arab Rep.', urbanPopulationShare: 42.7, internetUseShare: 74 },
  { code: 'ESP', country: 'Spain', urbanPopulationShare: 80.1, internetUseShare: 95.4 },
  { code: 'EST', country: 'Estonia', urbanPopulationShare: 70.7, internetUseShare: 93.2 },
  { code: 'ETH', country: 'Ethiopia', urbanPopulationShare: 23.1, internetUseShare: 20.3 },
  { code: 'FIN', country: 'Finland', urbanPopulationShare: 74, internetUseShare: 93.5 },
  { code: 'FJI', country: 'Fiji', urbanPopulationShare: 58.6, internetUseShare: 74.1 },
  { code: 'FRA', country: 'France', urbanPopulationShare: 78.8, internetUseShare: 86.8 },
  { code: 'FSM', country: 'Micronesia, Fed. Sts.', urbanPopulationShare: 22.4, internetUseShare: 39.4 },
  { code: 'GAB', country: 'Gabon', urbanPopulationShare: 91.6, internetUseShare: 68.2 },
  { code: 'GBR', country: 'United Kingdom', urbanPopulationShare: 83.2, internetUseShare: 95.4 },
  { code: 'GEO', country: 'Georgia', urbanPopulationShare: 60.8, internetUseShare: 81.9 },
  { code: 'GHA', country: 'Ghana', urbanPopulationShare: 57.8, internetUseShare: 70.7 },
  { code: 'GIN', country: 'Guinea', urbanPopulationShare: 37.6, internetUseShare: 32.3 },
  { code: 'GMB', country: 'Gambia, The', urbanPopulationShare: 63.8, internetUseShare: 48.7 },
  { code: 'GNB', country: 'Guinea-Bissau', urbanPopulationShare: 45.6, internetUseShare: 28.7 },
  { code: 'GNQ', country: 'Equatorial Guinea', urbanPopulationShare: 71.1, internetUseShare: 63.5 },
  { code: 'GRC', country: 'Greece', urbanPopulationShare: 78.8, internetUseShare: 85 },
  { code: 'GRD', country: 'Grenada', urbanPopulationShare: 36.5, internetUseShare: 69.4 },
  { code: 'GTM', country: 'Guatemala', urbanPopulationShare: 55.6, internetUseShare: 56.7 },
  { code: 'GUY', country: 'Guyana', urbanPopulationShare: 26.5, internetUseShare: 79.4 },
  { code: 'HKG', country: 'Hong Kong SAR, China', urbanPopulationShare: 100, internetUseShare: 96 },
  { code: 'HND', country: 'Honduras', urbanPopulationShare: 58.3, internetUseShare: 58.1 },
  { code: 'HRV', country: 'Croatia', urbanPopulationShare: 57.2, internetUseShare: 83.2 },
  { code: 'HTI', country: 'Haiti', urbanPopulationShare: 54.4, internetUseShare: 48 },
  { code: 'HUN', country: 'Hungary', urbanPopulationShare: 70.3, internetUseShare: 91.5 },
  { code: 'IDN', country: 'Indonesia', urbanPopulationShare: 58.1, internetUseShare: 69.2 },
  { code: 'IND', country: 'India', urbanPopulationShare: 35.1, internetUseShare: 60.3 },
  { code: 'IRL', country: 'Ireland', urbanPopulationShare: 64.1, internetUseShare: 96.9 },
  { code: 'IRN', country: 'Iran, Islamic Rep.', urbanPopulationShare: 76.7, internetUseShare: 83.7 },
  { code: 'IRQ', country: 'Iraq', urbanPopulationShare: 69.9, internetUseShare: 81.8 },
  { code: 'ISL', country: 'Iceland', urbanPopulationShare: 94.2, internetUseShare: 97.9 },
  { code: 'ISR', country: 'Israel', urbanPopulationShare: 91.5, internetUseShare: 87 },
  { code: 'ITA', country: 'Italy', urbanPopulationShare: 69.5, internetUseShare: 87 },
  { code: 'JAM', country: 'Jamaica', urbanPopulationShare: 58.5, internetUseShare: 89.5 },
  { code: 'JOR', country: 'Jordan', urbanPopulationShare: 92.7, internetUseShare: 92.5 },
  { code: 'JPN', country: 'Japan', urbanPopulationShare: 92.1, internetUseShare: 85 },
  { code: 'KAZ', country: 'Kazakhstan', urbanPopulationShare: 61.8, internetUseShare: 92.9 },
  { code: 'KEN', country: 'Kenya', urbanPopulationShare: 31.6, internetUseShare: 32.1 },
  { code: 'KGZ', country: 'Kyrgyz Republic', urbanPopulationShare: 34.7, internetUseShare: 91 },
  { code: 'KHM', country: 'Cambodia', urbanPopulationShare: 40.6, internetUseShare: 68.9 },
  { code: 'KIR', country: 'Kiribati', urbanPopulationShare: 61.5, internetUseShare: 88 },
  { code: 'KNA', country: 'St. Kitts and Nevis', urbanPopulationShare: 31.7, internetUseShare: 76.6 },
  { code: 'KOR', country: 'Korea, Rep.', urbanPopulationShare: 81.2, internetUseShare: 97.4 },
  { code: 'KWT', country: 'Kuwait', urbanPopulationShare: 100, internetUseShare: 99.7 },
  { code: 'LAO', country: 'Lao PDR', urbanPopulationShare: 38.8, internetUseShare: 64.4 },
  { code: 'LBN', country: 'Lebanon', urbanPopulationShare: 90.5, internetUseShare: 81.7 },
  { code: 'LBR', country: 'Liberia', urbanPopulationShare: 55, internetUseShare: 31.2 },
  { code: 'LBY', country: 'Libya', urbanPopulationShare: 87.9, internetUseShare: 82.1 },
  { code: 'LCA', country: 'St. Lucia', urbanPopulationShare: 29.1, internetUseShare: 67.4 },
  { code: 'LIE', country: 'Liechtenstein', urbanPopulationShare: 14.7, internetUseShare: 98.1 },
  { code: 'LKA', country: 'Sri Lanka', urbanPopulationShare: 20.1, internetUseShare: 51.2 },
  { code: 'LSO', country: 'Lesotho', urbanPopulationShare: 42.7, internetUseShare: 49 },
  { code: 'LTU', country: 'Lithuania', urbanPopulationShare: 68.6, internetUseShare: 88.5 },
  { code: 'LUX', country: 'Luxembourg', urbanPopulationShare: 94.8, internetUseShare: 99.3 },
  { code: 'LVA', country: 'Latvia', urbanPopulationShare: 68.4, internetUseShare: 92.2 },
  { code: 'MAC', country: 'Macao SAR, China', urbanPopulationShare: 100, internetUseShare: 89.8 },
  { code: 'MAR', country: 'Morocco', urbanPopulationShare: 62.7, internetUseShare: 91 },
  { code: 'MCO', country: 'Monaco', urbanPopulationShare: 100, internetUseShare: 98.9 },
  { code: 'MDA', country: 'Moldova', urbanPopulationShare: 43, internetUseShare: 76.5 },
  { code: 'MDG', country: 'Madagascar', urbanPopulationShare: 32, internetUseShare: 18.2 },
  { code: 'MDV', country: 'Maldives', urbanPopulationShare: 41.5, internetUseShare: 84.6 },
  { code: 'MEX', country: 'Mexico', urbanPopulationShare: 79.5, internetUseShare: 81.2 },
  { code: 'MHL', country: 'Marshall Islands', urbanPopulationShare: 78.4, internetUseShare: 64.1 },
  { code: 'MKD', country: 'North Macedonia', urbanPopulationShare: 62.3, internetUseShare: 88.5 },
  { code: 'MLI', country: 'Mali', urbanPopulationShare: 31, internetUseShare: 36 },
  { code: 'MLT', country: 'Malta', urbanPopulationShare: 95.6, internetUseShare: 92.1 },
  { code: 'MNE', country: 'Montenegro', urbanPopulationShare: 65.5, internetUseShare: 88.6 },
  { code: 'MNG', country: 'Mongolia', urbanPopulationShare: 70.4, internetUseShare: 83.7 },
  { code: 'MOZ', country: 'Mozambique', urbanPopulationShare: 35.7, internetUseShare: 19.9 },
  { code: 'MRT', country: 'Mauritania', urbanPopulationShare: 59.7, internetUseShare: 45 },
  { code: 'MUS', country: 'Mauritius', urbanPopulationShare: 39, internetUseShare: 79.5 },
  { code: 'MWI', country: 'Malawi', urbanPopulationShare: 17, internetUseShare: 18 },
  { code: 'MYS', country: 'Malaysia', urbanPopulationShare: 76.4, internetUseShare: 97.7 },
  { code: 'NAM', country: 'Namibia', urbanPopulationShare: 50, internetUseShare: 63.7 },
  { code: 'NER', country: 'Niger', urbanPopulationShare: 17.8, internetUseShare: 13 },
  { code: 'NGA', country: 'Nigeria', urbanPopulationShare: 62.2, internetUseShare: 40.1 },
  { code: 'NIC', country: 'Nicaragua', urbanPopulationShare: 59.1, internetUseShare: 60.3 },
  { code: 'NLD', country: 'Netherlands', urbanPopulationShare: 95.3, internetUseShare: 97 },
  { code: 'NOR', country: 'Norway', urbanPopulationShare: 83.1, internetUseShare: 99 },
  { code: 'NPL', country: 'Nepal', urbanPopulationShare: 66.5, internetUseShare: 45.8 },
  { code: 'NRU', country: 'Naoero', urbanPopulationShare: 100, internetUseShare: 83 },
  { code: 'NZL', country: 'New Zealand', urbanPopulationShare: 83.9, internetUseShare: 93.3 },
  { code: 'OMN', country: 'Oman', urbanPopulationShare: 79.6, internetUseShare: 95.3 },
  { code: 'PAN', country: 'Panama', urbanPopulationShare: 65.9, internetUseShare: 68.5 },
  { code: 'PER', country: 'Peru', urbanPopulationShare: 84.8, internetUseShare: 79.5 },
  { code: 'PHL', country: 'Philippines', urbanPopulationShare: 55.1, internetUseShare: 77.9 },
  { code: 'PLW', country: 'Palau', urbanPopulationShare: 79.2, internetUseShare: 82.9 },
  { code: 'PNG', country: 'Papua New Guinea', urbanPopulationShare: 15.1, internetUseShare: 18.6 },
  { code: 'POL', country: 'Poland', urbanPopulationShare: 59.9, internetUseShare: 86.4 },
  { code: 'PRT', country: 'Portugal', urbanPopulationShare: 61.2, internetUseShare: 85.8 },
  { code: 'PRY', country: 'Paraguay', urbanPopulationShare: 69.3, internetUseShare: 78.1 },
  { code: 'PSE', country: 'West Bank and Gaza', urbanPopulationShare: 86.9, internetUseShare: 86.6 },
  { code: 'QAT', country: 'Qatar', urbanPopulationShare: 99.3, internetUseShare: 98.2 },
  { code: 'ROU', country: 'Romania', urbanPopulationShare: 52.2, internetUseShare: 89.2 },
  { code: 'RUS', country: 'Russian Federation', urbanPopulationShare: 75, internetUseShare: 92.2 },
  { code: 'RWA', country: 'Rwanda', urbanPopulationShare: 28.9, internetUseShare: 28.8 },
  { code: 'SAU', country: 'Saudi Arabia', urbanPopulationShare: 84.3, internetUseShare: 100 },
  { code: 'SEN', country: 'Senegal', urbanPopulationShare: 54.7, internetUseShare: 59.2 },
  { code: 'SGP', country: 'Singapore', urbanPopulationShare: 100, internetUseShare: 94.3 },
  { code: 'SLB', country: 'Solomon Islands', urbanPopulationShare: 30, internetUseShare: 28.7 },
  { code: 'SLE', country: 'Sierra Leone', urbanPopulationShare: 44.8, internetUseShare: 23.7 },
  { code: 'SLV', country: 'El Salvador', urbanPopulationShare: 74.6, internetUseShare: 62.6 },
  { code: 'SMR', country: 'San Marino', urbanPopulationShare: 97.1, internetUseShare: 97.3 },
  { code: 'SOM', country: 'Somalia, Fed. Rep.', urbanPopulationShare: 54.1, internetUseShare: 26.1 },
  { code: 'SRB', country: 'Serbia', urbanPopulationShare: 62.1, internetUseShare: 85.4 },
  { code: 'STP', country: 'Sao Tome and Principe', urbanPopulationShare: 68.6, internetUseShare: 58.7 },
  { code: 'SUR', country: 'Suriname', urbanPopulationShare: 65.8, internetUseShare: 87.4 },
  { code: 'SVK', country: 'Slovak Republic', urbanPopulationShare: 53.2, internetUseShare: 87.2 },
  { code: 'SVN', country: 'Slovenia', urbanPopulationShare: 55.5, internetUseShare: 90.4 },
  { code: 'SWE', country: 'Sweden', urbanPopulationShare: 88.6, internetUseShare: 95.7 },
  { code: 'SWZ', country: 'Eswatini', urbanPopulationShare: 25.8, internetUseShare: 61.3 },
  { code: 'SYC', country: 'Seychelles', urbanPopulationShare: 45.1, internetUseShare: 86 },
  { code: 'TCD', country: 'Chad', urbanPopulationShare: 26.3, internetUseShare: 12 },
  { code: 'TGO', country: 'Togo', urbanPopulationShare: 43.2, internetUseShare: 37.6 },
  { code: 'THA', country: 'Thailand', urbanPopulationShare: 60.9, internetUseShare: 89.5 },
  { code: 'TJK', country: 'Tajikistan', urbanPopulationShare: 26.2, internetUseShare: 54.4 },
  { code: 'TON', country: 'Tonga', urbanPopulationShare: 21.1, internetUseShare: 64.1 },
  { code: 'TTO', country: 'Trinidad and Tobago', urbanPopulationShare: 54, internetUseShare: 82 },
  { code: 'TUR', country: 'Turkiye', urbanPopulationShare: 89, internetUseShare: 86 },
  { code: 'TZA', country: 'Tanzania', urbanPopulationShare: 35.5, internetUseShare: 28.4 },
  { code: 'UGA', country: 'Uganda', urbanPopulationShare: 30.6, internetUseShare: 9.3 },
  { code: 'UKR', country: 'Ukraine', urbanPopulationShare: 69.5, internetUseShare: 81.6 },
  { code: 'URY', country: 'Uruguay', urbanPopulationShare: 95.5, internetUseShare: 90.9 },
  { code: 'USA', country: 'United States', urbanPopulationShare: 80.1, internetUseShare: 93.5 },
  { code: 'UZB', country: 'Uzbekistan', urbanPopulationShare: 51, internetUseShare: 89 },
  { code: 'VCT', country: 'St. Vincent and the Grenadines', urbanPopulationShare: 47.7, internetUseShare: 75.5 },
  { code: 'VEN', country: 'Venezuela, RB', urbanPopulationShare: 89.2, internetUseShare: 76.3 },
  { code: 'VNM', country: 'Viet Nam', urbanPopulationShare: 38.1, internetUseShare: 78.1 },
  { code: 'ZAF', country: 'South Africa', urbanPopulationShare: 63.6, internetUseShare: 78.3 },
  { code: 'ZMB', country: 'Zambia', urbanPopulationShare: 45, internetUseShare: 16.5 },
  { code: 'ZWE', country: 'Zimbabwe', urbanPopulationShare: 39.3, internetUseShare: 38.7 },
];
