/** Gapminder 国家截面的固定年份 */
export const GAPMINDER_SCATTER_YEAR = 2007;

/** Gapminder 国家散点图中的大洲分类 */
export type CountryScatterContinent = 'Africa' | 'Americas' | 'Asia' | 'Europe' | 'Oceania';

/** 收入与寿命 Scatter Showcase 使用的国家发展指标 */
export type CountryScatterDatum = {
  /** 国家或地区名称 */
  country: string;
  /** 所属大洲 */
  continent: CountryScatterContinent;
  /** 经通胀调整的人均 GDP，单位为美元 */
  gdpPerCapita: number;
  /** 出生时预期寿命，单位为年 */
  lifeExpectancy: number;
};

/**
 * Gapminder 2007 年完整国家截面
 *
 * @remarks 来源为 jennybc/gapminder 固定 commit `391b5a40d3574c3b89d889dd7d72f7f3fdb4a70c`
 * 的 `data-raw/08_gap-every-five-years.tsv`，采用 CC0 许可。筛选 `year === 2007` 后，
 * 人均 GDP 四舍五入至整数美元，预期寿命四舍五入至一位小数
 */
export const countryScatterData: Array<CountryScatterDatum> = [
  { country: 'Afghanistan', continent: 'Asia', gdpPerCapita: 975, lifeExpectancy: 43.8 },
  { country: 'Albania', continent: 'Europe', gdpPerCapita: 5937, lifeExpectancy: 76.4 },
  { country: 'Algeria', continent: 'Africa', gdpPerCapita: 6223, lifeExpectancy: 72.3 },
  { country: 'Angola', continent: 'Africa', gdpPerCapita: 4797, lifeExpectancy: 42.7 },
  { country: 'Argentina', continent: 'Americas', gdpPerCapita: 12779, lifeExpectancy: 75.3 },
  { country: 'Australia', continent: 'Oceania', gdpPerCapita: 34435, lifeExpectancy: 81.2 },
  { country: 'Austria', continent: 'Europe', gdpPerCapita: 36126, lifeExpectancy: 79.8 },
  { country: 'Bahrain', continent: 'Asia', gdpPerCapita: 29796, lifeExpectancy: 75.6 },
  { country: 'Bangladesh', continent: 'Asia', gdpPerCapita: 1391, lifeExpectancy: 64.1 },
  { country: 'Belgium', continent: 'Europe', gdpPerCapita: 33693, lifeExpectancy: 79.4 },
  { country: 'Benin', continent: 'Africa', gdpPerCapita: 1441, lifeExpectancy: 56.7 },
  { country: 'Bolivia', continent: 'Americas', gdpPerCapita: 3822, lifeExpectancy: 65.6 },
  { country: 'Bosnia and Herzegovina', continent: 'Europe', gdpPerCapita: 7446, lifeExpectancy: 74.9 },
  { country: 'Botswana', continent: 'Africa', gdpPerCapita: 12570, lifeExpectancy: 50.7 },
  { country: 'Brazil', continent: 'Americas', gdpPerCapita: 9066, lifeExpectancy: 72.4 },
  { country: 'Bulgaria', continent: 'Europe', gdpPerCapita: 10681, lifeExpectancy: 73.0 },
  { country: 'Burkina Faso', continent: 'Africa', gdpPerCapita: 1217, lifeExpectancy: 52.3 },
  { country: 'Burundi', continent: 'Africa', gdpPerCapita: 430, lifeExpectancy: 49.6 },
  { country: 'Cambodia', continent: 'Asia', gdpPerCapita: 1714, lifeExpectancy: 59.7 },
  { country: 'Cameroon', continent: 'Africa', gdpPerCapita: 2042, lifeExpectancy: 50.4 },
  { country: 'Canada', continent: 'Americas', gdpPerCapita: 36319, lifeExpectancy: 80.7 },
  { country: 'Central African Republic', continent: 'Africa', gdpPerCapita: 706, lifeExpectancy: 44.7 },
  { country: 'Chad', continent: 'Africa', gdpPerCapita: 1704, lifeExpectancy: 50.7 },
  { country: 'Chile', continent: 'Americas', gdpPerCapita: 13172, lifeExpectancy: 78.6 },
  { country: 'China', continent: 'Asia', gdpPerCapita: 4959, lifeExpectancy: 73.0 },
  { country: 'Colombia', continent: 'Americas', gdpPerCapita: 7007, lifeExpectancy: 72.9 },
  { country: 'Comoros', continent: 'Africa', gdpPerCapita: 986, lifeExpectancy: 65.2 },
  { country: 'Congo, Dem. Rep.', continent: 'Africa', gdpPerCapita: 278, lifeExpectancy: 46.5 },
  { country: 'Congo, Rep.', continent: 'Africa', gdpPerCapita: 3633, lifeExpectancy: 55.3 },
  { country: 'Costa Rica', continent: 'Americas', gdpPerCapita: 9645, lifeExpectancy: 78.8 },
  { country: "Cote d'Ivoire", continent: 'Africa', gdpPerCapita: 1545, lifeExpectancy: 48.3 },
  { country: 'Croatia', continent: 'Europe', gdpPerCapita: 14619, lifeExpectancy: 75.7 },
  { country: 'Cuba', continent: 'Americas', gdpPerCapita: 8948, lifeExpectancy: 78.3 },
  { country: 'Czech Republic', continent: 'Europe', gdpPerCapita: 22833, lifeExpectancy: 76.5 },
  { country: 'Denmark', continent: 'Europe', gdpPerCapita: 35278, lifeExpectancy: 78.3 },
  { country: 'Djibouti', continent: 'Africa', gdpPerCapita: 2082, lifeExpectancy: 54.8 },
  { country: 'Dominican Republic', continent: 'Americas', gdpPerCapita: 6025, lifeExpectancy: 72.2 },
  { country: 'Ecuador', continent: 'Americas', gdpPerCapita: 6873, lifeExpectancy: 75.0 },
  { country: 'Egypt', continent: 'Africa', gdpPerCapita: 5581, lifeExpectancy: 71.3 },
  { country: 'El Salvador', continent: 'Americas', gdpPerCapita: 5728, lifeExpectancy: 71.9 },
  { country: 'Equatorial Guinea', continent: 'Africa', gdpPerCapita: 12154, lifeExpectancy: 51.6 },
  { country: 'Eritrea', continent: 'Africa', gdpPerCapita: 641, lifeExpectancy: 58.0 },
  { country: 'Ethiopia', continent: 'Africa', gdpPerCapita: 691, lifeExpectancy: 52.9 },
  { country: 'Finland', continent: 'Europe', gdpPerCapita: 33207, lifeExpectancy: 79.3 },
  { country: 'France', continent: 'Europe', gdpPerCapita: 30470, lifeExpectancy: 80.7 },
  { country: 'Gabon', continent: 'Africa', gdpPerCapita: 13206, lifeExpectancy: 56.7 },
  { country: 'Gambia', continent: 'Africa', gdpPerCapita: 753, lifeExpectancy: 59.4 },
  { country: 'Germany', continent: 'Europe', gdpPerCapita: 32170, lifeExpectancy: 79.4 },
  { country: 'Ghana', continent: 'Africa', gdpPerCapita: 1328, lifeExpectancy: 60.0 },
  { country: 'Greece', continent: 'Europe', gdpPerCapita: 27538, lifeExpectancy: 79.5 },
  { country: 'Guatemala', continent: 'Americas', gdpPerCapita: 5186, lifeExpectancy: 70.3 },
  { country: 'Guinea', continent: 'Africa', gdpPerCapita: 943, lifeExpectancy: 56.0 },
  { country: 'Guinea-Bissau', continent: 'Africa', gdpPerCapita: 579, lifeExpectancy: 46.4 },
  { country: 'Haiti', continent: 'Americas', gdpPerCapita: 1202, lifeExpectancy: 60.9 },
  { country: 'Honduras', continent: 'Americas', gdpPerCapita: 3548, lifeExpectancy: 70.2 },
  { country: 'Hong Kong, China', continent: 'Asia', gdpPerCapita: 39725, lifeExpectancy: 82.2 },
  { country: 'Hungary', continent: 'Europe', gdpPerCapita: 18009, lifeExpectancy: 73.3 },
  { country: 'Iceland', continent: 'Europe', gdpPerCapita: 36181, lifeExpectancy: 81.8 },
  { country: 'India', continent: 'Asia', gdpPerCapita: 2452, lifeExpectancy: 64.7 },
  { country: 'Indonesia', continent: 'Asia', gdpPerCapita: 3541, lifeExpectancy: 70.6 },
  { country: 'Iran', continent: 'Asia', gdpPerCapita: 11606, lifeExpectancy: 71.0 },
  { country: 'Iraq', continent: 'Asia', gdpPerCapita: 4471, lifeExpectancy: 59.5 },
  { country: 'Ireland', continent: 'Europe', gdpPerCapita: 40676, lifeExpectancy: 78.9 },
  { country: 'Israel', continent: 'Asia', gdpPerCapita: 25523, lifeExpectancy: 80.7 },
  { country: 'Italy', continent: 'Europe', gdpPerCapita: 28570, lifeExpectancy: 80.5 },
  { country: 'Jamaica', continent: 'Americas', gdpPerCapita: 7321, lifeExpectancy: 72.6 },
  { country: 'Japan', continent: 'Asia', gdpPerCapita: 31656, lifeExpectancy: 82.6 },
  { country: 'Jordan', continent: 'Asia', gdpPerCapita: 4519, lifeExpectancy: 72.5 },
  { country: 'Kenya', continent: 'Africa', gdpPerCapita: 1463, lifeExpectancy: 54.1 },
  { country: 'Korea, Dem. Rep.', continent: 'Asia', gdpPerCapita: 1593, lifeExpectancy: 67.3 },
  { country: 'Korea, Rep.', continent: 'Asia', gdpPerCapita: 23348, lifeExpectancy: 78.6 },
  { country: 'Kuwait', continent: 'Asia', gdpPerCapita: 47307, lifeExpectancy: 77.6 },
  { country: 'Lebanon', continent: 'Asia', gdpPerCapita: 10461, lifeExpectancy: 72.0 },
  { country: 'Lesotho', continent: 'Africa', gdpPerCapita: 1569, lifeExpectancy: 42.6 },
  { country: 'Liberia', continent: 'Africa', gdpPerCapita: 415, lifeExpectancy: 45.7 },
  { country: 'Libya', continent: 'Africa', gdpPerCapita: 12057, lifeExpectancy: 74.0 },
  { country: 'Madagascar', continent: 'Africa', gdpPerCapita: 1045, lifeExpectancy: 59.4 },
  { country: 'Malawi', continent: 'Africa', gdpPerCapita: 759, lifeExpectancy: 48.3 },
  { country: 'Malaysia', continent: 'Asia', gdpPerCapita: 12452, lifeExpectancy: 74.2 },
  { country: 'Mali', continent: 'Africa', gdpPerCapita: 1043, lifeExpectancy: 54.5 },
  { country: 'Mauritania', continent: 'Africa', gdpPerCapita: 1803, lifeExpectancy: 64.2 },
  { country: 'Mauritius', continent: 'Africa', gdpPerCapita: 10957, lifeExpectancy: 72.8 },
  { country: 'Mexico', continent: 'Americas', gdpPerCapita: 11978, lifeExpectancy: 76.2 },
  { country: 'Mongolia', continent: 'Asia', gdpPerCapita: 3096, lifeExpectancy: 66.8 },
  { country: 'Montenegro', continent: 'Europe', gdpPerCapita: 9254, lifeExpectancy: 74.5 },
  { country: 'Morocco', continent: 'Africa', gdpPerCapita: 3820, lifeExpectancy: 71.2 },
  { country: 'Mozambique', continent: 'Africa', gdpPerCapita: 824, lifeExpectancy: 42.1 },
  { country: 'Myanmar', continent: 'Asia', gdpPerCapita: 944, lifeExpectancy: 62.1 },
  { country: 'Namibia', continent: 'Africa', gdpPerCapita: 4811, lifeExpectancy: 52.9 },
  { country: 'Nepal', continent: 'Asia', gdpPerCapita: 1091, lifeExpectancy: 63.8 },
  { country: 'Netherlands', continent: 'Europe', gdpPerCapita: 36798, lifeExpectancy: 79.8 },
  { country: 'New Zealand', continent: 'Oceania', gdpPerCapita: 25185, lifeExpectancy: 80.2 },
  { country: 'Nicaragua', continent: 'Americas', gdpPerCapita: 2749, lifeExpectancy: 72.9 },
  { country: 'Niger', continent: 'Africa', gdpPerCapita: 620, lifeExpectancy: 56.9 },
  { country: 'Nigeria', continent: 'Africa', gdpPerCapita: 2014, lifeExpectancy: 46.9 },
  { country: 'Norway', continent: 'Europe', gdpPerCapita: 49357, lifeExpectancy: 80.2 },
  { country: 'Oman', continent: 'Asia', gdpPerCapita: 22316, lifeExpectancy: 75.6 },
  { country: 'Pakistan', continent: 'Asia', gdpPerCapita: 2606, lifeExpectancy: 65.5 },
  { country: 'Panama', continent: 'Americas', gdpPerCapita: 9809, lifeExpectancy: 75.5 },
  { country: 'Paraguay', continent: 'Americas', gdpPerCapita: 4173, lifeExpectancy: 71.8 },
  { country: 'Peru', continent: 'Americas', gdpPerCapita: 7409, lifeExpectancy: 71.4 },
  { country: 'Philippines', continent: 'Asia', gdpPerCapita: 3190, lifeExpectancy: 71.7 },
  { country: 'Poland', continent: 'Europe', gdpPerCapita: 15390, lifeExpectancy: 75.6 },
  { country: 'Portugal', continent: 'Europe', gdpPerCapita: 20510, lifeExpectancy: 78.1 },
  { country: 'Puerto Rico', continent: 'Americas', gdpPerCapita: 19329, lifeExpectancy: 78.7 },
  { country: 'Reunion', continent: 'Africa', gdpPerCapita: 7670, lifeExpectancy: 76.4 },
  { country: 'Romania', continent: 'Europe', gdpPerCapita: 10808, lifeExpectancy: 72.5 },
  { country: 'Rwanda', continent: 'Africa', gdpPerCapita: 863, lifeExpectancy: 46.2 },
  { country: 'Sao Tome and Principe', continent: 'Africa', gdpPerCapita: 1598, lifeExpectancy: 65.5 },
  { country: 'Saudi Arabia', continent: 'Asia', gdpPerCapita: 21655, lifeExpectancy: 72.8 },
  { country: 'Senegal', continent: 'Africa', gdpPerCapita: 1712, lifeExpectancy: 63.1 },
  { country: 'Serbia', continent: 'Europe', gdpPerCapita: 9787, lifeExpectancy: 74.0 },
  { country: 'Sierra Leone', continent: 'Africa', gdpPerCapita: 863, lifeExpectancy: 42.6 },
  { country: 'Singapore', continent: 'Asia', gdpPerCapita: 47143, lifeExpectancy: 80.0 },
  { country: 'Slovak Republic', continent: 'Europe', gdpPerCapita: 18678, lifeExpectancy: 74.7 },
  { country: 'Slovenia', continent: 'Europe', gdpPerCapita: 25768, lifeExpectancy: 77.9 },
  { country: 'Somalia', continent: 'Africa', gdpPerCapita: 926, lifeExpectancy: 48.2 },
  { country: 'South Africa', continent: 'Africa', gdpPerCapita: 9270, lifeExpectancy: 49.3 },
  { country: 'Spain', continent: 'Europe', gdpPerCapita: 28821, lifeExpectancy: 80.9 },
  { country: 'Sri Lanka', continent: 'Asia', gdpPerCapita: 3970, lifeExpectancy: 72.4 },
  { country: 'Sudan', continent: 'Africa', gdpPerCapita: 2602, lifeExpectancy: 58.6 },
  { country: 'Swaziland', continent: 'Africa', gdpPerCapita: 4513, lifeExpectancy: 39.6 },
  { country: 'Sweden', continent: 'Europe', gdpPerCapita: 33860, lifeExpectancy: 80.9 },
  { country: 'Switzerland', continent: 'Europe', gdpPerCapita: 37506, lifeExpectancy: 81.7 },
  { country: 'Syria', continent: 'Asia', gdpPerCapita: 4185, lifeExpectancy: 74.1 },
  { country: 'Taiwan', continent: 'Asia', gdpPerCapita: 28718, lifeExpectancy: 78.4 },
  { country: 'Tanzania', continent: 'Africa', gdpPerCapita: 1107, lifeExpectancy: 52.5 },
  { country: 'Thailand', continent: 'Asia', gdpPerCapita: 7458, lifeExpectancy: 70.6 },
  { country: 'Togo', continent: 'Africa', gdpPerCapita: 883, lifeExpectancy: 58.4 },
  { country: 'Trinidad and Tobago', continent: 'Americas', gdpPerCapita: 18009, lifeExpectancy: 69.8 },
  { country: 'Tunisia', continent: 'Africa', gdpPerCapita: 7093, lifeExpectancy: 73.9 },
  { country: 'Turkey', continent: 'Europe', gdpPerCapita: 8458, lifeExpectancy: 71.8 },
  { country: 'Uganda', continent: 'Africa', gdpPerCapita: 1056, lifeExpectancy: 51.5 },
  { country: 'United Kingdom', continent: 'Europe', gdpPerCapita: 33203, lifeExpectancy: 79.4 },
  { country: 'United States', continent: 'Americas', gdpPerCapita: 42952, lifeExpectancy: 78.2 },
  { country: 'Uruguay', continent: 'Americas', gdpPerCapita: 10611, lifeExpectancy: 76.4 },
  { country: 'Venezuela', continent: 'Americas', gdpPerCapita: 11416, lifeExpectancy: 73.7 },
  { country: 'Vietnam', continent: 'Asia', gdpPerCapita: 2442, lifeExpectancy: 74.2 },
  { country: 'West Bank and Gaza', continent: 'Asia', gdpPerCapita: 3025, lifeExpectancy: 73.4 },
  { country: 'Yemen, Rep.', continent: 'Asia', gdpPerCapita: 2281, lifeExpectancy: 62.7 },
  { country: 'Zambia', continent: 'Africa', gdpPerCapita: 1271, lifeExpectancy: 42.4 },
  { country: 'Zimbabwe', continent: 'Africa', gdpPerCapita: 470, lifeExpectancy: 43.5 },
];
