/** World Bank 散点数据的固定年份 */
export const WORLD_BANK_FERTILITY_WORK_YEAR = 2022;

/** World Bank 收入组代码 */
export type WorldBankIncomeGroup = 'HIC' | 'UMC' | 'LMC' | 'LIC';

/** 生育率与女性劳动参与率散点图的一条经济体记录 */
export type FertilityWorkDatum = {
  /** World Bank 经济体名称 */
  country: string;
  /** World Bank 收入组 */
  incomeGroup: WorldBankIncomeGroup;
  /** 总和生育率，单位为每名女性的生育数 */
  fertilityRate: number;
  /** 15 岁及以上女性劳动参与率，单位为百分比 */
  femaleLaborParticipation: number;
};

/**
 * World Bank 2022 年 186 个经济体的生育率与女性劳动参与率快照
 *
 * @remarks 指标来自 World Bank API：SP.DYN.TFRT.IN 与 SL.TLF.CACT.FE.ZS；收入组来自 country metadata。
 * 排除 aggregates、未分类收入组及任一指标缺失的经济体。数据检索于 2026-08-11，
 * 生育率保留两位小数，劳动参与率保留一位小数
 */
export const fertilityWorkData: Array<FertilityWorkDatum> = [
  { country: 'Afghanistan', incomeGroup: 'LIC', fertilityRate: 4.93, femaleLaborParticipation: 5.2 },
  { country: 'Albania', incomeGroup: 'UMC', fertilityRate: 1.36, femaleLaborParticipation: 56.4 },
  { country: 'Algeria', incomeGroup: 'UMC', fertilityRate: 2.82, femaleLaborParticipation: 14.3 },
  { country: 'Angola', incomeGroup: 'LMC', fertilityRate: 5.21, femaleLaborParticipation: 74 },
  { country: 'Argentina', incomeGroup: 'UMC', fertilityRate: 1.48, femaleLaborParticipation: 51.9 },
  { country: 'Armenia', incomeGroup: 'UMC', fertilityRate: 1.7, femaleLaborParticipation: 50.2 },
  { country: 'Australia', incomeGroup: 'HIC', fertilityRate: 1.63, femaleLaborParticipation: 62.5 },
  { country: 'Austria', incomeGroup: 'HIC', fertilityRate: 1.41, femaleLaborParticipation: 55.7 },
  { country: 'Azerbaijan', incomeGroup: 'UMC', fertilityRate: 1.67, femaleLaborParticipation: 62.2 },
  { country: 'Bahamas, The', incomeGroup: 'HIC', fertilityRate: 1.38, femaleLaborParticipation: 70.9 },
  { country: 'Bahrain', incomeGroup: 'HIC', fertilityRate: 1.84, femaleLaborParticipation: 42.2 },
  { country: 'Bangladesh', incomeGroup: 'LMC', fertilityRate: 2.18, femaleLaborParticipation: 43.7 },
  { country: 'Barbados', incomeGroup: 'HIC', fertilityRate: 1.71, femaleLaborParticipation: 61.1 },
  { country: 'Belarus', incomeGroup: 'UMC', fertilityRate: 1.33, femaleLaborParticipation: 57.9 },
  { country: 'Belgium', incomeGroup: 'HIC', fertilityRate: 1.53, femaleLaborParticipation: 50 },
  { country: 'Belize', incomeGroup: 'UMC', fertilityRate: 1.95, femaleLaborParticipation: 43.6 },
  { country: 'Benin', incomeGroup: 'LMC', fertilityRate: 4.63, femaleLaborParticipation: 74.6 },
  { country: 'Bhutan', incomeGroup: 'LMC', fertilityRate: 1.48, femaleLaborParticipation: 52.5 },
  { country: 'Bolivia', incomeGroup: 'LMC', fertilityRate: 2.58, femaleLaborParticipation: 71.7 },
  { country: 'Bosnia and Herzegovina', incomeGroup: 'UMC', fertilityRate: 1.48, femaleLaborParticipation: 38.5 },
  { country: 'Botswana', incomeGroup: 'UMC', fertilityRate: 2.78, femaleLaborParticipation: 59.9 },
  { country: 'Brazil', incomeGroup: 'UMC', fertilityRate: 1.63, femaleLaborParticipation: 53.9 },
  { country: 'Brunei Darussalam', incomeGroup: 'HIC', fertilityRate: 1.76, femaleLaborParticipation: 53.7 },
  { country: 'Bulgaria', incomeGroup: 'HIC', fertilityRate: 1.78, femaleLaborParticipation: 50.8 },
  { country: 'Burkina Faso', incomeGroup: 'LIC', fertilityRate: 4.28, femaleLaborParticipation: 65.4 },
  { country: 'Burundi', incomeGroup: 'LIC', fertilityRate: 4.98, femaleLaborParticipation: 80.2 },
  { country: 'Cabo Verde', incomeGroup: 'UMC', fertilityRate: 1.53, femaleLaborParticipation: 49.9 },
  { country: 'Cambodia', incomeGroup: 'LMC', fertilityRate: 2.62, femaleLaborParticipation: 77.2 },
  { country: 'Cameroon', incomeGroup: 'LMC', fertilityRate: 4.4, femaleLaborParticipation: 57.1 },
  { country: 'Canada', incomeGroup: 'HIC', fertilityRate: 1.34, femaleLaborParticipation: 61 },
  { country: 'Central African Republic', incomeGroup: 'LIC', fertilityRate: 6.02, femaleLaborParticipation: 65.5 },
  { country: 'Chad', incomeGroup: 'LIC', fertilityRate: 6.22, femaleLaborParticipation: 47.9 },
  { country: 'Channel Islands', incomeGroup: 'HIC', fertilityRate: 1.37, femaleLaborParticipation: 50.9 },
  { country: 'Chile', incomeGroup: 'HIC', fertilityRate: 1.25, femaleLaborParticipation: 50 },
  { country: 'China', incomeGroup: 'UMC', fertilityRate: 1.03, femaleLaborParticipation: 60.1 },
  { country: 'Colombia', incomeGroup: 'UMC', fertilityRate: 1.66, femaleLaborParticipation: 50.9 },
  { country: 'Comoros', incomeGroup: 'LMC', fertilityRate: 3.94, femaleLaborParticipation: 47 },
  { country: 'Congo, Dem. Rep.', incomeGroup: 'LIC', fertilityRate: 6.11, femaleLaborParticipation: 61.4 },
  { country: 'Congo, Rep.', incomeGroup: 'LMC', fertilityRate: 4.22, femaleLaborParticipation: 65.7 },
  { country: 'Costa Rica', incomeGroup: 'HIC', fertilityRate: 1.34, femaleLaborParticipation: 50.3 },
  { country: "Cote d'Ivoire", incomeGroup: 'LMC', fertilityRate: 4.35, femaleLaborParticipation: 59.1 },
  { country: 'Croatia', incomeGroup: 'HIC', fertilityRate: 1.53, femaleLaborParticipation: 47 },
  { country: 'Cuba', incomeGroup: 'UMC', fertilityRate: 1.41, femaleLaborParticipation: 41.9 },
  { country: 'Cyprus', incomeGroup: 'HIC', fertilityRate: 1.39, femaleLaborParticipation: 61.2 },
  { country: 'Czechia', incomeGroup: 'HIC', fertilityRate: 1.64, femaleLaborParticipation: 52.2 },
  { country: 'Denmark', incomeGroup: 'HIC', fertilityRate: 1.55, femaleLaborParticipation: 59.6 },
  { country: 'Djibouti', incomeGroup: 'LMC', fertilityRate: 2.65, femaleLaborParticipation: 18.7 },
  { country: 'Dominican Republic', incomeGroup: 'UMC', fertilityRate: 2.27, femaleLaborParticipation: 50.5 },
  { country: 'Ecuador', incomeGroup: 'UMC', fertilityRate: 1.86, femaleLaborParticipation: 54.2 },
  { country: 'Egypt, Arab Rep.', incomeGroup: 'LMC', fertilityRate: 2.75, femaleLaborParticipation: 15.2 },
  { country: 'El Salvador', incomeGroup: 'UMC', fertilityRate: 1.78, femaleLaborParticipation: 46 },
  { country: 'Equatorial Guinea', incomeGroup: 'UMC', fertilityRate: 4.17, femaleLaborParticipation: 53.5 },
  { country: 'Eritrea', incomeGroup: 'LIC', fertilityRate: 3.79, femaleLaborParticipation: 72.9 },
  { country: 'Estonia', incomeGroup: 'HIC', fertilityRate: 1.41, femaleLaborParticipation: 60.1 },
  { country: 'Eswatini', incomeGroup: 'LMC', fertilityRate: 2.8, femaleLaborParticipation: 47.2 },
  { country: 'Ethiopia', incomeGroup: 'LIC', fertilityRate: 4.08, femaleLaborParticipation: 58 },
  { country: 'Fiji', incomeGroup: 'UMC', fertilityRate: 2.31, femaleLaborParticipation: 38.2 },
  { country: 'Finland', incomeGroup: 'HIC', fertilityRate: 1.32, femaleLaborParticipation: 57.3 },
  { country: 'France', incomeGroup: 'HIC', fertilityRate: 1.78, femaleLaborParticipation: 51.9 },
  { country: 'French Polynesia', incomeGroup: 'HIC', fertilityRate: 1.52, femaleLaborParticipation: 47.8 },
  { country: 'Gabon', incomeGroup: 'UMC', fertilityRate: 3.71, femaleLaborParticipation: 41.9 },
  { country: 'Gambia, The', incomeGroup: 'LIC', fertilityRate: 4.08, femaleLaborParticipation: 45.1 },
  { country: 'Georgia', incomeGroup: 'UMC', fertilityRate: 1.82, femaleLaborParticipation: 55.8 },
  { country: 'Germany', incomeGroup: 'HIC', fertilityRate: 1.46, femaleLaborParticipation: 55.5 },
  { country: 'Ghana', incomeGroup: 'LMC', fertilityRate: 3.43, femaleLaborParticipation: 55.5 },
  { country: 'Greece', incomeGroup: 'HIC', fertilityRate: 1.32, femaleLaborParticipation: 44.4 },
  { country: 'Guam', incomeGroup: 'HIC', fertilityRate: 2.82, femaleLaborParticipation: 56.3 },
  { country: 'Guatemala', incomeGroup: 'UMC', fertilityRate: 2.34, femaleLaborParticipation: 40.5 },
  { country: 'Guinea', incomeGroup: 'LMC', fertilityRate: 4.3, femaleLaborParticipation: 42.5 },
  { country: 'Guinea-Bissau', incomeGroup: 'LIC', fertilityRate: 3.91, femaleLaborParticipation: 60 },
  { country: 'Guyana', incomeGroup: 'HIC', fertilityRate: 2.44, femaleLaborParticipation: 45.1 },
  { country: 'Haiti', incomeGroup: 'LMC', fertilityRate: 2.7, femaleLaborParticipation: 59.9 },
  { country: 'Honduras', incomeGroup: 'LMC', fertilityRate: 2.52, femaleLaborParticipation: 43.6 },
  { country: 'Hong Kong SAR, China', incomeGroup: 'HIC', fertilityRate: 0.7, femaleLaborParticipation: 52.8 },
  { country: 'Hungary', incomeGroup: 'HIC', fertilityRate: 1.57, femaleLaborParticipation: 53.1 },
  { country: 'Iceland', incomeGroup: 'HIC', fertilityRate: 1.59, femaleLaborParticipation: 70.6 },
  { country: 'India', incomeGroup: 'LMC', fertilityRate: 1.99, femaleLaborParticipation: 29.3 },
  { country: 'Indonesia', incomeGroup: 'UMC', fertilityRate: 2.15, femaleLaborParticipation: 52.6 },
  { country: 'Iran, Islamic Rep.', incomeGroup: 'UMC', fertilityRate: 1.7, femaleLaborParticipation: 13.5 },
  { country: 'Iraq', incomeGroup: 'UMC', fertilityRate: 3.29, femaleLaborParticipation: 11.2 },
  { country: 'Ireland', incomeGroup: 'HIC', fertilityRate: 1.51, femaleLaborParticipation: 59.1 },
  { country: 'Israel', incomeGroup: 'HIC', fertilityRate: 2.89, femaleLaborParticipation: 61.1 },
  { country: 'Italy', incomeGroup: 'HIC', fertilityRate: 1.24, femaleLaborParticipation: 40.5 },
  { country: 'Jamaica', incomeGroup: 'UMC', fertilityRate: 1.37, femaleLaborParticipation: 60.8 },
  { country: 'Japan', incomeGroup: 'HIC', fertilityRate: 1.26, femaleLaborParticipation: 54.2 },
  { country: 'Jordan', incomeGroup: 'UMC', fertilityRate: 2.68, femaleLaborParticipation: 13.9 },
  { country: 'Kazakhstan', incomeGroup: 'UMC', fertilityRate: 3.05, femaleLaborParticipation: 64.7 },
  { country: 'Kenya', incomeGroup: 'LMC', fertilityRate: 3.26, femaleLaborParticipation: 62.8 },
  { country: "Korea, Dem. People's Rep.", incomeGroup: 'LIC', fertilityRate: 1.8, femaleLaborParticipation: 77.7 },
  { country: 'Korea, Rep.', incomeGroup: 'HIC', fertilityRate: 0.78, femaleLaborParticipation: 55 },
  { country: 'Kuwait', incomeGroup: 'HIC', fertilityRate: 1.55, femaleLaborParticipation: 49.6 },
  { country: 'Kyrgyz Republic', incomeGroup: 'LMC', fertilityRate: 2.8, femaleLaborParticipation: 45.2 },
  { country: 'Lao PDR', incomeGroup: 'LMC', fertilityRate: 2.46, femaleLaborParticipation: 61.4 },
  { country: 'Latvia', incomeGroup: 'HIC', fertilityRate: 1.47, femaleLaborParticipation: 55.3 },
  { country: 'Lebanon', incomeGroup: 'LMC', fertilityRate: 2.26, femaleLaborParticipation: 22.3 },
  { country: 'Lesotho', incomeGroup: 'LMC', fertilityRate: 2.72, femaleLaborParticipation: 48.4 },
  { country: 'Liberia', incomeGroup: 'LIC', fertilityRate: 4.02, femaleLaborParticipation: 71.9 },
  { country: 'Libya', incomeGroup: 'UMC', fertilityRate: 2.4, femaleLaborParticipation: 33.6 },
  { country: 'Lithuania', incomeGroup: 'HIC', fertilityRate: 1.27, femaleLaborParticipation: 58 },
  { country: 'Luxembourg', incomeGroup: 'HIC', fertilityRate: 1.31, femaleLaborParticipation: 57 },
  { country: 'Macao SAR, China', incomeGroup: 'HIC', fertilityRate: 0.68, femaleLaborParticipation: 60 },
  { country: 'Madagascar', incomeGroup: 'LIC', fertilityRate: 4.04, femaleLaborParticipation: 82.8 },
  { country: 'Malawi', incomeGroup: 'LIC', fertilityRate: 3.72, femaleLaborParticipation: 58.8 },
  { country: 'Malaysia', incomeGroup: 'UMC', fertilityRate: 1.55, femaleLaborParticipation: 51.6 },
  { country: 'Maldives', incomeGroup: 'UMC', fertilityRate: 1.58, femaleLaborParticipation: 40.2 },
  { country: 'Mali', incomeGroup: 'LIC', fertilityRate: 5.69, femaleLaborParticipation: 53 },
  { country: 'Malta', incomeGroup: 'HIC', fertilityRate: 1.08, femaleLaborParticipation: 55.3 },
  { country: 'Mauritania', incomeGroup: 'LMC', fertilityRate: 4.77, femaleLaborParticipation: 26 },
  { country: 'Mauritius', incomeGroup: 'UMC', fertilityRate: 1.33, femaleLaborParticipation: 42.5 },
  { country: 'Mexico', incomeGroup: 'UMC', fertilityRate: 1.94, femaleLaborParticipation: 46 },
  { country: 'Moldova', incomeGroup: 'UMC', fertilityRate: 1.69, femaleLaborParticipation: 71.5 },
  { country: 'Mongolia', incomeGroup: 'UMC', fertilityRate: 2.7, femaleLaborParticipation: 54.6 },
  { country: 'Montenegro', incomeGroup: 'UMC', fertilityRate: 1.8, femaleLaborParticipation: 48.5 },
  { country: 'Morocco', incomeGroup: 'LMC', fertilityRate: 2.26, femaleLaborParticipation: 19.6 },
  { country: 'Mozambique', incomeGroup: 'LIC', fertilityRate: 4.84, femaleLaborParticipation: 77.2 },
  { country: 'Myanmar', incomeGroup: 'LMC', fertilityRate: 2.13, femaleLaborParticipation: 41.1 },
  { country: 'Namibia', incomeGroup: 'LMC', fertilityRate: 3.25, femaleLaborParticipation: 54.7 },
  { country: 'Nepal', incomeGroup: 'LMC', fertilityRate: 2, femaleLaborParticipation: 27.2 },
  { country: 'Netherlands', incomeGroup: 'HIC', fertilityRate: 1.49, femaleLaborParticipation: 62.6 },
  { country: 'New Caledonia', incomeGroup: 'HIC', fertilityRate: 2, femaleLaborParticipation: 52.6 },
  { country: 'New Zealand', incomeGroup: 'HIC', fertilityRate: 1.67, femaleLaborParticipation: 66.4 },
  { country: 'Nicaragua', incomeGroup: 'LMC', fertilityRate: 2.24, femaleLaborParticipation: 50.1 },
  { country: 'Niger', incomeGroup: 'LIC', fertilityRate: 6.14, femaleLaborParticipation: 72.6 },
  { country: 'Nigeria', incomeGroup: 'LMC', fertilityRate: 4.55, femaleLaborParticipation: 76.9 },
  { country: 'North Macedonia', incomeGroup: 'UMC', fertilityRate: 1.6, femaleLaborParticipation: 42.2 },
  { country: 'Norway', incomeGroup: 'HIC', fertilityRate: 1.41, femaleLaborParticipation: 62.4 },
  { country: 'Oman', incomeGroup: 'HIC', fertilityRate: 2.45, femaleLaborParticipation: 30.8 },
  { country: 'Pakistan', incomeGroup: 'LMC', fertilityRate: 3.66, femaleLaborParticipation: 24 },
  { country: 'Panama', incomeGroup: 'HIC', fertilityRate: 2.14, femaleLaborParticipation: 52.1 },
  { country: 'Papua New Guinea', incomeGroup: 'LMC', fertilityRate: 3.16, femaleLaborParticipation: 50.6 },
  { country: 'Paraguay', incomeGroup: 'UMC', fertilityRate: 2.44, femaleLaborParticipation: 59 },
  { country: 'Peru', incomeGroup: 'UMC', fertilityRate: 2, femaleLaborParticipation: 66.7 },
  { country: 'Philippines', incomeGroup: 'UMC', fertilityRate: 1.93, femaleLaborParticipation: 50.4 },
  { country: 'Poland', incomeGroup: 'HIC', fertilityRate: 1.29, femaleLaborParticipation: 51.6 },
  { country: 'Portugal', incomeGroup: 'HIC', fertilityRate: 1.43, femaleLaborParticipation: 53.8 },
  { country: 'Puerto Rico (US)', incomeGroup: 'HIC', fertilityRate: 0.91, femaleLaborParticipation: 35.9 },
  { country: 'Qatar', incomeGroup: 'HIC', fertilityRate: 1.74, femaleLaborParticipation: 63.5 },
  { country: 'Romania', incomeGroup: 'HIC', fertilityRate: 1.71, femaleLaborParticipation: 43.2 },
  { country: 'Russian Federation', incomeGroup: 'HIC', fertilityRate: 1.42, femaleLaborParticipation: 55.3 },
  { country: 'Rwanda', incomeGroup: 'LIC', fertilityRate: 3.78, femaleLaborParticipation: 54.7 },
  { country: 'Samoa', incomeGroup: 'UMC', fertilityRate: 3.88, femaleLaborParticipation: 31.1 },
  { country: 'Sao Tome and Principe', incomeGroup: 'LMC', fertilityRate: 3.7, femaleLaborParticipation: 23 },
  { country: 'Saudi Arabia', incomeGroup: 'HIC', fertilityRate: 2.14, femaleLaborParticipation: 34.1 },
  { country: 'Senegal', incomeGroup: 'LMC', fertilityRate: 3.86, femaleLaborParticipation: 37.7 },
  { country: 'Serbia', incomeGroup: 'UMC', fertilityRate: 1.59, femaleLaborParticipation: 50.1 },
  { country: 'Sierra Leone', incomeGroup: 'LIC', fertilityRate: 3.88, femaleLaborParticipation: 51.6 },
  { country: 'Singapore', incomeGroup: 'HIC', fertilityRate: 1.04, femaleLaborParticipation: 62.9 },
  { country: 'Slovak Republic', incomeGroup: 'HIC', fertilityRate: 1.57, femaleLaborParticipation: 55.7 },
  { country: 'Slovenia', incomeGroup: 'HIC', fertilityRate: 1.55, femaleLaborParticipation: 53.9 },
  { country: 'Solomon Islands', incomeGroup: 'LMC', fertilityRate: 3.62, femaleLaborParticipation: 82.3 },
  { country: 'Somalia, Fed. Rep.', incomeGroup: 'LIC', fertilityRate: 6.26, femaleLaborParticipation: 20.7 },
  { country: 'South Africa', incomeGroup: 'UMC', fertilityRate: 2.23, femaleLaborParticipation: 47.1 },
  { country: 'South Sudan', incomeGroup: 'LIC', fertilityRate: 3.96, femaleLaborParticipation: 70.6 },
  { country: 'Spain', incomeGroup: 'HIC', fertilityRate: 1.16, femaleLaborParticipation: 52.3 },
  { country: 'Sri Lanka', incomeGroup: 'UMC', fertilityRate: 1.98, femaleLaborParticipation: 31.6 },
  { country: 'St. Lucia', incomeGroup: 'UMC', fertilityRate: 1.39, femaleLaborParticipation: 62.7 },
  {
    country: 'St. Vincent and the Grenadines',
    incomeGroup: 'UMC',
    fertilityRate: 1.79,
    femaleLaborParticipation: 57.6,
  },
  { country: 'Sudan', incomeGroup: 'LIC', fertilityRate: 4.38, femaleLaborParticipation: 14.5 },
  { country: 'Suriname', incomeGroup: 'UMC', fertilityRate: 2.27, femaleLaborParticipation: 44 },
  { country: 'Sweden', incomeGroup: 'HIC', fertilityRate: 1.53, femaleLaborParticipation: 61 },
  { country: 'Switzerland', incomeGroup: 'HIC', fertilityRate: 1.39, femaleLaborParticipation: 61.9 },
  { country: 'Syrian Arab Republic', incomeGroup: 'LIC', fertilityRate: 2.75, femaleLaborParticipation: 13 },
  { country: 'Tajikistan', incomeGroup: 'LMC', fertilityRate: 3.13, femaleLaborParticipation: 21.4 },
  { country: 'Tanzania', incomeGroup: 'LMC', fertilityRate: 4.67, femaleLaborParticipation: 80.3 },
  { country: 'Thailand', incomeGroup: 'UMC', fertilityRate: 1.22, femaleLaborParticipation: 59.6 },
  { country: 'Timor-Leste', incomeGroup: 'LMC', fertilityRate: 2.8, femaleLaborParticipation: 61.2 },
  { country: 'Togo', incomeGroup: 'LMC', fertilityRate: 4.25, femaleLaborParticipation: 56.2 },
  { country: 'Tonga', incomeGroup: 'UMC', fertilityRate: 3.17, femaleLaborParticipation: 42.6 },
  { country: 'Trinidad and Tobago', incomeGroup: 'HIC', fertilityRate: 1.54, femaleLaborParticipation: 50 },
  { country: 'Tunisia', incomeGroup: 'LMC', fertilityRate: 1.85, femaleLaborParticipation: 27.5 },
  { country: 'Turkiye', incomeGroup: 'UMC', fertilityRate: 1.63, femaleLaborParticipation: 35 },
  { country: 'Turkmenistan', incomeGroup: 'UMC', fertilityRate: 2.73, femaleLaborParticipation: 38.4 },
  { country: 'Uganda', incomeGroup: 'LIC', fertilityRate: 4.39, femaleLaborParticipation: 75.4 },
  { country: 'United Arab Emirates', incomeGroup: 'HIC', fertilityRate: 1.15, femaleLaborParticipation: 53.1 },
  { country: 'United Kingdom', incomeGroup: 'HIC', fertilityRate: 1.56, femaleLaborParticipation: 57.7 },
  { country: 'United States', incomeGroup: 'HIC', fertilityRate: 1.66, femaleLaborParticipation: 56 },
  { country: 'Uruguay', incomeGroup: 'HIC', fertilityRate: 1.42, femaleLaborParticipation: 55.7 },
  { country: 'Uzbekistan', incomeGroup: 'LMC', fertilityRate: 3.4, femaleLaborParticipation: 41.1 },
  { country: 'Vanuatu', incomeGroup: 'LMC', fertilityRate: 3.65, femaleLaborParticipation: 53.6 },
  { country: 'Venezuela, RB', incomeGroup: 'LMC', fertilityRate: 2.09, femaleLaborParticipation: 35.3 },
  { country: 'Viet Nam', incomeGroup: 'UMC', fertilityRate: 1.93, femaleLaborParticipation: 69.9 },
  { country: 'Virgin Islands (U.S.)', incomeGroup: 'HIC', fertilityRate: 2, femaleLaborParticipation: 52.9 },
  { country: 'West Bank and Gaza', incomeGroup: 'LMC', fertilityRate: 3.38, femaleLaborParticipation: 18.9 },
  { country: 'Yemen, Rep.', incomeGroup: 'LIC', fertilityRate: 4.59, femaleLaborParticipation: 4.8 },
  { country: 'Zambia', incomeGroup: 'LMC', fertilityRate: 4.18, femaleLaborParticipation: 54 },
  { country: 'Zimbabwe', incomeGroup: 'LMC', fertilityRate: 3.77, femaleLaborParticipation: 59.8 },
];
