import type { PreviewControlContract } from '@/modules/docs/preview';

import { definePreviewControls } from '@/modules/docs/preview';

/** Scope 局部坐标 playground 使用的稳定字段 id */
export const ScopeTransformControlId = {
  Operation: 'operation',
  PlacementEnabled: 'placementEnabled',
  PlacementTarget: 'placementTarget',
  Referent: 'referent',
  SelfAnchor: 'selfAnchor',
  SelfPoint: 'selfPoint',
  TranslateX: 'translateX',
  TranslateY: 'translateY',
  PolarAngle: 'polarAngle',
  Distance: 'distance',
  Direction: 'direction',
  OffsetX: 'offsetX',
  OffsetY: 'offsetY',
  Fraction: 'fraction',
  RotateDegrees: 'rotateDegrees',
  ScaleX: 'scaleX',
  ScaleY: 'scaleY',
  Pivot: 'pivot',
  PivotPoint: 'pivotPoint',
} as const;

/** Scope 局部坐标字段按演示能力显示的共享条件 */
export const ScopeTransformVisibleWhen = {
  Placement: { controlId: ScopeTransformControlId.PlacementEnabled, oneOf: [true] },
  PlacementDisabled: { controlId: ScopeTransformControlId.PlacementEnabled, oneOf: [false] },
  Referent: {
    controlId: ScopeTransformControlId.Operation,
    oneOf: ['polar-translate', 'at-translate', 'offset-translate'],
  },
  Translate: { controlId: ScopeTransformControlId.Operation, oneOf: ['translate'] },
  PolarTranslate: { controlId: ScopeTransformControlId.Operation, oneOf: ['polar-translate'] },
  AtTranslate: { controlId: ScopeTransformControlId.Operation, oneOf: ['at-translate'] },
  OffsetTranslate: { controlId: ScopeTransformControlId.Operation, oneOf: ['offset-translate'] },
  BetweenTranslate: { controlId: ScopeTransformControlId.Operation, oneOf: ['between-translate'] },
  Distance: { controlId: ScopeTransformControlId.Operation, oneOf: ['polar-translate', 'at-translate'] },
  Rotate: { controlId: ScopeTransformControlId.Operation, oneOf: ['rotate'] },
  Scale: { controlId: ScopeTransformControlId.Operation, oneOf: ['scale'] },
  Pivot: { controlId: ScopeTransformControlId.Operation, oneOf: ['rotate', 'scale'] },
  ExplicitSelfPoint: { controlId: ScopeTransformControlId.SelfAnchor, oneOf: ['explicit'] },
  ExplicitPivot: { controlId: ScopeTransformControlId.Pivot, oneOf: ['explicit'] },
} as const;

/** Scope placement 与七种 transform 输入的中文属性面板 */
export const scopeTranslateBasicControls = definePreviewControls({
  presentation: 'panel',
  title: 'Scope 局部坐标',
  sections: [
    {
      label: '演示能力',
      controls: [
        {
          kind: 'select',
          id: ScopeTransformControlId.Operation,
          label: '能力',
          defaultValue: 'translate',
          options: [
            { value: 'translate', label: '笛卡尔平移' },
            { value: 'polar-translate', label: '极坐标平移' },
            { value: 'at-translate', label: '方向相对平移' },
            { value: 'offset-translate', label: '引用点偏移' },
            { value: 'between-translate', label: '两点之间' },
            { value: 'rotate', label: '旋转' },
            { value: 'scale', label: '缩放' },
          ],
        },
        {
          kind: 'switch',
          id: ScopeTransformControlId.PlacementEnabled,
          label: '自身定位',
          defaultValue: false,
        },
      ],
    },
    {
      label: '变换参照',
      visibleWhen: ScopeTransformVisibleWhen.Referent,
      controls: [
        {
          kind: 'select',
          id: ScopeTransformControlId.Referent,
          label: '引用点',
          defaultValue: 'O',
          visibleWhen: ScopeTransformVisibleWhen.PlacementDisabled,
          options: [
            { value: 'O', label: 'O（左）' },
            { value: 'T', label: 'T（右）' },
          ],
        },
      ],
    },
    {
      label: '自身定位',
      visibleWhen: ScopeTransformVisibleWhen.Placement,
      controls: [
        {
          kind: 'select',
          id: ScopeTransformControlId.PlacementTarget,
          label: '定位目标',
          defaultValue: 'T',
          options: [
            { value: 'O', label: 'O（左）' },
            { value: 'T', label: 'T（右）' },
          ],
        },
        {
          kind: 'select',
          id: ScopeTransformControlId.SelfAnchor,
          label: '自身锚点',
          defaultValue: 'center',
          options: [
            { value: 'origin', label: '局部原点' },
            { value: 'center', label: '包络中心' },
            { value: 'right', label: '右侧中心' },
            { value: 'top-left', label: '左上角' },
            { value: 'bottom-right', label: '右下角' },
            { value: 'explicit', label: '显式局部坐标' },
          ],
        },
        {
          kind: 'point',
          id: ScopeTransformControlId.SelfPoint,
          label: '自身点',
          defaultValue: [0, 0],
          min: [-40, -60],
          max: [80, 40],
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.ExplicitSelfPoint,
        },
      ],
    },
    {
      label: '平移参数',
      controls: [
        {
          kind: 'range',
          id: ScopeTransformControlId.TranslateX,
          label: 'translate x',
          defaultValue: 0,
          min: -80,
          max: 80,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.Translate,
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.TranslateY,
          label: 'translate y',
          defaultValue: 0,
          min: -80,
          max: 80,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.Translate,
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.OffsetX,
          label: 'offset x',
          defaultValue: 100,
          min: -100,
          max: 100,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.OffsetTranslate,
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.OffsetY,
          label: 'offset y',
          defaultValue: 0,
          min: -80,
          max: 80,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.OffsetTranslate,
        },
      ],
    },
    {
      label: '相对定位参数',
      controls: [
        {
          kind: 'range',
          id: ScopeTransformControlId.PolarAngle,
          label: '极坐标角度',
          defaultValue: 0,
          min: -180,
          max: 180,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.PolarTranslate,
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.Distance,
          label: '半径 / 距离',
          defaultValue: 100,
          min: 20,
          max: 100,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.Distance,
        },
        {
          kind: 'select',
          id: ScopeTransformControlId.Direction,
          label: '方向',
          defaultValue: 'right',
          visibleWhen: ScopeTransformVisibleWhen.AtTranslate,
          options: [
            { value: 'top', label: '上' },
            { value: 'top-right', label: '右上' },
            { value: 'right', label: '右' },
            { value: 'bottom-right', label: '右下' },
            { value: 'bottom', label: '下' },
            { value: 'bottom-left', label: '左下' },
            { value: 'left', label: '左' },
            { value: 'top-left', label: '左上' },
          ],
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.Fraction,
          label: 'O → T 比例',
          defaultValue: 0.5,
          min: 0,
          max: 1,
          step: 0.05,
          visibleWhen: ScopeTransformVisibleWhen.BetweenTranslate,
        },
      ],
    },
    {
      label: '旋转与缩放',
      controls: [
        {
          kind: 'range',
          id: ScopeTransformControlId.RotateDegrees,
          label: '旋转角度',
          defaultValue: 0,
          min: -180,
          max: 180,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.Rotate,
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.ScaleX,
          label: 'scale x',
          defaultValue: 1,
          min: 0.5,
          max: 1.5,
          step: 0.1,
          visibleWhen: ScopeTransformVisibleWhen.Scale,
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.ScaleY,
          label: 'scale y',
          defaultValue: 1,
          min: 0.5,
          max: 1.5,
          step: 0.1,
          visibleWhen: ScopeTransformVisibleWhen.Scale,
        },
      ],
    },
    {
      label: '变换基点',
      visibleWhen: ScopeTransformVisibleWhen.Pivot,
      controls: [
        {
          kind: 'select',
          id: ScopeTransformControlId.Pivot,
          label: 'pivot',
          defaultValue: 'origin',
          options: [
            { value: 'origin', label: '局部原点' },
            { value: 'center', label: '包络中心' },
            { value: 'right', label: '右侧中心' },
            { value: 'top-left', label: '左上角' },
            { value: 'bottom-right', label: '右下角' },
            { value: 'explicit', label: '显式局部坐标' },
          ],
        },
        {
          kind: 'point',
          id: ScopeTransformControlId.PivotPoint,
          label: 'pivot 坐标',
          defaultValue: [0, 0],
          min: [-40, -60],
          max: [80, 40],
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.ExplicitPivot,
        },
      ],
    },
  ],
});

/** Scope 局部坐标面板的稳定文档契约 */
export const previewControlContract = {
  controls: scopeTranslateBasicControls,
  canonicalValues: {
    operation: 'translate',
    placementEnabled: false,
    placementTarget: 'T',
    referent: 'O',
    selfAnchor: 'center',
    selfPoint: [0, 0],
    translateX: 0,
    translateY: 0,
    offsetX: 100,
    offsetY: 0,
    polarAngle: 0,
    distance: 100,
    direction: 'right',
    fraction: 0.5,
    rotateDegrees: 0,
    scaleX: 1,
    scaleY: 1,
    pivot: 'origin',
    pivotPoint: [0, 0],
  },
  relatedApis: ['Scope.placement', 'Scope.transforms'],
} satisfies PreviewControlContract;
