import { definePreviewControls } from '@/modules/docs/components/component-preview/author';

import { ScopeTransformControlId, ScopeTransformVisibleWhen } from './scope-translate-basic.controls';

/** Scope transform playground controls in English */
export const scopeTranslateBasicEnControls = definePreviewControls({
  presentation: 'panel',
  title: 'Scope transform',
  sections: [
    {
      label: 'Transform type',
      controls: [
        {
          kind: 'select',
          id: ScopeTransformControlId.Kind,
          label: 'kind',
          defaultValue: 'translate',
          options: [
            { value: 'translate', label: 'Cartesian translate' },
            { value: 'polar-translate', label: 'Polar translate' },
            { value: 'at-translate', label: 'Direction relative' },
            { value: 'offset-translate', label: 'Referent offset' },
            { value: 'between-translate', label: 'Between two points' },
            { value: 'rotate', label: 'Rotate' },
            { value: 'scale', label: 'Scale' },
          ],
        },
        {
          kind: 'select',
          id: ScopeTransformControlId.Referent,
          label: 'Referent',
          defaultValue: 'O',
          visibleWhen: ScopeTransformVisibleWhen.Referent,
          options: [
            { value: 'O', label: 'O (left)' },
            { value: 'T', label: 'T (right)' },
          ],
        },
      ],
    },
    {
      label: 'Translate parameters',
      controls: [
        {
          kind: 'range',
          id: ScopeTransformControlId.TranslateX,
          label: 'translate x',
          defaultValue: 0,
          min: -80,
          max: 80,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.Translate,
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.TranslateY,
          label: 'translate y',
          defaultValue: 0,
          min: -80,
          max: 80,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.Translate,
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.OffsetX,
          label: 'offset x',
          defaultValue: 100,
          min: -100,
          max: 100,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.OffsetTranslate,
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.OffsetY,
          label: 'offset y',
          defaultValue: 0,
          min: -80,
          max: 80,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.OffsetTranslate,
        },
      ],
    },
    {
      label: 'Relative parameters',
      controls: [
        {
          kind: 'range',
          id: ScopeTransformControlId.PolarAngle,
          label: 'Polar angle',
          defaultValue: 0,
          min: -180,
          max: 180,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.PolarTranslate,
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.Distance,
          label: 'Radius / distance',
          defaultValue: 100,
          min: 20,
          max: 100,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.Distance,
        },
        {
          kind: 'select',
          id: ScopeTransformControlId.Direction,
          label: 'Direction',
          defaultValue: 'right',
          visibleWhen: ScopeTransformVisibleWhen.AtTranslate,
          options: [
            { value: 'top', label: 'Top' },
            { value: 'top-right', label: 'Top right' },
            { value: 'right', label: 'Right' },
            { value: 'bottom-right', label: 'Bottom right' },
            { value: 'bottom', label: 'Bottom' },
            { value: 'bottom-left', label: 'Bottom left' },
            { value: 'left', label: 'Left' },
            { value: 'top-left', label: 'Top left' },
          ],
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.Fraction,
          label: 'O → T fraction',
          defaultValue: 0.5,
          min: 0,
          max: 1,
          step: 0.05,
          visibleWhen: ScopeTransformVisibleWhen.BetweenTranslate,
        },
      ],
    },
    {
      label: 'Rotate and scale',
      controls: [
        {
          kind: 'range',
          id: ScopeTransformControlId.RotateDegrees,
          label: 'Rotation',
          defaultValue: 0,
          min: -180,
          max: 180,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.Rotate,
        },
        {
          kind: 'number',
          id: ScopeTransformControlId.RotateCenterX,
          label: 'Center x',
          defaultValue: 0,
          min: -40,
          max: 40,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.Rotate,
        },
        {
          kind: 'number',
          id: ScopeTransformControlId.RotateCenterY,
          label: 'Center y',
          defaultValue: 0,
          min: -40,
          max: 40,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.Rotate,
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.ScaleX,
          label: 'scale x',
          defaultValue: 1,
          min: 0.5,
          max: 1.5,
          step: 0.1,
          visibleWhen: ScopeTransformVisibleWhen.Scale,
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.ScaleY,
          label: 'scale y',
          defaultValue: 1,
          min: 0.5,
          max: 1.5,
          step: 0.1,
          visibleWhen: ScopeTransformVisibleWhen.Scale,
        },
      ],
    },
  ],
});
