import type { PreviewControlContract } from '@/modules/docs/preview';

import { definePreviewControls } from '@/modules/docs/preview';

import { ScopeTransformControlId, ScopeTransformVisibleWhen } from './scope-translate-basic.controls';

/** Scope placement and transform playground controls in English */
export const scopeTranslateBasicEnControls = definePreviewControls({
  presentation: 'panel',
  title: 'Scope local coordinates',
  sections: [
    {
      label: 'Operation',
      controls: [
        {
          kind: 'select',
          id: ScopeTransformControlId.Operation,
          label: 'Operation',
          defaultValue: 'translate',
          options: [
            { value: 'translate', label: 'Cartesian translate' },
            { value: 'polar-translate', label: 'Polar translate' },
            { value: 'at-translate', label: 'Direction relative' },
            { value: 'offset-translate', label: 'Referent offset' },
            { value: 'between-translate', label: 'Between two points' },
            { value: 'rotate', label: 'Rotate' },
            { value: 'scale', label: 'Scale' },
          ],
        },
        {
          kind: 'switch',
          id: ScopeTransformControlId.PlacementEnabled,
          label: 'Self placement',
          defaultValue: false,
        },
      ],
    },
    {
      label: 'Transform referent',
      visibleWhen: ScopeTransformVisibleWhen.Referent,
      controls: [
        {
          kind: 'select',
          id: ScopeTransformControlId.Referent,
          label: 'Referent',
          defaultValue: 'O',
          visibleWhen: ScopeTransformVisibleWhen.PlacementDisabled,
          options: [
            { value: 'O', label: 'O (left)' },
            { value: 'T', label: 'T (right)' },
          ],
        },
      ],
    },
    {
      label: 'Self placement',
      visibleWhen: ScopeTransformVisibleWhen.Placement,
      controls: [
        {
          kind: 'select',
          id: ScopeTransformControlId.PlacementTarget,
          label: 'Placement target',
          defaultValue: 'T',
          options: [
            { value: 'O', label: 'O (left)' },
            { value: 'T', label: 'T (right)' },
          ],
        },
        {
          kind: 'select',
          id: ScopeTransformControlId.SelfAnchor,
          label: 'selfAnchor',
          defaultValue: 'center',
          options: [
            { value: 'origin', label: 'Local origin' },
            { value: 'center', label: 'Envelope center' },
            { value: 'right', label: 'Right center' },
            { value: 'top-left', label: 'Top left' },
            { value: 'bottom-right', label: 'Bottom right' },
            { value: 'explicit', label: 'Explicit local point' },
          ],
        },
        {
          kind: 'point',
          id: ScopeTransformControlId.SelfPoint,
          label: 'Self point',
          defaultValue: [0, 0],
          min: [-40, -60],
          max: [80, 40],
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.ExplicitSelfPoint,
        },
      ],
    },
    {
      label: 'Translate parameters',
      controls: [
        {
          kind: 'range',
          id: ScopeTransformControlId.TranslateX,
          label: 'translate x',
          defaultValue: 0,
          min: -80,
          max: 80,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.Translate,
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.TranslateY,
          label: 'translate y',
          defaultValue: 0,
          min: -80,
          max: 80,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.Translate,
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.OffsetX,
          label: 'offset x',
          defaultValue: 100,
          min: -100,
          max: 100,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.OffsetTranslate,
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.OffsetY,
          label: 'offset y',
          defaultValue: 0,
          min: -80,
          max: 80,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.OffsetTranslate,
        },
      ],
    },
    {
      label: 'Relative parameters',
      controls: [
        {
          kind: 'range',
          id: ScopeTransformControlId.PolarAngle,
          label: 'Polar angle',
          defaultValue: 0,
          min: -180,
          max: 180,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.PolarTranslate,
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.Distance,
          label: 'Radius / distance',
          defaultValue: 100,
          min: 20,
          max: 100,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.Distance,
        },
        {
          kind: 'select',
          id: ScopeTransformControlId.Direction,
          label: 'Direction',
          defaultValue: 'right',
          visibleWhen: ScopeTransformVisibleWhen.AtTranslate,
          options: [
            { value: 'top', label: 'Top' },
            { value: 'top-right', label: 'Top right' },
            { value: 'right', label: 'Right' },
            { value: 'bottom-right', label: 'Bottom right' },
            { value: 'bottom', label: 'Bottom' },
            { value: 'bottom-left', label: 'Bottom left' },
            { value: 'left', label: 'Left' },
            { value: 'top-left', label: 'Top left' },
          ],
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.Fraction,
          label: 'O → T fraction',
          defaultValue: 0.5,
          min: 0,
          max: 1,
          step: 0.05,
          visibleWhen: ScopeTransformVisibleWhen.BetweenTranslate,
        },
      ],
    },
    {
      label: 'Rotate and scale',
      controls: [
        {
          kind: 'range',
          id: ScopeTransformControlId.RotateDegrees,
          label: 'Rotation',
          defaultValue: 0,
          min: -180,
          max: 180,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.Rotate,
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.ScaleX,
          label: 'scale x',
          defaultValue: 1,
          min: 0.5,
          max: 1.5,
          step: 0.1,
          visibleWhen: ScopeTransformVisibleWhen.Scale,
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.ScaleY,
          label: 'scale y',
          defaultValue: 1,
          min: 0.5,
          max: 1.5,
          step: 0.1,
          visibleWhen: ScopeTransformVisibleWhen.Scale,
        },
      ],
    },
    {
      label: 'Transform pivot',
      visibleWhen: ScopeTransformVisibleWhen.Pivot,
      controls: [
        {
          kind: 'select',
          id: ScopeTransformControlId.Pivot,
          label: 'pivot',
          defaultValue: 'origin',
          options: [
            { value: 'origin', label: 'Local origin' },
            { value: 'center', label: 'Envelope center' },
            { value: 'right', label: 'Right center' },
            { value: 'top-left', label: 'Top left' },
            { value: 'bottom-right', label: 'Bottom right' },
            { value: 'explicit', label: 'Explicit local point' },
          ],
        },
        {
          kind: 'point',
          id: ScopeTransformControlId.PivotPoint,
          label: 'Pivot point',
          defaultValue: [0, 0],
          min: [-40, -60],
          max: [80, 40],
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.ExplicitPivot,
        },
      ],
    },
  ],
});

/** Stable documentation contract for the Scope local-coordinate controls */
export const previewControlContract = {
  controls: scopeTranslateBasicEnControls,
  canonicalValues: {
    operation: 'translate',
    placementEnabled: false,
    placementTarget: 'T',
    referent: 'O',
    selfAnchor: 'center',
    selfPoint: [0, 0],
    translateX: 0,
    translateY: 0,
    offsetX: 100,
    offsetY: 0,
    polarAngle: 0,
    distance: 100,
    direction: 'right',
    fraction: 0.5,
    rotateDegrees: 0,
    scaleX: 1,
    scaleY: 1,
    pivot: 'origin',
    pivotPoint: [0, 0],
  },
  relatedApis: ['Scope.placement', 'Scope.transforms'],
} satisfies PreviewControlContract;
