import type { PreviewControlContract } from '@/modules/docs/preview';

import { definePreviewControls } from '@/modules/docs/preview';

/** Scope transform playground 使用的稳定字段 id */
export const ScopeTransformControlId = {
  Kind: 'transformKind',
  Referent: 'referent',
  TranslateX: 'translateX',
  TranslateY: 'translateY',
  PolarAngle: 'polarAngle',
  Distance: 'distance',
  Direction: 'direction',
  OffsetX: 'offsetX',
  OffsetY: 'offsetY',
  Fraction: 'fraction',
  RotateDegrees: 'rotateDegrees',
  RotateCenterX: 'rotateCenterX',
  RotateCenterY: 'rotateCenterY',
  ScaleX: 'scaleX',
  ScaleY: 'scaleY',
} as const;

/** Scope transform 字段按 kind 显示的共享条件 */
export const ScopeTransformVisibleWhen = {
  Referent: {
    controlId: ScopeTransformControlId.Kind,
    oneOf: ['polar-translate', 'at-translate', 'offset-translate'],
  },
  Translate: { controlId: ScopeTransformControlId.Kind, oneOf: ['translate'] },
  PolarTranslate: { controlId: ScopeTransformControlId.Kind, oneOf: ['polar-translate'] },
  AtTranslate: { controlId: ScopeTransformControlId.Kind, oneOf: ['at-translate'] },
  OffsetTranslate: { controlId: ScopeTransformControlId.Kind, oneOf: ['offset-translate'] },
  BetweenTranslate: { controlId: ScopeTransformControlId.Kind, oneOf: ['between-translate'] },
  Distance: { controlId: ScopeTransformControlId.Kind, oneOf: ['polar-translate', 'at-translate'] },
  Rotate: { controlId: ScopeTransformControlId.Kind, oneOf: ['rotate'] },
  Scale: { controlId: ScopeTransformControlId.Kind, oneOf: ['scale'] },
} as const;

/** Scope 七种 transform 输入的中文属性面板 */
export const scopeTranslateBasicControls = definePreviewControls({
  presentation: 'panel',
  title: 'Scope transform',
  sections: [
    {
      label: '变换类型',
      controls: [
        {
          kind: 'select',
          id: ScopeTransformControlId.Kind,
          label: 'kind',
          defaultValue: 'translate',
          options: [
            { value: 'translate', label: '笛卡尔平移' },
            { value: 'polar-translate', label: '极坐标平移' },
            { value: 'at-translate', label: '方向相对平移' },
            { value: 'offset-translate', label: '引用点偏移' },
            { value: 'between-translate', label: '两点之间' },
            { value: 'rotate', label: '旋转' },
            { value: 'scale', label: '缩放' },
          ],
        },
        {
          kind: 'select',
          id: ScopeTransformControlId.Referent,
          label: '引用点',
          defaultValue: 'O',
          visibleWhen: ScopeTransformVisibleWhen.Referent,
          options: [
            { value: 'O', label: 'O（左）' },
            { value: 'T', label: 'T（右）' },
          ],
        },
      ],
    },
    {
      label: '平移参数',
      controls: [
        {
          kind: 'range',
          id: ScopeTransformControlId.TranslateX,
          label: 'translate x',
          defaultValue: 0,
          min: -80,
          max: 80,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.Translate,
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.TranslateY,
          label: 'translate y',
          defaultValue: 0,
          min: -80,
          max: 80,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.Translate,
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.OffsetX,
          label: 'offset x',
          defaultValue: 100,
          min: -100,
          max: 100,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.OffsetTranslate,
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.OffsetY,
          label: 'offset y',
          defaultValue: 0,
          min: -80,
          max: 80,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.OffsetTranslate,
        },
      ],
    },
    {
      label: '相对定位参数',
      controls: [
        {
          kind: 'range',
          id: ScopeTransformControlId.PolarAngle,
          label: '极坐标角度',
          defaultValue: 0,
          min: -180,
          max: 180,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.PolarTranslate,
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.Distance,
          label: '半径 / 距离',
          defaultValue: 100,
          min: 20,
          max: 100,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.Distance,
        },
        {
          kind: 'select',
          id: ScopeTransformControlId.Direction,
          label: '方向',
          defaultValue: 'right',
          visibleWhen: ScopeTransformVisibleWhen.AtTranslate,
          options: [
            { value: 'top', label: '上' },
            { value: 'top-right', label: '右上' },
            { value: 'right', label: '右' },
            { value: 'bottom-right', label: '右下' },
            { value: 'bottom', label: '下' },
            { value: 'bottom-left', label: '左下' },
            { value: 'left', label: '左' },
            { value: 'top-left', label: '左上' },
          ],
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.Fraction,
          label: 'O → T 比例',
          defaultValue: 0.5,
          min: 0,
          max: 1,
          step: 0.05,
          visibleWhen: ScopeTransformVisibleWhen.BetweenTranslate,
        },
      ],
    },
    {
      label: '旋转与缩放',
      controls: [
        {
          kind: 'range',
          id: ScopeTransformControlId.RotateDegrees,
          label: '旋转角度',
          defaultValue: 0,
          min: -180,
          max: 180,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.Rotate,
        },
        {
          kind: 'number',
          id: ScopeTransformControlId.RotateCenterX,
          label: '旋转中心 x',
          defaultValue: 0,
          min: -40,
          max: 40,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.Rotate,
        },
        {
          kind: 'number',
          id: ScopeTransformControlId.RotateCenterY,
          label: '旋转中心 y',
          defaultValue: 0,
          min: -40,
          max: 40,
          step: 5,
          visibleWhen: ScopeTransformVisibleWhen.Rotate,
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.ScaleX,
          label: 'scale x',
          defaultValue: 1,
          min: 0.5,
          max: 1.5,
          step: 0.1,
          visibleWhen: ScopeTransformVisibleWhen.Scale,
        },
        {
          kind: 'range',
          id: ScopeTransformControlId.ScaleY,
          label: 'scale y',
          defaultValue: 1,
          min: 0.5,
          max: 1.5,
          step: 0.1,
          visibleWhen: ScopeTransformVisibleWhen.Scale,
        },
      ],
    },
  ],
});

/** Scope 变换面板的稳定文档契约 */
export const previewControlContract = {
  controls: scopeTranslateBasicControls,
  canonicalValues: {
    transformKind: 'translate',
    referent: 'O',
    translateX: 0,
    translateY: 0,
    offsetX: 100,
    offsetY: 0,
    polarAngle: 0,
    distance: 100,
    direction: 'right',
    fraction: 0.5,
    rotateDegrees: 0,
    rotateCenterX: 0,
    rotateCenterY: 0,
    scaleX: 1,
    scaleY: 1,
  },
  relatedApis: ['Scope.transforms'],
} satisfies PreviewControlContract;
