import type { IRCoordinate } from '@retikz/core';

import type { AnchorIdGenerator, AnchorOwner, AnchorRegistry } from '../contract';
import type { AnchorIdSpec, ExternalRow } from '../schemas';

import { resolveFieldPath } from '../providers';
import { slug } from './provenance';

const ownerText = (owner: AnchorOwner): string => {
  const id = owner.markId === undefined ? '' : ` id="${owner.markId}"`;
  const role = owner.role === undefined ? '' : ` ${owner.role}`;
  return `${owner.markType}${role} mark${id} at markIndex=${owner.markIndex}, rowIndex=${owner.transformedIndex}`;
};

const renderTemplate = (template: string, row: ExternalRow, owner: AnchorOwner, plotId: string | undefined): string =>
  template.replace(/\{(plotId|markId|markIndex|index|field:[^}]+)\}/g, (match, token: string) => {
    if (token === 'plotId') return plotId ?? '';
    if (token === 'markId') return owner.markId ?? '';
    if (token === 'markIndex') return String(owner.markIndex);
    if (token === 'index') return String(owner.transformedIndex);
    const field = token.slice('field:'.length);
    const value = resolveFieldPath(row, field);
    if (value === undefined) {
      throw new Error(`lowerPlots: anchorId template references missing field "${field}" for ${ownerText(owner)}`);
    }
    return slug(value);
  });

const defaultPrefix = (owner: AnchorOwner): string => owner.markId ?? `mark.${owner.markIndex}`;

export const createAnchorRegistry = (options: {
  plotId?: string;
  generators?: Record<string, AnchorIdGenerator>;
}): AnchorRegistry => {
  const registered = new Map<string, AnchorOwner>();
  const pending: Array<{ id: string; owner: AnchorOwner }> = [];

  const makeScopedId = (prefix: string, raw: unknown): string => {
    const scoped = `${prefix}.${slug(raw)}`;
    return options.plotId === undefined ? scoped : `${options.plotId}.${scoped}`;
  };

  const makeId = (spec: AnchorIdSpec, row: ExternalRow, owner: AnchorOwner): string => {
    const prefix = spec.prefix ?? defaultPrefix(owner);
    if (spec.field !== undefined) {
      const raw = resolveFieldPath(row, spec.field);
      if (raw === undefined) {
        throw new Error(`lowerPlots: anchorId field "${spec.field}" missing for ${ownerText(owner)}`);
      }
      return makeScopedId(prefix, raw);
    }
    if (spec.template !== undefined) {
      const rendered = renderTemplate(spec.template, row, owner, options.plotId);
      if (rendered.length === 0) {
        throw new Error(`lowerPlots: anchorId template produced an empty id for ${ownerText(owner)}`);
      }
      return rendered.includes('.') || options.plotId === undefined ? rendered : `${options.plotId}.${rendered}`;
    }
    if (spec.generator !== undefined) {
      const generator = options.generators?.[spec.generator];
      if (generator === undefined) {
        throw new Error(`lowerPlots: anchorId generator "${spec.generator}" is not registered for ${ownerText(owner)}`);
      }
      const generated = generator(row, {
        plotId: options.plotId,
        markId: owner.markId,
        markIndex: owner.markIndex,
        transformedIndex: owner.transformedIndex,
        prefix,
        role: owner.role,
      });
      if (generated.length === 0) {
        throw new Error(
          `lowerPlots: anchorId generator "${spec.generator}" produced an empty id for ${ownerText(owner)}`,
        );
      }
      return generated.includes('.') || options.plotId === undefined ? generated : `${options.plotId}.${generated}`;
    }
    throw new Error(`lowerPlots: anchorId requires field, template, or generator for ${ownerText(owner)}`);
  };

  const register = (id: string, owner: AnchorOwner): void => {
    const prior = registered.get(id);
    if (prior !== undefined) {
      throw new Error(
        `lowerPlots: duplicate anchor id "${id}" from ${ownerText(owner)}; already registered by ${ownerText(prior)}`,
      );
    }
    registered.set(id, owner);
  };

  return {
    makeId,
    register,
    reference: (id, owner) => {
      pending.push({ id, owner });
    },
    coordinate: (id, position, owner): IRCoordinate => {
      register(id, owner);
      return { type: 'coordinate', id, position };
    },
    assertResolved: () => {
      for (const ref of pending) {
        if (!registered.has(ref.id)) {
          throw new Error(
            `lowerPlots: relation target anchor id "${ref.id}" referenced by ${ownerText(ref.owner)} was not generated by any mark anchorId`,
          );
        }
      }
    },
  };
};
