/** Palmer Penguins 原始数据地址 */
export const PALMER_PENGUINS_SOURCE_URL = 'https://github.com/vega/vega-datasets/blob/main/data/penguins.json';

/** 数据许可：Palmer Station Antarctica LTER，CC0 */
export const PALMER_PENGUINS_LICENSE = 'CC0 1.0';

/** 原始 344 行中鳍长有效的记录数 */
export const PALMER_PENGUINS_VALID_FLIPPER_LENGTH_COUNT = 342;

/**
 * Strip Chart 的确定性展示样本
 * @description 移除鳍长缺失的 2 行后，按源文件顺序从 Adelie、Chinstrap、Gentoo 的有效记录各取前 30 行
 */
export const stripPalmerPenguinsData = [
  { species: 'Adelie', flipperLengthMm: 181 },
  { species: 'Adelie', flipperLengthMm: 186 },
  { species: 'Adelie', flipperLengthMm: 195 },
  { species: 'Adelie', flipperLengthMm: 193 },
  { species: 'Adelie', flipperLengthMm: 190 },
  { species: 'Adelie', flipperLengthMm: 181 },
  { species: 'Adelie', flipperLengthMm: 195 },
  { species: 'Adelie', flipperLengthMm: 193 },
  { species: 'Adelie', flipperLengthMm: 190 },
  { species: 'Adelie', flipperLengthMm: 186 },
  { species: 'Adelie', flipperLengthMm: 180 },
  { species: 'Adelie', flipperLengthMm: 182 },
  { species: 'Adelie', flipperLengthMm: 191 },
  { species: 'Adelie', flipperLengthMm: 198 },
  { species: 'Adelie', flipperLengthMm: 185 },
  { species: 'Adelie', flipperLengthMm: 195 },
  { species: 'Adelie', flipperLengthMm: 197 },
  { species: 'Adelie', flipperLengthMm: 184 },
  { species: 'Adelie', flipperLengthMm: 194 },
  { species: 'Adelie', flipperLengthMm: 174 },
  { species: 'Adelie', flipperLengthMm: 180 },
  { species: 'Adelie', flipperLengthMm: 189 },
  { species: 'Adelie', flipperLengthMm: 185 },
  { species: 'Adelie', flipperLengthMm: 180 },
  { species: 'Adelie', flipperLengthMm: 187 },
  { species: 'Adelie', flipperLengthMm: 183 },
  { species: 'Adelie', flipperLengthMm: 187 },
  { species: 'Adelie', flipperLengthMm: 172 },
  { species: 'Adelie', flipperLengthMm: 180 },
  { species: 'Adelie', flipperLengthMm: 178 },
  { species: 'Chinstrap', flipperLengthMm: 192 },
  { species: 'Chinstrap', flipperLengthMm: 196 },
  { species: 'Chinstrap', flipperLengthMm: 193 },
  { species: 'Chinstrap', flipperLengthMm: 188 },
  { species: 'Chinstrap', flipperLengthMm: 197 },
  { species: 'Chinstrap', flipperLengthMm: 198 },
  { species: 'Chinstrap', flipperLengthMm: 178 },
  { species: 'Chinstrap', flipperLengthMm: 197 },
  { species: 'Chinstrap', flipperLengthMm: 195 },
  { species: 'Chinstrap', flipperLengthMm: 198 },
  { species: 'Chinstrap', flipperLengthMm: 193 },
  { species: 'Chinstrap', flipperLengthMm: 194 },
  { species: 'Chinstrap', flipperLengthMm: 185 },
  { species: 'Chinstrap', flipperLengthMm: 201 },
  { species: 'Chinstrap', flipperLengthMm: 190 },
  { species: 'Chinstrap', flipperLengthMm: 201 },
  { species: 'Chinstrap', flipperLengthMm: 197 },
  { species: 'Chinstrap', flipperLengthMm: 181 },
  { species: 'Chinstrap', flipperLengthMm: 190 },
  { species: 'Chinstrap', flipperLengthMm: 195 },
  { species: 'Chinstrap', flipperLengthMm: 181 },
  { species: 'Chinstrap', flipperLengthMm: 191 },
  { species: 'Chinstrap', flipperLengthMm: 187 },
  { species: 'Chinstrap', flipperLengthMm: 193 },
  { species: 'Chinstrap', flipperLengthMm: 195 },
  { species: 'Chinstrap', flipperLengthMm: 197 },
  { species: 'Chinstrap', flipperLengthMm: 200 },
  { species: 'Chinstrap', flipperLengthMm: 200 },
  { species: 'Chinstrap', flipperLengthMm: 191 },
  { species: 'Chinstrap', flipperLengthMm: 205 },
  { species: 'Gentoo', flipperLengthMm: 211 },
  { species: 'Gentoo', flipperLengthMm: 230 },
  { species: 'Gentoo', flipperLengthMm: 210 },
  { species: 'Gentoo', flipperLengthMm: 218 },
  { species: 'Gentoo', flipperLengthMm: 215 },
  { species: 'Gentoo', flipperLengthMm: 210 },
  { species: 'Gentoo', flipperLengthMm: 211 },
  { species: 'Gentoo', flipperLengthMm: 219 },
  { species: 'Gentoo', flipperLengthMm: 209 },
  { species: 'Gentoo', flipperLengthMm: 215 },
  { species: 'Gentoo', flipperLengthMm: 214 },
  { species: 'Gentoo', flipperLengthMm: 216 },
  { species: 'Gentoo', flipperLengthMm: 214 },
  { species: 'Gentoo', flipperLengthMm: 213 },
  { species: 'Gentoo', flipperLengthMm: 210 },
  { species: 'Gentoo', flipperLengthMm: 217 },
  { species: 'Gentoo', flipperLengthMm: 210 },
  { species: 'Gentoo', flipperLengthMm: 221 },
  { species: 'Gentoo', flipperLengthMm: 209 },
  { species: 'Gentoo', flipperLengthMm: 222 },
  { species: 'Gentoo', flipperLengthMm: 218 },
  { species: 'Gentoo', flipperLengthMm: 215 },
  { species: 'Gentoo', flipperLengthMm: 213 },
  { species: 'Gentoo', flipperLengthMm: 215 },
  { species: 'Gentoo', flipperLengthMm: 215 },
  { species: 'Gentoo', flipperLengthMm: 215 },
  { species: 'Gentoo', flipperLengthMm: 216 },
  { species: 'Gentoo', flipperLengthMm: 215 },
  { species: 'Gentoo', flipperLengthMm: 210 },
  { species: 'Gentoo', flipperLengthMm: 220 },
];
