/** 产品与套餐维度的月度账户数，缺少 P2 + T2 组合以展示空面板策略 */
export const accountRows: Array<Record<string, string | number>> = [
  { product: 'P1', tier: 'T1', month: 1, accounts: 18 },
  { product: 'P1', tier: 'T1', month: 2, accounts: 23 },
  { product: 'P1', tier: 'T1', month: 3, accounts: 29 },
  { product: 'P1', tier: 'T1', month: 4, accounts: 35 },
  { product: 'P1', tier: 'T2', month: 1, accounts: 105 },
  { product: 'P1', tier: 'T2', month: 2, accounts: 126 },
  { product: 'P1', tier: 'T2', month: 3, accounts: 148 },
  { product: 'P1', tier: 'T2', month: 4, accounts: 171 },
  { product: 'P2', tier: 'T1', month: 1, accounts: 6 },
  { product: 'P2', tier: 'T1', month: 2, accounts: 8 },
  { product: 'P2', tier: 'T1', month: 3, accounts: 9 },
  { product: 'P2', tier: 'T1', month: 4, accounts: 12 },
  { product: 'P3', tier: 'T1', month: 1, accounts: 31 },
  { product: 'P3', tier: 'T1', month: 2, accounts: 36 },
  { product: 'P3', tier: 'T1', month: 3, accounts: 41 },
  { product: 'P3', tier: 'T1', month: 4, accounts: 45 },
  { product: 'P3', tier: 'T2', month: 1, accounts: 220 },
  { product: 'P3', tier: 'T2', month: 2, accounts: 248 },
  { product: 'P3', tier: 'T2', month: 3, accounts: 281 },
  { product: 'P3', tier: 'T2', month: 4, accounts: 306 },
];
