import { BlendMode, NodeTextAlign, ShadowPreset } from '@retikz/core';

import type { PreviewControlContract } from '@/modules/docs/preview';

import { definePreviewControls } from '@/modules/docs/preview';

/** English control panel for node, text, label, and effect channels */
export const builtinNodeTextControls = definePreviewControls({
  presentation: 'panel',
  title: 'Node and text channels',
  defaultSize: 38,
  sections: [
    {
      label: 'Node geometry',
      controls: [
        { kind: 'range', id: 'padding', label: 'padding', defaultValue: 8, min: 0, max: 20, step: 1 },
        {
          kind: 'range',
          id: 'cornerRadius',
          label: 'cornerRadius',
          defaultValue: 8,
          min: 0,
          max: 24,
          step: 1,
        },
        { kind: 'range', id: 'rotate', label: 'rotate', defaultValue: 0, min: -30, max: 30, step: 1 },
        {
          kind: 'range',
          id: 'minimumSize',
          label: 'minimumSize',
          defaultValue: 64,
          min: 36,
          max: 108,
          step: 4,
        },
        { kind: 'range', id: 'scale', label: 'scale', defaultValue: 1, min: 0.7, max: 1.4, step: 0.1 },
      ],
    },
    {
      label: 'Text inside nodes',
      controls: [
        { kind: 'color', id: 'textColor', label: 'textColor', defaultValue: '#1e3a8a' },
        {
          kind: 'select',
          id: 'align',
          label: 'align',
          defaultValue: NodeTextAlign.Middle,
          options: [
            { value: NodeTextAlign.Start, label: 'Start' },
            { value: NodeTextAlign.Middle, label: 'Middle' },
            { value: NodeTextAlign.End, label: 'End' },
          ],
        },
        { kind: 'range', id: 'fontSize', label: 'font.size', defaultValue: 14, min: 10, max: 24, step: 1 },
        {
          kind: 'range',
          id: 'lineHeight',
          label: 'lineHeight',
          defaultValue: 1.2,
          min: 0.8,
          max: 2,
          step: 0.1,
        },
        {
          kind: 'range',
          id: 'maxTextWidth',
          label: 'maxTextWidth',
          defaultValue: 96,
          min: 48,
          max: 144,
          step: 8,
        },
      ],
    },
    {
      label: 'Node labels',
      controls: [
        { kind: 'switch', id: 'showLabel', label: 'Show label', defaultValue: true },
        {
          kind: 'select',
          id: 'labelPosition',
          label: 'labelPosition',
          defaultValue: 'top',
          options: [
            { value: 'top', label: 'Top' },
            { value: 'right', label: 'Right' },
            { value: 'bottom', label: 'Bottom' },
            { value: 'left', label: 'Left' },
          ],
          visibleWhen: { controlId: 'showLabel', oneOf: [true] },
        },
        {
          kind: 'range',
          id: 'labelDistance',
          label: 'labelDistance',
          defaultValue: 14,
          min: 4,
          max: 28,
          step: 2,
          visibleWhen: { controlId: 'showLabel', oneOf: [true] },
        },
        {
          kind: 'switch',
          id: 'labelPin',
          label: 'labelPin',
          defaultValue: true,
          visibleWhen: { controlId: 'showLabel', oneOf: [true] },
        },
        {
          kind: 'color',
          id: 'labelTextColor',
          label: 'labelTextColor',
          defaultValue: '#475569',
          visibleWhen: { controlId: 'showLabel', oneOf: [true] },
        },
      ],
    },
    {
      label: 'Effects',
      controls: [
        {
          kind: 'select',
          id: 'shadow',
          label: 'shadow',
          defaultValue: ShadowPreset.Md,
          options: [
            { value: ShadowPreset.None, label: 'None' },
            { value: ShadowPreset.Sm, label: 'sm' },
            { value: ShadowPreset.Md, label: 'md' },
            { value: ShadowPreset.Lg, label: 'lg' },
            { value: ShadowPreset.Xl, label: 'xl' },
          ],
        },
        {
          kind: 'select',
          id: 'blendMode',
          label: 'blendMode',
          defaultValue: BlendMode.Normal,
          options: [
            { value: BlendMode.Normal, label: 'normal' },
            { value: BlendMode.Multiply, label: 'multiply' },
            { value: BlendMode.Screen, label: 'screen' },
            { value: BlendMode.Overlay, label: 'overlay' },
          ],
        },
      ],
    },
  ],
});

/** Stable documentation contract for the node-and-text playground */
export const previewControlContract = {
  controls: builtinNodeTextControls,
  canonicalValues: {
    padding: 8,
    cornerRadius: 8,
    rotate: 0,
    minimumSize: 64,
    scale: 1,
    textColor: '#1e3a8a',
    align: NodeTextAlign.Middle,
    fontSize: 14,
    lineHeight: 1.2,
    maxTextWidth: 96,
    showLabel: true,
    labelPosition: 'top',
    labelDistance: 14,
    labelPin: true,
    labelTextColor: '#475569',
    shadow: ShadowPreset.Md,
    blendMode: BlendMode.Normal,
  },
  presets: [
    {
      id: 'card',
      label: 'Info card',
      values: {
        padding: 8,
        cornerRadius: 8,
        rotate: 0,
        minimumSize: 64,
        scale: 1,
        textColor: '#1e3a8a',
        align: NodeTextAlign.Middle,
        fontSize: 14,
        lineHeight: 1.2,
        maxTextWidth: 96,
        showLabel: true,
        labelPosition: 'top',
        labelDistance: 14,
        labelPin: true,
        labelTextColor: '#475569',
        shadow: ShadowPreset.Md,
        blendMode: BlendMode.Normal,
      },
    },
    {
      id: 'tilted',
      label: 'Tilted emphasis',
      values: {
        padding: 12,
        cornerRadius: 16,
        rotate: -18,
        minimumSize: 84,
        scale: 1.1,
        textColor: '#7c2d12',
        align: NodeTextAlign.Middle,
        fontSize: 16,
        lineHeight: 1.3,
        maxTextWidth: 112,
        showLabel: false,
        labelPosition: 'top',
        labelDistance: 14,
        labelPin: true,
        labelTextColor: '#475569',
        shadow: ShadowPreset.Xl,
        blendMode: BlendMode.Multiply,
      },
    },
  ],
  relatedApis: [
    'PointMark.padding',
    'PointMark.cornerRadius',
    'PointMark.rotate',
    'PointMark.minimumSize',
    'PointMark.scale',
    'PointMark.textColor',
    'PointMark.align',
    'PointMark.font',
    'PointMark.lineHeight',
    'PointMark.maxTextWidth',
    'PointMark.label',
    'PointMark.labelPosition',
    'PointMark.labelDistance',
    'PointMark.labelPin',
    'PointMark.labelTextColor',
    'PointMark.shadow',
    'PointMark.blendMode',
  ],
} satisfies PreviewControlContract;
