import { BlendMode, NodeTextAlign, ShadowPreset } from '@retikz/core';

import type { PreviewControlContract } from '@/modules/docs/preview';

import { definePreviewControls } from '@/modules/docs/preview';

import { nodeTextRows } from './builtin-node-text.data';

/** 节点、文本、标签与效果通道的中文属性面板 */
export const builtinNodeTextControls = definePreviewControls({
  presentation: 'panel',
  title: '节点与文本通道',
  defaultSize: 38,
  sections: [
    {
      label: '数据',
      defaultCollapsed: true,
      controls: [
        {
          kind: 'table',
          id: 'rows',
          label: '节点与文本数据',
          rows: nodeTextRows,
          columns: [{ key: 'x' }, { key: 'nodeY' }, { key: 'textY' }, { key: 'word' }, { key: 'tag' }],
        },
      ],
    },
    {
      label: '节点几何',
      controls: [
        { kind: 'range', id: 'padding', label: '内边距', defaultValue: 18, min: 0, max: 36, step: 1 },
        {
          kind: 'range',
          id: 'cornerRadius',
          label: '圆角半径',
          defaultValue: 8,
          min: 0,
          max: 24,
          step: 1,
        },
        { kind: 'range', id: 'rotate', label: '旋转角度', defaultValue: 0, min: -30, max: 30, step: 1 },
        {
          kind: 'range',
          id: 'minimumSize',
          label: '最小尺寸',
          defaultValue: 36,
          min: 0,
          max: 108,
          step: 4,
        },
        { kind: 'range', id: 'scale', label: '缩放比例', defaultValue: 1, min: 0.7, max: 1.4, step: 0.1 },
      ],
    },
    {
      label: '节点内文本',
      controls: [
        { kind: 'color', id: 'textColor', label: '文字颜色', defaultValue: '#1e3a8a' },
        {
          kind: 'select',
          id: 'align',
          label: '文字对齐',
          defaultValue: NodeTextAlign.Middle,
          options: [
            { value: NodeTextAlign.Start, label: '左对齐' },
            { value: NodeTextAlign.Middle, label: '居中' },
            { value: NodeTextAlign.End, label: '右对齐' },
          ],
        },
        { kind: 'range', id: 'fontSize', label: '字号', defaultValue: 14, min: 10, max: 24, step: 1 },
        {
          kind: 'range',
          id: 'lineHeight',
          label: '行高',
          defaultValue: 18,
          min: 12,
          max: 32,
          step: 1,
        },
        {
          kind: 'range',
          id: 'maxTextWidth',
          label: '最大文字宽度',
          defaultValue: 96,
          min: 48,
          max: 144,
          step: 8,
        },
      ],
    },
    {
      label: '节点标签',
      controls: [
        { kind: 'switch', id: 'showLabel', label: '显示外侧标签', defaultValue: true },
        {
          kind: 'select',
          id: 'labelPosition',
          label: '标签位置',
          defaultValue: 'top',
          options: [
            { value: 'top', label: '上' },
            { value: 'right', label: '右' },
            { value: 'bottom', label: '下' },
            { value: 'left', label: '左' },
          ],
          visibleWhen: { controlId: 'showLabel', oneOf: [true] },
        },
        {
          kind: 'range',
          id: 'labelDistance',
          label: '标签距离',
          defaultValue: 14,
          min: 4,
          max: 28,
          step: 2,
          visibleWhen: { controlId: 'showLabel', oneOf: [true] },
        },
        {
          kind: 'switch',
          id: 'labelPin',
          label: '显示引线',
          defaultValue: true,
          visibleWhen: { controlId: 'showLabel', oneOf: [true] },
        },
        {
          kind: 'color',
          id: 'labelTextColor',
          label: '标签文字颜色',
          defaultValue: '#475569',
          visibleWhen: { controlId: 'showLabel', oneOf: [true] },
        },
      ],
    },
    {
      label: '效果',
      controls: [
        {
          kind: 'select',
          id: 'shadow',
          label: '阴影',
          defaultValue: ShadowPreset.Md,
          options: [
            { value: ShadowPreset.None, label: '无' },
            { value: ShadowPreset.Sm, label: '小' },
            { value: ShadowPreset.Md, label: '中' },
            { value: ShadowPreset.Lg, label: '大' },
            { value: ShadowPreset.Xl, label: '超大' },
          ],
        },
        {
          kind: 'select',
          id: 'blendMode',
          label: '混合模式',
          defaultValue: BlendMode.Normal,
          options: [
            { value: BlendMode.Normal, label: '正常' },
            { value: BlendMode.Multiply, label: '正片叠底' },
            { value: BlendMode.Screen, label: '滤色' },
            { value: BlendMode.Overlay, label: '叠加' },
          ],
        },
      ],
    },
  ],
});

/** 节点与文本 playground 的稳定文档契约 */
export const previewControlContract = {
  controls: builtinNodeTextControls,
  canonicalValues: {
    padding: 18,
    cornerRadius: 8,
    rotate: 0,
    minimumSize: 36,
    scale: 1,
    textColor: '#1e3a8a',
    align: NodeTextAlign.Middle,
    fontSize: 14,
    lineHeight: 18,
    maxTextWidth: 96,
    showLabel: true,
    labelPosition: 'top',
    labelDistance: 14,
    labelPin: true,
    labelTextColor: '#475569',
    shadow: ShadowPreset.Md,
    blendMode: BlendMode.Normal,
  },
  presets: [
    {
      id: 'card',
      label: '信息卡片',
      values: {
        padding: 18,
        cornerRadius: 8,
        rotate: 0,
        minimumSize: 36,
        scale: 1,
        textColor: '#1e3a8a',
        align: NodeTextAlign.Middle,
        fontSize: 14,
        lineHeight: 18,
        maxTextWidth: 96,
        showLabel: true,
        labelPosition: 'top',
        labelDistance: 14,
        labelPin: true,
        labelTextColor: '#475569',
        shadow: ShadowPreset.Md,
        blendMode: BlendMode.Normal,
      },
    },
    {
      id: 'tilted',
      label: '旋转强调',
      values: {
        padding: 24,
        cornerRadius: 16,
        rotate: -18,
        minimumSize: 48,
        scale: 1.1,
        textColor: '#7c2d12',
        align: NodeTextAlign.Middle,
        fontSize: 16,
        lineHeight: 22,
        maxTextWidth: 112,
        showLabel: false,
        labelPosition: 'top',
        labelDistance: 14,
        labelPin: true,
        labelTextColor: '#475569',
        shadow: ShadowPreset.Xl,
        blendMode: BlendMode.Multiply,
      },
    },
  ],
  relatedApis: [
    'PointMark.padding',
    'PointMark.cornerRadius',
    'PointMark.rotate',
    'PointMark.minimumSize',
    'PointMark.scale',
    'PointMark.textColor',
    'PointMark.align',
    'PointMark.font',
    'PointMark.lineHeight',
    'PointMark.maxTextWidth',
    'PointMark.label',
    'PointMark.labelPosition',
    'PointMark.labelDistance',
    'PointMark.labelPin',
    'PointMark.labelTextColor',
    'PointMark.shadow',
    'PointMark.blendMode',
  ],
} satisfies PreviewControlContract;
