/** 一维定位后的来源节点、汇聚目标与关系 */
export const coordinate1DCompositionRows = [
  {
    thingX: 0.8,
    thingId: 'toothbrush',
    thingLabel: 'Toothbrush',
    practiceX: 2.4,
    practiceId: 'care',
    practiceLabel: 'Care',
    practiceGlyph: '●',
    relationColor: '#0f766e',
  },
  {
    thingX: 1.85,
    thingId: 'towel',
    thingLabel: 'Towel',
    practiceX: 2.4,
    practiceId: 'care',
    practiceLabel: 'Care',
    practiceGlyph: '●',
    relationColor: '#0f766e',
  },
  {
    thingX: 2.9,
    thingId: 'comb',
    thingLabel: 'Comb',
    practiceX: 2.4,
    practiceId: 'care',
    practiceLabel: 'Care',
    practiceGlyph: '●',
    relationColor: '#0f766e',
  },
  {
    thingX: 3.95,
    thingId: 'soap',
    thingLabel: 'Soap',
    practiceX: 2.4,
    practiceId: 'care',
    practiceLabel: 'Care',
    practiceGlyph: '●',
    relationColor: '#0f766e',
  },
  {
    thingX: 4.7,
    thingId: 'novel',
    thingLabel: 'Novel',
    practiceX: 6.5,
    practiceId: 'reading',
    practiceLabel: 'Reading',
    practiceGlyph: '●',
    relationColor: '#7c3aed',
  },
  {
    thingX: 5.75,
    thingId: 'magazine',
    thingLabel: 'Magazine',
    practiceX: 6.5,
    practiceId: 'reading',
    practiceLabel: 'Reading',
    practiceGlyph: '●',
    relationColor: '#7c3aed',
  },
  {
    thingX: 6.8,
    thingId: 'tablet',
    thingLabel: 'Tablet',
    practiceX: 6.5,
    practiceId: 'reading',
    practiceLabel: 'Reading',
    practiceGlyph: '●',
    relationColor: '#7c3aed',
  },
  {
    thingX: 7.85,
    thingId: 'bookmark',
    thingLabel: 'Bookmark',
    practiceX: 6.5,
    practiceId: 'reading',
    practiceLabel: 'Reading',
    practiceGlyph: '●',
    relationColor: '#7c3aed',
  },
  {
    thingX: 8.6,
    thingId: 'pan',
    thingLabel: 'Pan',
    practiceX: 10.65,
    practiceId: 'cooking',
    practiceLabel: 'Cooking',
    practiceGlyph: '●',
    relationColor: '#c2410c',
  },
  {
    thingX: 9.65,
    thingId: 'recipe',
    thingLabel: 'Recipe',
    practiceX: 10.65,
    practiceId: 'cooking',
    practiceLabel: 'Cooking',
    practiceGlyph: '●',
    relationColor: '#c2410c',
  },
  {
    thingX: 10.7,
    thingId: 'board',
    thingLabel: 'Board',
    practiceX: 10.65,
    practiceId: 'cooking',
    practiceLabel: 'Cooking',
    practiceGlyph: '●',
    relationColor: '#c2410c',
  },
  {
    thingX: 11.75,
    thingId: 'cutlery',
    thingLabel: 'Cutlery',
    practiceX: 10.65,
    practiceId: 'cooking',
    practiceLabel: 'Cooking',
    practiceGlyph: '●',
    relationColor: '#c2410c',
  },
];
