/** 一维定位后的来源节点、汇聚目标与关系 */
export const coordinate1DCompositionRows = [
  {
    thingX: 0.8,
    thingId: 'toothbrush',
    thingLabel: '牙刷',
    practiceX: 2.4,
    practiceId: 'care',
    practiceLabel: '护理',
    practiceGlyph: '●',
    relationColor: '#0f766e',
  },
  {
    thingX: 1.85,
    thingId: 'towel',
    thingLabel: '毛巾',
    practiceX: 2.4,
    practiceId: 'care',
    practiceLabel: '护理',
    practiceGlyph: '●',
    relationColor: '#0f766e',
  },
  {
    thingX: 2.9,
    thingId: 'comb',
    thingLabel: '梳子',
    practiceX: 2.4,
    practiceId: 'care',
    practiceLabel: '护理',
    practiceGlyph: '●',
    relationColor: '#0f766e',
  },
  {
    thingX: 3.95,
    thingId: 'soap',
    thingLabel: '香皂',
    practiceX: 2.4,
    practiceId: 'care',
    practiceLabel: '护理',
    practiceGlyph: '●',
    relationColor: '#0f766e',
  },
  {
    thingX: 4.7,
    thingId: 'novel',
    thingLabel: '小说',
    practiceX: 6.5,
    practiceId: 'reading',
    practiceLabel: '阅读',
    practiceGlyph: '●',
    relationColor: '#7c3aed',
  },
  {
    thingX: 5.75,
    thingId: 'magazine',
    thingLabel: '杂志',
    practiceX: 6.5,
    practiceId: 'reading',
    practiceLabel: '阅读',
    practiceGlyph: '●',
    relationColor: '#7c3aed',
  },
  {
    thingX: 6.8,
    thingId: 'tablet',
    thingLabel: '平板',
    practiceX: 6.5,
    practiceId: 'reading',
    practiceLabel: '阅读',
    practiceGlyph: '●',
    relationColor: '#7c3aed',
  },
  {
    thingX: 7.85,
    thingId: 'bookmark',
    thingLabel: '书签',
    practiceX: 6.5,
    practiceId: 'reading',
    practiceLabel: '阅读',
    practiceGlyph: '●',
    relationColor: '#7c3aed',
  },
  {
    thingX: 8.6,
    thingId: 'pan',
    thingLabel: '锅具',
    practiceX: 10.65,
    practiceId: 'cooking',
    practiceLabel: '烹饪',
    practiceGlyph: '●',
    relationColor: '#c2410c',
  },
  {
    thingX: 9.65,
    thingId: 'recipe',
    thingLabel: '菜谱',
    practiceX: 10.65,
    practiceId: 'cooking',
    practiceLabel: '烹饪',
    practiceGlyph: '●',
    relationColor: '#c2410c',
  },
  {
    thingX: 10.7,
    thingId: 'board',
    thingLabel: '砧板',
    practiceX: 10.65,
    practiceId: 'cooking',
    practiceLabel: '烹饪',
    practiceGlyph: '●',
    relationColor: '#c2410c',
  },
  {
    thingX: 11.75,
    thingId: 'cutlery',
    thingLabel: '餐具',
    practiceX: 10.65,
    practiceId: 'cooking',
    practiceLabel: '烹饪',
    practiceGlyph: '●',
    relationColor: '#c2410c',
  },
];
