export const regionalSales: Array<Record<string, string | number>> = [
  { region: 'north', channel: 'online', month: 1, revenue: 58 },
  { region: 'north', channel: 'online', month: 2, revenue: 66 },
  { region: 'north', channel: 'online', month: 3, revenue: 73 },
  { region: 'north', channel: 'online', month: 4, revenue: 88 },
  { region: 'south', channel: 'online', month: 1, revenue: 42 },
  { region: 'south', channel: 'online', month: 2, revenue: 54 },
  { region: 'south', channel: 'online', month: 3, revenue: 63 },
  { region: 'south', channel: 'online', month: 4, revenue: 71 },
  { region: 'west', channel: 'online', month: 1, revenue: 76 },
  { region: 'west', channel: 'online', month: 2, revenue: 69 },
  { region: 'west', channel: 'online', month: 3, revenue: 81 },
  { region: 'west', channel: 'online', month: 4, revenue: 92 },
  { region: 'north', channel: 'store', month: 1, revenue: 44 },
  { region: 'north', channel: 'store', month: 2, revenue: 52 },
  { region: 'north', channel: 'store', month: 3, revenue: 61 },
  { region: 'north', channel: 'store', month: 4, revenue: 67 },
  { region: 'south', channel: 'store', month: 1, revenue: 36 },
  { region: 'south', channel: 'store', month: 2, revenue: 41 },
  { region: 'south', channel: 'store', month: 3, revenue: 49 },
  { region: 'south', channel: 'store', month: 4, revenue: 58 },
  { region: 'west', channel: 'store', month: 1, revenue: 51 },
  { region: 'west', channel: 'store', month: 2, revenue: 56 },
  { region: 'west', channel: 'store', month: 3, revenue: 65 },
  { region: 'west', channel: 'store', month: 4, revenue: 72 },
];
