import type { PreviewControlContract } from '@/modules/docs/preview';

import { definePreviewControls } from '@/modules/docs/preview';

/** Grid 完整参数空间的中文属性面板 */
export const gridPlaygroundControls = definePreviewControls({
  presentation: 'panel',
  title: 'Grid 参数',
  sections: [
    {
      label: '范围与格线',
      controls: [
        {
          kind: 'point',
          id: 'boundsStart',
          label: '起始',
          defaultValue: [60, 50],
          min: [24, 24],
          max: [80, 64],
          step: 4,
        },
        {
          kind: 'point',
          id: 'boundsEnd',
          label: '终止',
          defaultValue: [340, 230],
          min: [184, 124],
          max: [360, 244],
          step: 10,
        },
        {
          kind: 'select',
          id: 'spacingMode',
          label: '间距模式',
          defaultValue: 'uniform',
          options: [
            { value: 'uniform', label: '统一间距' },
            { value: 'axis', label: '分轴间距' },
          ],
        },
        {
          kind: 'range',
          id: 'spacing',
          label: '统一间距',
          defaultValue: 24,
          min: 10,
          max: 48,
          step: 2,
          visibleWhen: { controlId: 'spacingMode', oneOf: ['uniform'] },
        },
        {
          kind: 'range',
          id: 'spacingX',
          label: '横向间距',
          defaultValue: 24,
          min: 10,
          max: 48,
          step: 2,
          visibleWhen: { controlId: 'spacingMode', oneOf: ['axis'] },
        },
        {
          kind: 'range',
          id: 'spacingY',
          label: '纵向间距',
          defaultValue: 18,
          min: 10,
          max: 48,
          step: 2,
          visibleWhen: { controlId: 'spacingMode', oneOf: ['axis'] },
        },
      ],
    },
    {
      label: '对齐与网格线',
      controls: [
        { kind: 'switch', id: 'originEnabled', label: '自定义原点', defaultValue: false },
        {
          kind: 'range',
          id: 'originX',
          label: '原点 x',
          defaultValue: 200,
          min: 0,
          max: 400,
          step: 4,
          visibleWhen: { controlId: 'originEnabled', oneOf: [true] },
        },
        {
          kind: 'range',
          id: 'originY',
          label: '原点 y',
          defaultValue: 140,
          min: 0,
          max: 280,
          step: 4,
          visibleWhen: { controlId: 'originEnabled', oneOf: [true] },
        },
        { kind: 'switch', id: 'includeBoundary', label: '包含边界', defaultValue: false },
        { kind: 'color', id: 'lineStroke', label: '普通线颜色', defaultValue: '#d3d3d3' },
        { kind: 'range', id: 'lineStrokeWidth', label: '普通线宽度', defaultValue: 1, min: 0.5, max: 4, step: 0.5 },
        { kind: 'switch', id: 'lineDashed', label: '普通线虚线', defaultValue: false },
        { kind: 'range', id: 'lineOpacity', label: '普通线透明度', defaultValue: 1, min: 0.1, max: 1, step: 0.1 },
      ],
    },
    {
      label: '主线',
      controls: [
        { kind: 'switch', id: 'majorEnabled', label: '启用主线', defaultValue: true },
        {
          kind: 'range',
          id: 'majorEvery',
          label: '主线间隔',
          defaultValue: 4,
          min: 2,
          max: 8,
          step: 1,
          visibleWhen: { controlId: 'majorEnabled', oneOf: [true] },
        },
        {
          kind: 'range',
          id: 'majorOffset',
          label: '主线偏移',
          defaultValue: 0,
          min: -4,
          max: 4,
          step: 1,
          visibleWhen: { controlId: 'majorEnabled', oneOf: [true] },
        },
        {
          kind: 'color',
          id: 'majorStroke',
          label: '主线颜色',
          defaultValue: '#808080',
          visibleWhen: { controlId: 'majorEnabled', oneOf: [true] },
        },
        {
          kind: 'range',
          id: 'majorStrokeWidth',
          label: '主线宽度',
          defaultValue: 1.5,
          min: 0.5,
          max: 5,
          step: 0.5,
          visibleWhen: { controlId: 'majorEnabled', oneOf: [true] },
        },
        {
          kind: 'switch',
          id: 'majorDashed',
          label: '主线虚线',
          defaultValue: false,
          visibleWhen: { controlId: 'majorEnabled', oneOf: [true] },
        },
        {
          kind: 'range',
          id: 'majorOpacity',
          label: '主线透明度',
          defaultValue: 1,
          min: 0.1,
          max: 1,
          step: 0.1,
          visibleWhen: { controlId: 'majorEnabled', oneOf: [true] },
        },
      ],
    },
    {
      label: '边框',
      controls: [
        { kind: 'switch', id: 'borderEnabled', label: '启用边框', defaultValue: false },
        {
          kind: 'range',
          id: 'borderPadding',
          label: '边框外扩',
          defaultValue: 8,
          min: 0,
          max: 16,
          step: 2,
          visibleWhen: { controlId: 'borderEnabled', oneOf: [true] },
        },
        {
          kind: 'select',
          id: 'borderOrder',
          label: '绘制顺序',
          defaultValue: 'front',
          options: [
            { value: 'behind', label: '置后' },
            { value: 'front', label: '置前' },
          ],
          visibleWhen: { controlId: 'borderEnabled', oneOf: [true] },
        },
        {
          kind: 'switch',
          id: 'borderExtendLines',
          label: '延伸网格线',
          defaultValue: false,
          visibleWhen: { controlId: 'borderEnabled', oneOf: [true] },
        },
        {
          kind: 'color',
          id: 'borderStroke',
          label: '边框颜色',
          defaultValue: '#696969',
          visibleWhen: { controlId: 'borderEnabled', oneOf: [true] },
        },
        {
          kind: 'range',
          id: 'borderStrokeWidth',
          label: '边框宽度',
          defaultValue: 1.5,
          min: 0.5,
          max: 5,
          step: 0.5,
          visibleWhen: { controlId: 'borderEnabled', oneOf: [true] },
        },
        {
          kind: 'switch',
          id: 'borderDashed',
          label: '边框虚线',
          defaultValue: false,
          visibleWhen: { controlId: 'borderEnabled', oneOf: [true] },
        },
        {
          kind: 'range',
          id: 'borderOpacity',
          label: '边框透明度',
          defaultValue: 1,
          min: 0.1,
          max: 1,
          step: 0.1,
          visibleWhen: { controlId: 'borderEnabled', oneOf: [true] },
        },
        {
          kind: 'color',
          id: 'borderFill',
          label: '填充颜色',
          defaultValue: '#ffffff',
          visibleWhen: { controlId: 'borderEnabled', oneOf: [true] },
        },
        {
          kind: 'range',
          id: 'borderFillOpacity',
          label: '填充透明度',
          defaultValue: 0,
          min: 0,
          max: 0.5,
          step: 0.05,
          visibleWhen: { controlId: 'borderEnabled', oneOf: [true] },
        },
      ],
    },
  ],
});

/** 当前 Grid playground 的稳定文档契约 */
export const previewControlContract = {
  controls: gridPlaygroundControls,
  canonicalValues: {
    boundsStart: [60, 50],
    boundsEnd: [340, 230],
    spacingMode: 'uniform',
    spacing: 24,
    spacingX: 24,
    spacingY: 18,
    originEnabled: false,
    originX: 200,
    originY: 140,
    includeBoundary: false,
    lineStroke: '#d3d3d3',
    lineStrokeWidth: 1,
    lineDashed: false,
    lineOpacity: 1,
    majorEnabled: true,
    majorEvery: 4,
    majorOffset: 0,
    majorStroke: '#808080',
    majorStrokeWidth: 1.5,
    majorDashed: false,
    majorOpacity: 1,
    borderEnabled: false,
    borderPadding: 8,
    borderOrder: 'front',
    borderExtendLines: false,
    borderStroke: '#696969',
    borderStrokeWidth: 1.5,
    borderDashed: false,
    borderOpacity: 1,
    borderFill: '#ffffff',
    borderFillOpacity: 0,
  },
  relatedApis: ['Grid.bounds', 'Grid.spacing', 'Grid.origin', 'Grid.lines', 'Grid.major', 'Grid.border'],
} satisfies PreviewControlContract;
