import type { PreviewControlContract } from '@/modules/docs/preview';

import { definePreviewControls } from '@/modules/docs/preview';

/** Grid 完整参数空间的英文属性面板 */
export const gridPlaygroundEnControls = definePreviewControls({
  presentation: 'panel',
  title: 'Grid parameters',
  sections: [
    {
      label: 'Bounds and spacing',
      controls: [
        {
          kind: 'point',
          id: 'boundsMin',
          label: 'bounds.min',
          defaultValue: [60, 50],
          min: [24, 24],
          max: [80, 64],
          step: 4,
        },
        {
          kind: 'point',
          id: 'boundsMax',
          label: 'bounds.max',
          defaultValue: [340, 230],
          min: [184, 124],
          max: [360, 244],
          step: 10,
        },
        {
          kind: 'select',
          id: 'spacingMode',
          label: 'spacing',
          defaultValue: 'uniform',
          options: [
            { value: 'uniform', label: 'Uniform' },
            { value: 'axis', label: 'Per axis' },
          ],
        },
        {
          kind: 'range',
          id: 'spacing',
          label: 'Uniform spacing',
          defaultValue: 24,
          min: 10,
          max: 48,
          step: 2,
          visibleWhen: { controlId: 'spacingMode', oneOf: ['uniform'] },
        },
        {
          kind: 'range',
          id: 'spacingX',
          label: 'spacing.x',
          defaultValue: 24,
          min: 10,
          max: 48,
          step: 2,
          visibleWhen: { controlId: 'spacingMode', oneOf: ['axis'] },
        },
        {
          kind: 'range',
          id: 'spacingY',
          label: 'spacing.y',
          defaultValue: 18,
          min: 10,
          max: 48,
          step: 2,
          visibleWhen: { controlId: 'spacingMode', oneOf: ['axis'] },
        },
      ],
    },
    {
      label: 'Alignment and lines',
      controls: [
        { kind: 'switch', id: 'originEnabled', label: 'Custom origin', defaultValue: false },
        {
          kind: 'range',
          id: 'originX',
          label: 'origin.x',
          defaultValue: 200,
          min: 0,
          max: 400,
          step: 4,
          visibleWhen: { controlId: 'originEnabled', oneOf: [true] },
        },
        {
          kind: 'range',
          id: 'originY',
          label: 'origin.y',
          defaultValue: 140,
          min: 0,
          max: 280,
          step: 4,
          visibleWhen: { controlId: 'originEnabled', oneOf: [true] },
        },
        {
          kind: 'select',
          id: 'direction',
          label: 'Direction',
          defaultValue: 'both',
          options: [
            { value: 'both', label: 'Both' },
            { value: 'vertical', label: 'Vertical only' },
            { value: 'horizontal', label: 'Horizontal only' },
          ],
        },
        { kind: 'switch', id: 'includeBoundary', label: 'includeBoundary', defaultValue: false },
        { kind: 'color', id: 'lineStroke', label: 'Line color', defaultValue: '#d3d3d3' },
        { kind: 'range', id: 'lineStrokeWidth', label: 'Line width', defaultValue: 1, min: 0.5, max: 4, step: 0.5 },
        { kind: 'switch', id: 'lineDashed', label: 'Dashed lines', defaultValue: false },
        { kind: 'range', id: 'lineOpacity', label: 'Line opacity', defaultValue: 1, min: 0.1, max: 1, step: 0.1 },
      ],
    },
    {
      label: 'Major lines',
      controls: [
        { kind: 'switch', id: 'majorEnabled', label: 'Enable major', defaultValue: true },
        {
          kind: 'range',
          id: 'majorEvery',
          label: 'major.every',
          defaultValue: 4,
          min: 2,
          max: 8,
          step: 1,
          visibleWhen: { controlId: 'majorEnabled', oneOf: [true] },
        },
        {
          kind: 'range',
          id: 'majorOffset',
          label: 'major.offset',
          defaultValue: 0,
          min: -4,
          max: 4,
          step: 1,
          visibleWhen: { controlId: 'majorEnabled', oneOf: [true] },
        },
        {
          kind: 'color',
          id: 'majorStroke',
          label: 'Major color',
          defaultValue: '#808080',
          visibleWhen: { controlId: 'majorEnabled', oneOf: [true] },
        },
        {
          kind: 'range',
          id: 'majorStrokeWidth',
          label: 'Major width',
          defaultValue: 1.5,
          min: 0.5,
          max: 5,
          step: 0.5,
          visibleWhen: { controlId: 'majorEnabled', oneOf: [true] },
        },
        {
          kind: 'switch',
          id: 'majorDashed',
          label: 'Dashed majors',
          defaultValue: false,
          visibleWhen: { controlId: 'majorEnabled', oneOf: [true] },
        },
        {
          kind: 'range',
          id: 'majorOpacity',
          label: 'Major opacity',
          defaultValue: 1,
          min: 0.1,
          max: 1,
          step: 0.1,
          visibleWhen: { controlId: 'majorEnabled', oneOf: [true] },
        },
      ],
    },
    {
      label: 'Border',
      controls: [
        { kind: 'switch', id: 'borderEnabled', label: 'Enable border', defaultValue: false },
        {
          kind: 'range',
          id: 'borderPadding',
          label: 'border.padding',
          defaultValue: 8,
          min: 0,
          max: 16,
          step: 2,
          visibleWhen: { controlId: 'borderEnabled', oneOf: [true] },
        },
        {
          kind: 'select',
          id: 'borderOrder',
          label: 'border.order',
          defaultValue: 'front',
          options: [
            { value: 'behind', label: 'Behind' },
            { value: 'front', label: 'Front' },
          ],
          visibleWhen: { controlId: 'borderEnabled', oneOf: [true] },
        },
        {
          kind: 'switch',
          id: 'borderExtendLines',
          label: 'extendLines',
          defaultValue: false,
          visibleWhen: { controlId: 'borderEnabled', oneOf: [true] },
        },
        {
          kind: 'color',
          id: 'borderStroke',
          label: 'Border color',
          defaultValue: '#696969',
          visibleWhen: { controlId: 'borderEnabled', oneOf: [true] },
        },
        {
          kind: 'range',
          id: 'borderStrokeWidth',
          label: 'Border width',
          defaultValue: 1.5,
          min: 0.5,
          max: 5,
          step: 0.5,
          visibleWhen: { controlId: 'borderEnabled', oneOf: [true] },
        },
        {
          kind: 'switch',
          id: 'borderDashed',
          label: 'Dashed border',
          defaultValue: false,
          visibleWhen: { controlId: 'borderEnabled', oneOf: [true] },
        },
        {
          kind: 'range',
          id: 'borderOpacity',
          label: 'Border opacity',
          defaultValue: 1,
          min: 0.1,
          max: 1,
          step: 0.1,
          visibleWhen: { controlId: 'borderEnabled', oneOf: [true] },
        },
        {
          kind: 'color',
          id: 'borderFill',
          label: 'Fill color',
          defaultValue: '#ffffff',
          visibleWhen: { controlId: 'borderEnabled', oneOf: [true] },
        },
        {
          kind: 'range',
          id: 'borderFillOpacity',
          label: 'Fill opacity',
          defaultValue: 0,
          min: 0,
          max: 0.5,
          step: 0.05,
          visibleWhen: { controlId: 'borderEnabled', oneOf: [true] },
        },
      ],
    },
  ],
});

/** 当前 Grid playground 的稳定英文文档契约 */
export const previewControlContract = {
  controls: gridPlaygroundEnControls,
  canonicalValues: {
    boundsMin: [60, 50],
    boundsMax: [340, 230],
    spacingMode: 'uniform',
    spacing: 24,
    spacingX: 24,
    spacingY: 18,
    originEnabled: false,
    originX: 200,
    originY: 140,
    direction: 'both',
    includeBoundary: false,
    lineStroke: '#d3d3d3',
    lineStrokeWidth: 1,
    lineDashed: false,
    lineOpacity: 1,
    majorEnabled: true,
    majorEvery: 4,
    majorOffset: 0,
    majorStroke: '#808080',
    majorStrokeWidth: 1.5,
    majorDashed: false,
    majorOpacity: 1,
    borderEnabled: false,
    borderPadding: 8,
    borderOrder: 'front',
    borderExtendLines: false,
    borderStroke: '#696969',
    borderStrokeWidth: 1.5,
    borderDashed: false,
    borderOpacity: 1,
    borderFill: '#ffffff',
    borderFillOpacity: 0,
  },
  relatedApis: [
    'Grid.bounds',
    'Grid.spacing',
    'Grid.origin',
    'Grid.lines.vertical',
    'Grid.lines.horizontal',
    'Grid.lines.includeBoundary',
    'Grid.lines.style',
    'Grid.major',
    'Grid.border',
  ],
} satisfies PreviewControlContract;
