export const measurements = [
  { group: 'A', value: 3.1 },
  { group: 'A', value: 3.4 },
  { group: 'A', value: 3.6 },
  { group: 'A', value: 3.9 },
  { group: 'A', value: 4.1 },
  { group: 'A', value: 4.4 },
  { group: 'A', value: 4.8 },
  { group: 'A', value: 5.2 },
  { group: 'A', value: 5.5 },
  { group: 'B', value: 5.1 },
  { group: 'B', value: 5.5 },
  { group: 'B', value: 5.9 },
  { group: 'B', value: 6.4 },
  { group: 'B', value: 6.9 },
  { group: 'B', value: 7.1 },
  { group: 'B', value: 7.4 },
  { group: 'B', value: 7.8 },
  { group: 'B', value: 8.2 },
];
