// @retikz/plot-react public API barrel.
export type {
  AxisProps,
  BuildPlotSpecOptions,
  CoordinateInput,
  DatumLabelProps,
  FacetDimensionInput,
  FacetProps,
  FieldName,
  IntervalMarkProps,
  LegendProps,
  MarkTransformShortcutContext,
  MarkTransformShortcutDefinition,
  PathMarkProps,
  PointMarkProps,
  PositionScaleType,
  ReferenceMarkProps,
  RelationMarkProps,
  ResolveLabelMap,
  ScaffoldProps,
  ScaleDimension,
  ScaleProps,
  TrackProps,
  TransformProps,
} from './components';
export {
  Axis,
  buildPlotSpec,
  Facet,
  IntervalMark,
  Legend,
  PathMark,
  PointMark,
  ReferenceMark,
  RelationMark,
  resolveLabelOf,
  Scaffold,
  Scale,
  Track,
  Transform,
} from './components';
export type { PlotDslProps, PlotPanelProps, PlotProps, PlotSpecProps } from './Plot';
export { Plot } from './Plot';
