// @retikz/plot-react public API barrel.
export type {
  AxisProps,
  BuildPlotSpecOptions,
  CaptionLabelProps,
  CoordinateInput,
  DatumLabelProps,
  FacetDimensionInput,
  FacetProps,
  FieldName,
  IntervalMarkProps,
  LegendProps,
  MarkTransformShortcutContext,
  MarkTransformShortcutDefinition,
  PathMarkProps,
  PlotLabelText,
  PlotTextLabelProps,
  PointMarkProps,
  PositionScaleType,
  ReferenceMarkProps,
  RelationMarkProps,
  ResolveLabelMap,
  ScaffoldProps,
  ScaleDimension,
  ScaleProps,
  TitleLabelProps,
  TrackProps,
  TransformProps,
} from './components';
export {
  Axis,
  buildPlotSpec,
  CaptionLabel,
  Facet,
  IntervalMark,
  Legend,
  PathMark,
  PointMark,
  ReferenceMark,
  RelationMark,
  resolveLabelOf,
  Scaffold,
  Scale,
  TitleLabel,
  Track,
  Transform,
} from './components';
export type { PlotDslProps, PlotLineageProps, PlotPanelProps, PlotProps, PlotSpecProps } from './Plot';
export { Plot } from './Plot';
export { resolvePlotLineage } from './plot-runtime';
