export const accountRows: Array<Record<string, string | number>> = [
  { product: 'core', tier: 'free', month: 1, accounts: 18 },
  { product: 'core', tier: 'free', month: 2, accounts: 23 },
  { product: 'core', tier: 'free', month: 3, accounts: 29 },
  { product: 'core', tier: 'free', month: 4, accounts: 35 },
  { product: 'core', tier: 'pro', month: 1, accounts: 105 },
  { product: 'core', tier: 'pro', month: 2, accounts: 126 },
  { product: 'core', tier: 'pro', month: 3, accounts: 148 },
  { product: 'core', tier: 'pro', month: 4, accounts: 171 },
  { product: 'growth', tier: 'free', month: 1, accounts: 6 },
  { product: 'growth', tier: 'free', month: 2, accounts: 8 },
  { product: 'growth', tier: 'free', month: 3, accounts: 9 },
  { product: 'growth', tier: 'free', month: 4, accounts: 12 },
  { product: 'platform', tier: 'free', month: 1, accounts: 31 },
  { product: 'platform', tier: 'free', month: 2, accounts: 36 },
  { product: 'platform', tier: 'free', month: 3, accounts: 41 },
  { product: 'platform', tier: 'free', month: 4, accounts: 45 },
  { product: 'platform', tier: 'pro', month: 1, accounts: 220 },
  { product: 'platform', tier: 'pro', month: 2, accounts: 248 },
  { product: 'platform', tier: 'pro', month: 3, accounts: 281 },
  { product: 'platform', tier: 'pro', month: 4, accounts: 306 },
];
