/** Table 主题 token 的 canonical key */
export const TableThemeToken = {
  CellBackgroundFill: 'cell.background.fill',
  CellBackgroundFillOpacity: 'cell.background.fillOpacity',
  CellContentColor: 'cell.content.color',
  CellContentFontFamily: 'cell.content.font.family',
  CellContentFontWeight: 'cell.content.font.weight',
  ColumnHeaderBackgroundFill: 'columnHeader.background.fill',
  ColumnHeaderBackgroundFillOpacity: 'columnHeader.background.fillOpacity',
  ColumnHeaderContentColor: 'columnHeader.content.color',
  ColumnHeaderContentFontFamily: 'columnHeader.content.font.family',
  ColumnHeaderContentFontWeight: 'columnHeader.content.font.weight',
  TableBorderTop: 'table.border.top',
  TableBorderRight: 'table.border.right',
  TableBorderBottom: 'table.border.bottom',
  TableBorderLeft: 'table.border.left',
  TableBorderHorizontal: 'table.border.horizontal',
  TableBorderVertical: 'table.border.vertical',
  ColumnHeaderBorderBottom: 'columnHeader.border.bottom',
  DataCategorical: 'data.categorical',
  DataSequential: 'data.sequential',
} as const;
