import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { readSchemaDescriptions } from '../schema-reference/descriptions';
import { translateBlockApiReference } from './block.en';
import type { ApiReferenceLanguage, ApiReferencePackageConfig } from './tex';
import { createApiReferenceMdx } from './tex';

const repositoryRoot = path.resolve(import.meta.dirname, '../../../..');
const schemaNames = [
  'BlockSchema',
  'BlockHeaderSchema',
  'BlockSectionSchema',
  'BlockRowSchema',
  'BlockTextSchema',
  'CodeBlockPropsSchema',
  'CodeParameterSchema',
  'CodeSignatureSchema',
  'CodePropertySchema',
  'CodeMethodSchema',
  'CodeLogicSchema',
];
/** Block 与代码实体的公开入口切片 */
export const blockApiConfigs: ReadonlyArray<ApiReferencePackageConfig> = [
  {
    owner: 'graph-react',
    symbols: [
      'Block',
      'BlockProps',
      'BlockHeader',
      'BlockHeaderProps',
      'BlockSection',
      'BlockSectionProps',
      'BlockRow',
      'BlockRowProps',
    ],
    pairs: [
      ['Block', 'BlockProps'],
      ['BlockHeader', 'BlockHeaderProps'],
      ['BlockSection', 'BlockSectionProps'],
      ['BlockRow', 'BlockRowProps'],
    ],
  },
  {
    owner: 'graph-vanilla',
    symbols: [
      'block',
      'BlockInputEmbedProps',
      'blockHeader',
      'BlockHeaderInputEmbedProps',
      'blockSection',
      'BlockSectionInputEmbedProps',
      'blockRow',
      'BlockRowInputEmbedProps',
      'InputBlock',
      'InputBlockHeader',
      'InputBlockSection',
      'InputBlockRow',
      'BlockInputEmbedAdapter',
      'BlockHeaderInputEmbedAdapter',
      'BlockSectionInputEmbedAdapter',
      'BlockRowInputEmbedAdapter',
      'normalizeBlock',
      'normalizeBlockHeader',
      'normalizeBlockSection',
      'normalizeBlockRow',
      'createGraphVanillaAdapters',
    ],
    pairs: [
      ['block', 'BlockInputEmbedProps'],
      ['blockHeader', 'BlockHeaderInputEmbedProps'],
      ['blockSection', 'BlockSectionInputEmbedProps'],
      ['blockRow', 'BlockRowInputEmbedProps'],
      ['normalizeBlock', 'InputBlock'],
      ['normalizeBlockHeader', 'InputBlockHeader'],
      ['normalizeBlockSection', 'InputBlockSection'],
      ['normalizeBlockRow', 'InputBlockRow'],
    ],
  },
  {
    owner: 'graph',
    symbols: [
      'IRBlock',
      'IRBlockHeader',
      'IRBlockSection',
      'IRBlockRow',
      'IRBlockText',
      'createBlock',
      'BlockCreateOptions',
      'createBlockHeader',
      'BlockHeaderCreateOptions',
      'createBlockSection',
      'BlockSectionCreateOptions',
      'createBlockRow',
      'BlockRowCreateOptions',
      'IRCodeBlock',
      'IRCodeBlockProps',
      'IRCodeParameter',
      'IRCodeSignature',
      'IRCodeProperty',
      'IRCodeMethod',
      'IRCodeLogic',
      'defineCodeBlock',
      'CodeBlockDefinition',
      'CodeBlockComposeContext',
      'createCodeBlockContribution',
      'CodeBlockTokens',
      'GraphDefinitionOptions',
      'createGraphDefinitions',
      'createGraphProviders',
    ],
    pairs: [
      ['createBlock', 'BlockCreateOptions'],
      ['createBlockHeader', 'BlockHeaderCreateOptions'],
      ['createBlockSection', 'BlockSectionCreateOptions'],
      ['createBlockRow', 'BlockRowCreateOptions'],
    ],
  },
].map(({ owner, symbols, pairs }): ApiReferencePackageConfig => ({
  packageName: `@retikz/${owner}`,
  packageDirectory: `packages/schematic/${owner}`,
  tsconfigPath: path.resolve(repositoryRoot, `packages/schematic/${owner}/tsconfig.json`),
  entries: [
    {
      source: path.resolve(repositoryRoot, `packages/schematic/${owner}/src/index.ts`),
      title: { zh: `\`@retikz/${owner}\``, en: `\`@retikz/${owner}\`` },
      symbols,
      symbolPairs: pairs.map(([entry, input]) => [entry, input]),
    },
  ],
  schemaLocalizations: Object.fromEntries(
    schemaNames.map(name => [
      name,
      {
        descriptions: readSchemaDescriptions(
          path.resolve(
            repositoryRoot,
            'apps/docs/src/modules/docs/contents/schematic/graph/block/schema-reference/index.zh.mdx',
          ),
          name,
        ),
      },
    ]),
  ),
  translate: translateBlockApiReference,
}));
/** 从公开声明生成 Block 双语参考 */
export const writeBlockApiReferenceMdx = async (outputDirectory: string): Promise<void> => {
  mkdirSync(outputDirectory, { recursive: true });
  for (const lang of ['zh', 'en'] as const satisfies ReadonlyArray<ApiReferenceLanguage>) {
    const sections: Array<string> = [];
    for (const config of blockApiConfigs) sections.push(await createApiReferenceMdx(config, lang));
    writeFileSync(
      path.resolve(outputDirectory, `generated.${lang}.mdx`),
      `{/* Generated by pnpm generate:api-reference. Do not edit manually. */}\n\n${sections.join('\n\n')}\n`,
      'utf8',
    );
  }
};
