import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import * as schemas from '@retikz/diagram/branch';

import { readSchemaDescriptions } from '../schema-reference/descriptions';
import { assertBranchApiReferenceTranslated, translateBranchApiReference } from './branch.en';
import { createSchemaLocalizationResolver, resolveStandardSchemaLocalization } from './standard-schema';
import { createApiReferenceMdx } from './tex';
import type { ApiReferencePackageConfig } from './tex';

const root = path.resolve(import.meta.dirname, '../../../..');

const schemaPage = path.join(
  root,
  'apps/docs/src/modules/docs/contents/schematic/diagram/branch/schema-reference/index.zh.mdx',
);

const localize = createSchemaLocalizationResolver([
  ...(
    [
      'BranchDiagramSchema',
      'BranchNodeSchema',
      'BranchSchema',
      'BranchLayoutIntentSchema',
      'BranchNodeLayoutSchema',
    ] as const
  ).map(name => ({
    schema: schemas[name],
    localizations: { zh: { descriptions: readSchemaDescriptions(schemaPage, name) } },
  })),
  {
    schema: schemas.BranchDiagramArtifactSchema,
    localizations: {
      zh: {
        descriptions: {
          layout: '选中的布局定义',
          frame: '完整图示边界',
          regions: '标题、说明、绘图区与图例的区域边界',
          nodes: '共享节点的唯一几何',
          segments: '唯一有向相邻段的参考路由',
          branches: '各分支对应的相邻段索引',
        },
      },
    },
  },
]);

/** Branch 三个公开子路径的源码投影配置 */
export const branchApiConfigs: ReadonlyArray<ApiReferencePackageConfig> = [
  {
    owner: 'diagram-react',
    symbols: [
      'BranchDiagram',
      'BranchDiagramProps',
      'BranchDiagramLayoutHostProps',
      'BranchNode',
      'BranchNodeProps',
      'Branch',
      'BranchProps',
    ],
    pairs: [
      ['BranchDiagram', 'BranchDiagramProps'],
      ['BranchNode', 'BranchNodeProps'],
      ['Branch', 'BranchProps'],
    ] as const,
  },
  {
    owner: 'diagram-vanilla',
    symbols: [
      'branchDiagram',
      'BranchDiagramInputEmbedProps',
      'normalizeBranchDiagram',
      'InputBranchDiagram',
      'InputBranchNode',
      'InputBranch',
      'BranchDiagramInputEmbedAdapter',
      'createBranchDiagramVanillaAdapters',
      'BranchDiagramEmbedKind',
      'branchDiagramDefinitionOptionsOf',
    ],
    pairs: [
      ['branchDiagram', 'BranchDiagramInputEmbedProps'],
      ['normalizeBranchDiagram', 'InputBranchDiagram'],
    ] as const,
  },
  {
    owner: 'diagram',
    symbols: [
      'defineBranchLayout',
      'BranchLayoutDefinition',
      'BranchLayoutInput',
      'BranchLayoutNodeInput',
      'BranchLayoutOutput',
      'BranchLayoutNodeOutput',
      'BranchLayoutSegmentOutput',
      'BranchDiagramDefinitionOptions',
      'LanesBranchLayoutDefinition',
      'BranchDiagramProviderKey',
      'createBranchDiagramProvider',
      'createBranchDiagramProviderContribution',
      'IRBranchDiagram',
      'IRBranchNode',
      'IRBranch',
      'IRBranchLayoutIntent',
      'BranchDiagramArtifact',
    ],
    pairs: [] as const,
  },
].map(({ owner, symbols, pairs }): ApiReferencePackageConfig => ({
  packageName: `@retikz/${owner}`,
  packageDirectory: `packages/schematic/${owner}`,
  tsconfigPath: path.join(root, `packages/schematic/${owner}/tsconfig.json`),
  entries: [
    {
      source: path.join(root, `packages/schematic/${owner}/src/branch/index.ts`),
      title: { zh: `\`@retikz/${owner}/branch\``, en: `\`@retikz/${owner}/branch\`` },
      symbols,
      symbolPairs: pairs,
    },
  ],
  translate: translateBranchApiReference,
  resolveSchemaLocalization: schema => localize(schema) ?? resolveStandardSchemaLocalization(schema),
}));

/** 生成 Branch 双语 API include */
export const writeBranchApiReferenceMdx = async (outputDirectory: string): Promise<void> => {
  mkdirSync(outputDirectory, { recursive: true });

  for (const lang of ['zh', 'en'] as const) {
    const sections: Array<string> = [];

    for (const config of branchApiConfigs) sections.push(await createApiReferenceMdx(config, lang));
    if (lang === 'en') assertBranchApiReferenceTranslated();
    writeFileSync(
      path.join(outputDirectory, `generated.${lang}.mdx`),
      `{/* Generated by pnpm generate:api-reference. Do not edit manually. */}\n\n${sections.join('\n\n')}\n`,
      'utf8',
    );
  }
};
