import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import * as schemas from '@retikz/data';

import { readSchemaDescriptions } from '../schema-reference/descriptions';
import { assertDataTransformApiReferenceTranslated, translateDataTransformApiReference } from './data-transform.en';
import { createSchemaLocalizationResolver } from './standard-schema';
import { createApiReferenceMdx } from './tex';
import type { ApiReferencePackageConfig } from './tex';

const root = path.resolve(import.meta.dirname, '../../../..');
const schemaPage = path.join(
  root,
  'apps/docs/src/modules/docs/contents/viz/data/transform/schema-reference/index.zh.mdx',
);
const schemaNames = [
  'DataExecutionSchema',
  'DataTransformDeclarationSchema',
  'DataTransformSchema',
  'ExternalTransformSchema',
  'SortTransformSchema',
  'SortParamsSchema',
  'SummarizeTransformSchema',
  'SummarizeParamsSchema',
  'SelectTransformSchema',
  'SelectParamsSchema',
  'AnnotateTransformSchema',
  'AnnotateParamsSchema',
  'StackTransformSchema',
  'StackParamsSchema',
  'BinTransformSchema',
  'BinParamsSchema',
  'NormalizeTransformSchema',
  'NormalizeParamsSchema',
  'DeriveIntervalTransformSchema',
  'DeriveIntervalParamsSchema',
  'RelateTransformSchema',
  'RelateParamsSchema',
  'JitterTransformSchema',
  'JitterParamsSchema',
  'DensityTransformSchema',
  'DensityParamsSchema',
  'SmoothTransformSchema',
  'SmoothParamsSchema',
  'AnnotateSelectorSchema',
  'EndpointProjectionSchema',
  'PairMeasureOperationSchema',
  'DensityBandwidthSchema',
  'ReducerOperationSchema',
  'ReducerMetricsSchema',
  'QuantileBandReducerOperationSchema',
  'QuantileBandOutputsSchema',
  'QuantileBandPointOutputSchema',
  'QuantileBandWhiskerSchema',
  'SelectorOperationSchema',
  'OrderBySchema',
  'OutsideQuantileBandSelectorOperationSchema',
  'OutsideQuantileBandBoundarySchema',
  'RegressionMethodSchema',
] as const;
const localize = createSchemaLocalizationResolver(
  schemaNames.map(name => ({
    schema: schemas[name === 'DataTransformSchema' ? 'TransformSchema' : name],
    localizations: { zh: { descriptions: readSchemaDescriptions(schemaPage, name) } },
  })),
);

/** 数据变换公开参考生成 */
export const dataTransformApiReferenceConfig: ApiReferencePackageConfig = {
  packageName: '@retikz/data',
  packageDirectory: 'packages/viz/data',
  tsconfigPath: path.join(root, 'packages/viz/data/tsconfig.json'),
  entries: [
    {
      source: path.join(root, 'packages/viz/data/src/index.ts'),
      title: { zh: '`@retikz/data`', en: '`@retikz/data`' },
      symbols: [
        'IRDataSortTransform',
        'IRDataReducerOperation',
        'IRDataReducerMetrics',
        'IRDataQuantileBandReducerOperation',
        'IRDataSelectorOperation',
        'IRDataOutsideQuantileBandSelectorOperation',
        'IRDataOrderBy',
        'IRDataSummarizeTransform',
        'IRDataSelectTransform',
        'IRDataAnnotateSelector',
        'IRDataAnnotateTransform',
        'IRDataBuiltinTransform',
        'IRDataTransform',
        'IRDataStackTransform',
        'IRDataBinTransform',
        'IRDataNormalizeTransform',
        'IRDataDeriveIntervalTransform',
        'IRDataEndpointProjection',
        'IRDataPairMeasureOperation',
        'IRDataRelateTransform',
        'IRDataJitterTransform',
        'IRDataDensityBandwidth',
        'IRDataDensityTransform',
        'IRDataSmoothTransform',
        'BuiltinDataTransform',
        'DataSortOrder',
        'BuiltinReducerOperationKind',

        'BuiltinSelectorOperationKind',

        'RowSelectorTie',

        'StackOffset',
        'PairMeasureOperationKind',
        'NormalizeBasis',
        'JitterAxis',
        'DensityBandwidthKind',
        'IRDataExecution',
        'IRDataTransformDeclaration',
        'IRRegressionMethod',
        'BuiltinRegressionMethod',

        'DataTransformPhase',
        'DataTransformBindingClass',
        'DataTransformFieldEffect',
        'DataTransformSchedule',
        'DataTransformOutputDescriptor',
        'DataTransformOutputModel',
        'TransformContext',
        'TransformSemanticContext',
        'TransformDefinition',
        'TransformDefinitionInput',
        'defineTransform',
        'AnyTransformDefinition',
        'TransformImplementation',
        'defineTransformImplementation',
        'AnyTransformImplementation',
        'AnySynchronousTransformImplementation',
        'extractTransformKind',
        'StatisticsReducerDefinition',
        'defineStatisticsReducer',
        'AnyStatisticsReducerDefinition',
        'RowSelection',
        'RowSelectorDefinition',
        'defineRowSelector',
        'AnyRowSelectorDefinition',
        'StatisticsReducerImplementation',
        'defineStatisticsReducerImplementation',
        'AnyStatisticsReducerImplementation',
        'AnySynchronousStatisticsReducerImplementation',
        'RowSelectorImplementation',
        'defineRowSelectorImplementation',
        'AnyRowSelectorImplementation',
        'AnySynchronousRowSelectorImplementation',
        'extractStatisticOperation',
        'RegressionPair',
        'RegressionModel',
        'RegressionDefinition',
        'defineRegression',
        'AnyRegressionDefinition',
        'RegressionImplementation',
        'defineRegressionImplementation',
        'AnyRegressionImplementation',
        'AnySynchronousRegressionImplementation',
        'extractRegressionKind',
        'RegressionResolution',
        'DataTransformModel',
        'DataTransformDependency',
        'DataTransformStage',
        'DataTransformResolution',
        'DataTransformResult',
        'DataTransformDiagnostic',
        'DataTransformStageInput',
        'DataTransformInputDescriptor',
        'DataTransformExecutionRequirements',
        'DataTransformRequestOptions',
        'DataTransformStageImplementation',
        'DataTransformStageSupport',
        'DataTransformImplementationProvider',
        'DataTransformProviderRegistration',
        'DataTransformExecutionOptions',
        'DataTransformExecution',
        'DataTransformPreparation',
        'DataTransformExecutor',
        'DataInputBinding',
        'DataInputBindings',
        'BUILTIN_TRANSFORMS',
        'BUILTIN_TRANSFORM_DEFINITIONS_BY_KIND',
        'BUILTIN_TRANSFORM_IMPLEMENTATIONS',
        'resolveTransformRegistry',
        'resolveTransformImplementationRegistry',
        'BUILTIN_STATISTICS_REDUCERS',
        'BUILTIN_STATISTICS_REDUCER_IMPLEMENTATIONS',
        'BUILTIN_ROW_SELECTORS',
        'BUILTIN_ROW_SELECTOR_IMPLEMENTATIONS',
        'resolveStatisticsReducerRegistry',
        'resolveStatisticsReducerImplementationRegistry',
        'resolveRowSelectorRegistry',
        'resolveRowSelectorImplementationRegistry',
        'BUILTIN_REGRESSIONS',
        'BUILTIN_REGRESSION_IMPLEMENTATIONS',
        'resolveRegressionRegistry',
        'resolveRegressionImplementationRegistry',
        'resolveRegression',
        'DataTransformResolveOptions',
        'resolveDataTransforms',
        'resolveDataTransformOutputModel',
        'resolveDataExecution',
        'ingestDataTransformResult',
        'describeDataTransformInput',
        'createDataTransformExecutor',
        'executeDataTransforms',
        'DEFAULT_TRANSFORM_CONTEXT',
        'ApplyTransformsOptions',
        'applyTransformsToDataView',
        'applyTransforms',
        'collectTransformFields',
        'ApplyTransformsWithLineageOptions',
        'ApplyTransformsWithLineageResult',
        'ApplyTransformsToDataViewWithLineageResult',
        'applyTransformsToDataViewWithLineage',
        'applyTransformsWithLineage',
      ],
    },
  ],
  translate: translateDataTransformApiReference,
  resolveSchemaLocalization: localize,
};

/** 数据变换公开参考生成 */
export const writeDataTransformApiReferenceMdx = async (outputDirectory: string): Promise<void> => {
  mkdirSync(outputDirectory, { recursive: true });
  for (const lang of ['zh', 'en'] as const) {
    const content = await createApiReferenceMdx(dataTransformApiReferenceConfig, lang);
    if (lang === 'en') assertDataTransformApiReferenceTranslated();
    writeFileSync(
      path.join(outputDirectory, `generated.${lang}.mdx`),
      `{/* Generated by pnpm generate:data-transform-api-reference. Do not edit manually. */}\n\n${content}\n`,
      'utf8',
    );
  }
};
