import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import * as schemas from '@retikz/data';

import { readSchemaDescriptions } from '../schema-reference/descriptions';
import { assertDataModelApiReferenceTranslated, translateDataModelApiReference } from './data-model.en';
import { createSchemaLocalizationResolver } from './standard-schema';
import { createApiReferenceMdx } from './tex';
import type { ApiReferencePackageConfig } from './tex';

const root = path.resolve(import.meta.dirname, '../../../..');
const schemaPage = path.join(root, 'apps/docs/src/modules/docs/contents/viz/data/model/schema-reference/index.zh.mdx');
const localize = createSchemaLocalizationResolver(
  (['DataReferenceSchema', 'FieldDefinitionSchema'] as const).map(name => ({
    schema: schemas[name],
    localizations: { zh: { descriptions: readSchemaDescriptions(schemaPage, name) } },
  })),
);

/** 数据模型公开入口的局部参考投影；不收录变换与编译实现 */
export const dataModelApiReferenceConfig: ApiReferencePackageConfig = {
  packageName: '@retikz/data',
  packageDirectory: 'packages/viz/data',
  tsconfigPath: path.join(root, 'packages/viz/data/tsconfig.json'),
  entries: [
    {
      source: path.join(root, 'packages/viz/data/src/index.ts'),
      title: { zh: '`@retikz/data`', en: '`@retikz/data`' },
      declarationOnlySymbols: ['ExternalRow', 'ExternalDatasets'],
      memberTypeLabels: { IRDataReference: { model: 'IRDataModel' } },
      symbols: [
        'IRDataReference',
        'IRDataModel',
        'IRDataFieldDefinition',
        'DataFieldType',
        'BuiltinDataFieldFormat',
        'FieldFormat',
        'ExternalRow',
        'ExternalDatasets',
        'ParsedFieldValue',
        'FieldFormatDefinition',
        'defineFieldFormat',
        'resolveFormatRegistry',
        'BUILTIN_FORMATS',
        'BuiltinFieldOrderMode',
        'FieldOrderContext',
        'FieldOrderDefinition',
        'defineFieldOrder',
        'resolveFieldOrderRegistry',
        'BUILTIN_FIELD_ORDERS',
        'resolveCategoryDomain',
        'ResolveField',
        'FieldResolution',
      ],
    },
  ],
  translate: translateDataModelApiReference,
  resolveSchemaLocalization: localize,
};

/** 从公开声明生成数据模型中英文参考 */
export const writeDataModelApiReferenceMdx = async (outputDirectory: string): Promise<void> => {
  mkdirSync(outputDirectory, { recursive: true });
  for (const lang of ['zh', 'en'] as const) {
    const content = await createApiReferenceMdx(dataModelApiReferenceConfig, lang);
    if (lang === 'en') assertDataModelApiReferenceTranslated();
    writeFileSync(
      path.join(outputDirectory, `generated.${lang}.mdx`),
      `{/* Generated by pnpm generate:api-reference. Do not edit manually. */}\n\n${content}\n`,
      'utf8',
    );
  }
};
