import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { pathSchemaDescriptions } from '../schema-reference/path';
import { translateDrawApiReference } from './draw.en';
import type { ApiReferenceLanguage, ApiReferencePackageConfig } from './tex';
import { createApiReferenceMdx } from './tex';

const repositoryRoot = path.resolve(import.meta.dirname, '../../../..');

/** 绘制参考按宿主入口、作者输入和扩展契约筛选真实公共导出 */
export const drawApiReferenceConfigs: ReadonlyArray<ApiReferencePackageConfig> = [
  {
    packageName: '@retikz/react',
    packageDirectory: 'packages/kernel/react',
    tsconfigPath: path.resolve(repositoryRoot, 'packages/kernel/react/tsconfig.json'),
    entries: [
      {
        source: path.resolve(repositoryRoot, 'packages/kernel/react/src/index.ts'),
        title: { zh: 'React 组件', en: 'React components' },
        symbols: [
          'Draw',
          'DrawProps',
          'Path',
          'PathProps',
          'Step',
          'StepProps',
          'MoveStepProps',
          'LineStepProps',
          'AxisLineStepProps',
          'FoldStepProps',
          'CycleStepProps',
          'CurveStepProps',
          'CubicStepProps',
          'BendStepProps',
          'ArcStepProps',
          'CirclePathStepProps',
          'EllipsePathStepProps',
          'RectangleStepProps',
          'SmoothStepProps',
          'GeneratorStepProps',
        ],
      },
    ],
    translate: translateDrawApiReference,
    schemaPackageName: '@retikz/core',
    schemaLocalizations: { PathBaseSchema: { descriptions: pathSchemaDescriptions } },
  },
  {
    packageName: '@retikz/vanilla',
    packageDirectory: 'packages/kernel/vanilla',
    tsconfigPath: path.resolve(repositoryRoot, 'packages/kernel/vanilla/tsconfig.json'),
    entries: [
      {
        source: path.resolve(repositoryRoot, 'packages/kernel/vanilla/src/index.ts'),
        title: { zh: 'Vanilla 作者输入', en: 'Vanilla authoring input' },
        symbols: ['path', 'InputPath', 'InputStep'],
      },
    ],
    translate: translateDrawApiReference,
    schemaPackageName: '@retikz/core',
    schemaLocalizations: { PathBaseSchema: { descriptions: pathSchemaDescriptions } },
  },
  {
    packageName: '@retikz/core',
    packageDirectory: 'packages/kernel/core',
    tsconfigPath: path.resolve(repositoryRoot, 'packages/kernel/core/tsconfig.json'),
    entries: [
      {
        source: path.resolve(repositoryRoot, 'packages/kernel/core/src/index.ts'),
        title: { zh: '路径写法与扩展契约', en: 'Path syntax and extension contracts' },
        symbols: [
          'DrawWay',
          'WayDSL',
          'WayItem',
          'definePathGenerator',
          'PathGeneratorDefinition',
          'PathGeneratorGenerateContext',
          'definePathKind',
          'PathKindDefinition',
          'PathKindCompileContext',
          'PathKindCompileResult',
          'defineArrow',
          'ArrowDefinition',
          'ArrowEmitContext',
        ],
      },
    ],
    translate: translateDrawApiReference,
    schemaPackageName: '@retikz/core',
    schemaLocalizations: { PathBaseSchema: { descriptions: pathSchemaDescriptions } },
  },
];

/** 从三个公开包入口生成绘制家族的查询视图 */
export const createDrawApiReferenceMdx = async (lang: ApiReferenceLanguage): Promise<string> => {
  const sections: Array<string> = [];
  for (const config of drawApiReferenceConfigs) sections.push(await createApiReferenceMdx(config, lang));
  return sections.join('\n\n');
};

/** 写出绘制双语参考，字段和声明继续由通用生成器拥有 */
export const writeDrawApiReferenceMdx = async (outputDirectory: string): Promise<void> => {
  mkdirSync(outputDirectory, { recursive: true });
  for (const lang of ['zh', 'en'] as const) {
    const source = await createDrawApiReferenceMdx(lang);
    writeFileSync(
      path.resolve(outputDirectory, `generated.${lang}.mdx`),
      `{/* Generated by pnpm generate:api-reference. Do not edit manually. */}\n\n${source}\n`,
      'utf8',
    );
  }
};
