import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { translateEntityApiReference } from './entity.en';
import type { ApiReferenceLanguage, ApiReferencePackageConfig } from './tex';
import { createApiReferenceMdx } from './tex';

const repositoryRoot = path.resolve(import.meta.dirname, '../../../..');

const entityMemberValueSets = {
  role: { name: 'EntityRole', open: true },
  status: { name: 'GraphStatus' },
} as const;

const entityMemberTypeLabels = { animations: 'Array<IRAnimationTrack>' } as const;

/** Entity 组件参考的公开入口切片，不收录编译内部类型 */
export const entityApiConfigs: ReadonlyArray<ApiReferencePackageConfig> = [
  { owner: 'graph-react', symbols: ['Entity', 'EntityProps'] },
  {
    owner: 'graph-vanilla',
    symbols: [
      'entity',
      'InputEntity',
      'EntityInputEmbedProps',
      'EntityInputEmbedAdapter',
      'normalizeEntity',
      'createGraphVanillaAdapters',
    ],
  },
  {
    owner: 'graph',
    symbols: [
      'EntityRole',
      'EntityRoleValue',
      'GraphStatus',
      'GraphStatusValue',
      'EntitySchema',
      'EntityRoleSchema',
      'IRGraphEntity',
      'createEntity',
      'EntityCreateOptions',
      'defineEntityRole',
      'EntityRoleDefinition',
      'defineEntityKind',
      'EntityKindDefinition',
      'defineEntityPredicate',
      'EntityPredicateDefinitionInput',
      'EntityPredicateDefinition',
      'GraphDefinitionOptions',
      'createGraphDefinitions',
      'createGraphProviders',
    ],
  },
].map(({ owner, symbols }): ApiReferencePackageConfig => ({
  packageName: `@retikz/${owner}`,
  packageDirectory: `packages/schematic/${owner}`,
  tsconfigPath: path.resolve(repositoryRoot, `packages/schematic/${owner}/tsconfig.json`),
  entries: [
    {
      source: path.resolve(repositoryRoot, `packages/schematic/${owner}/src/index.ts`),
      title: { zh: `\`@retikz/${owner}\``, en: `\`@retikz/${owner}\`` },
      symbols,
      fullMemberSymbols: owner === 'graph-react' ? ['EntityProps'] : undefined,
      memberValueSets:
        owner === 'graph-react'
          ? { EntityProps: entityMemberValueSets }
          : owner === 'graph-vanilla'
            ? {
                EntityInputEmbedProps: entityMemberValueSets,
                InputEntity: entityMemberValueSets,
              }
            : { IRGraphEntity: entityMemberValueSets },
      memberTypeLabels:
        owner === 'graph-react'
          ? { EntityProps: entityMemberTypeLabels }
          : owner === 'graph-vanilla'
            ? {
                EntityInputEmbedProps: entityMemberTypeLabels,
                InputEntity: entityMemberTypeLabels,
              }
            : { IRGraphEntity: entityMemberTypeLabels },
    },
  ],
  schemaReferences: {
    EntitySchema: '/schematic/graph/entity/schema-reference',
    EntityRoleSchema: '/schematic/graph/entity/schema-reference#entityroleschema',
  },
  translate: translateEntityApiReference,
}));

/** 按真实公开声明生成 Entity 双语参考 */
export const writeEntityApiReferenceMdx = async (outputDirectory: string): Promise<void> => {
  mkdirSync(outputDirectory, { recursive: true });
  for (const lang of ['zh', 'en'] as const satisfies ReadonlyArray<ApiReferenceLanguage>) {
    const sections: Array<string> = [];
    for (const config of entityApiConfigs) sections.push(await createApiReferenceMdx(config, lang));
    writeFileSync(
      path.resolve(outputDirectory, `generated.${lang}.mdx`),
      `{/* Generated by pnpm generate:api-reference. Do not edit manually. */}\n\n${sections.join('\n\n')}\n`,
      'utf8',
    );
  }
};
