import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { readSchemaDescriptions } from '../schema-reference/descriptions';
import { embedApiReferenceMdx } from './embedded-reference';
import { translateGroupApiReference } from './group.en';
import type { ApiReferencePackageConfig } from './tex';
import { createApiReferenceMdx } from './tex';

const repositoryRoot = path.resolve(import.meta.dirname, '../../../..');
/** Group 合页使用的公开 API */
export const groupApiConfigs: ReadonlyArray<ApiReferencePackageConfig> = [
  { owner: 'graph-react', symbols: ['Group', 'GroupProps'], pairs: [['Group', 'GroupProps']] },
  {
    owner: 'graph-vanilla',
    symbols: [
      'group',
      'GroupInputEmbedProps',
      'InputGroup',
      'GroupInputEmbedAdapter',
      'normalizeGroup',
      'createGraphVanillaAdapters',
    ],
    pairs: [
      ['group', 'GroupInputEmbedProps'],
      ['normalizeGroup', 'InputGroup'],
    ],
  },
  {
    owner: 'graph',
    symbols: [
      'IRGroup',
      'IRGroupCaption',
      'IRGroupCaptionText',
      'createGroup',
      'GroupCreateOptions',
      'GraphDefinitionOptions',
      'createGraphDefinitions',
      'createGraphProviders',
    ],
    pairs: [['createGroup', 'GroupCreateOptions']],
  },
].map(({ owner, symbols, pairs }): ApiReferencePackageConfig => ({
  packageName: `@retikz/${owner}`,
  packageDirectory: `packages/schematic/${owner}`,
  tsconfigPath: path.resolve(repositoryRoot, `packages/schematic/${owner}/tsconfig.json`),
  entries: [
    {
      source: path.resolve(repositoryRoot, `packages/schematic/${owner}/src/index.ts`),
      title: { zh: `\`@retikz/${owner}\``, en: `\`@retikz/${owner}\`` },
      symbols,
      symbolPairs: pairs.map(([entry, input]) => [entry, input]),
    },
  ],
  schemaLocalizations: Object.fromEntries(
    ['GroupSchema', 'GroupCaptionSchema', 'GroupCaptionTextSchema'].map(name => [
      name,
      {
        descriptions: readSchemaDescriptions(
          path.resolve(repositoryRoot, 'apps/docs/src/modules/docs/contents/schematic/graph/group/index.zh.mdx'),
          name,
        ),
      },
    ]),
  ),
  translate: translateGroupApiReference,
}));
/** 生成合页参考，包名作为正文标签展示 */
export const writeGroupApiReferenceMdx = async (outputDirectory: string): Promise<void> => {
  mkdirSync(outputDirectory, { recursive: true });
  for (const lang of ['zh', 'en'] as const) {
    const sections: Array<string> = [];
    for (const config of groupApiConfigs) sections.push(await createApiReferenceMdx(config, lang));
    const content = sections.map(embedApiReferenceMdx).join('\n\n');
    writeFileSync(
      path.resolve(outputDirectory, `generated.${lang}.mdx`),
      `{/* Generated by pnpm generate:api-reference. Do not edit manually. */}\n\n${content}\n`,
      'utf8',
    );
  }
};
