import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { translateLayoutApiReference } from './layout.en';
import type { ApiReferenceLanguage, ApiReferencePackageConfig } from './tex';
import { createApiReferenceMdx } from './tex';

const repositoryRoot = path.resolve(import.meta.dirname, '../../../..');

/** 复用对应 Schema 参考的中文字段说明 */
const layoutSchemaLocalizations = {
  SceneSchema: {
    descriptions: {
      version: '场景数据格式版本，当前必须为 1，与包版本号无关',
      type: '判别字段，标记该对象为 scene 根节点',
      theme: '场景根主题选择；只填写需要覆盖的 style 与 mode 字段',
      children: '有顺序的顶层子节点列表，允许空数组',
      viewBox: '显式指定取景范围；省略时根据内容范围与留白自动计算',
      animations: '场景根动画轨道，可包含 viewBox 取景动画；省略时不添加根动画轨道',
    },
  },
  ViewBoxSchema: {
    descriptions: {
      x: '左边界的场景坐标，必须为有限数，可以为负数',
      y: '上边界的场景坐标，必须为有限数，可以为负数',
      width: '宽度，使用场景坐标单位，必须为有限正数',
      height: '高度，使用场景坐标单位，必须为有限正数',
    },
  },
};

/** Layout 组件参考只收录公开入口中的组件与直接执行配置 */
const layoutConfig: ApiReferencePackageConfig = {
  packageName: '@retikz/react',
  packageDirectory: 'packages/kernel/react',
  tsconfigPath: path.resolve(repositoryRoot, 'packages/kernel/react/tsconfig.json'),
  entries: [
    {
      source: path.resolve(repositoryRoot, 'packages/kernel/react/src/index.ts'),
      title: { zh: '`@retikz/react`', en: '`@retikz/react`' },
      symbolPairs: [['Layout', 'LayoutProps']],
      symbols: [
        'Layout',
        'LayoutProps',
        'LayoutExtensions',
        'LayoutRuntimeMode',
        'LayoutRuntimeModeValue',
        'LayoutRuntimeOptions',
        'LayoutRetainedRuntimeOptions',
        'LayoutStaticRuntimeOptions',
      ],
    },
  ],
  translate: translateLayoutApiReference,
};

/** 按组件职责补齐作者输入和持久化数据契约 */
export const layoutApiReferenceConfigs: ReadonlyArray<ApiReferencePackageConfig> = [
  layoutConfig,
  {
    packageName: '@retikz/vanilla',
    packageDirectory: 'packages/kernel/vanilla',
    tsconfigPath: path.resolve(repositoryRoot, 'packages/kernel/vanilla/tsconfig.json'),
    entries: [
      {
        source: path.resolve(repositoryRoot, 'packages/kernel/vanilla/src/index.ts'),
        title: { zh: '`@retikz/vanilla`', en: '`@retikz/vanilla`' },
        symbols: ['scene', 'InputScene', 'InputSceneChildren', 'InputSceneLayers', 'layer', 'InputLayer'],
      },
    ],
    translate: translateLayoutApiReference,
    schemaPackageName: '@retikz/core',
    schemaLocalizations: { ...layoutSchemaLocalizations },
  },
  {
    packageName: '@retikz/core',
    packageDirectory: 'packages/kernel/core',
    tsconfigPath: path.resolve(repositoryRoot, 'packages/kernel/core/tsconfig.json'),
    entries: [
      {
        source: path.resolve(repositoryRoot, 'packages/kernel/core/src/index.ts'),
        title: { zh: '`@retikz/core`', en: '`@retikz/core`' },
        symbols: ['IRScene', 'IRViewBox'],
      },
    ],
    translate: translateLayoutApiReference,
    schemaPackageName: '@retikz/core',
    schemaLocalizations: { ...layoutSchemaLocalizations },
  },
];

/** 生成单个语言的组件 API 参考 */
export const createLayoutApiReferenceMdx = async (lang: ApiReferenceLanguage): Promise<string> => {
  const sections: Array<string> = [];
  for (const config of layoutApiReferenceConfigs) sections.push(await createApiReferenceMdx(config, lang));
  return sections.join('\n\n');
};

/** 写入组件的中英文 API include */
export const writeLayoutApiReferenceMdx = async (outputDirectory: string): Promise<void> => {
  mkdirSync(outputDirectory, { recursive: true });
  for (const lang of ['zh', 'en'] as const)
    writeFileSync(
      path.join(outputDirectory, `generated.${lang}.mdx`),
      `{/* Generated by pnpm generate:api-reference. Do not edit manually. */}\n\n${await createLayoutApiReferenceMdx(lang)}\n`,
      'utf8',
    );
};
