import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { layoutComponentSchemaLocalizations } from './layout-components-schema';
import { translateLayoutComponentApiReference } from './layout-components.en';
import type { ApiReferencePackageConfig } from './tex';
import { createApiReferenceMdx } from './tex';

const repositoryRoot = path.resolve(import.meta.dirname, '../../../..');

/** 三个布局组件的公开 API 局部视图；共享入口归 FlexLayout 页面 */
export const layoutComponentApiReferenceConfigs = (
  name: 'FlexLayout' | 'GridLayout' | 'OverlayLayout',
): Array<ApiReferencePackageConfig> => {
  const builder = name[0].toLowerCase() + name.slice(1);
  const shared = name === 'FlexLayout';
  const extras =
    name === 'FlexLayout'
      ? [
          'FlexLayoutDirection',
          'FlexLayoutDirection',
          'FlexLayoutWrap',
          'FlexLayoutWrap',
          'FlexMainDistribution',
          'LayoutAxisSizeKind',
          'LayoutAxisSizeInput',
          'LayoutSizeInput',
          'LayoutAlignment',
          'LayoutDistribution',
          'LayoutOverflow',
          'LayoutItemKind',
        ]
      : name === 'GridLayout'
        ? [
            'GridAutoFlow',
            'GridAutoFlow',
            'GridOverlap',
            'GridOverlap',
            'GridTrackInput',
            'GridTrackBreadthInput',
            'GridPlacementInput',
            'LayoutTrackArtifact',
            'LayoutTrackSourceKind',
            'LayoutTrackSourceKind',
            'GRID_LAYOUT_MAX_TRACKS_PER_AXIS',
          ]
        : [
            'OverlayPlacementKind',
            'OverlayPlacementKind',
            'OverlayPlacementInput',
            'LayoutSizeParticipation',
            'LayoutSizeParticipation',
          ];
  const owners = [
    {
      suffix: '-react',
      entry: '',
      symbols: [name, `${name}Props`, `${name}Item`, `${name}ItemProps`],
      pairs: [
        [name, `${name}Props`],
        [`${name}Item`, `${name}ItemProps`],
      ],
    },
    {
      suffix: '-vanilla',
      entry: '',
      symbols: [
        builder,
        `Input${name}`,
        `Input${name}Item`,
        `${name}InputEmbedAdapter`,
        ...(shared ? ['LayoutInputEmbedAdapters'] : []),
      ],
      pairs: [[builder, `Input${name}`]],
    },
    {
      suffix: '',
      entry: '',
      symbols: [
        `create${name}`,
        `${name}Input`,
        `IR${name}`,
        `${name}ItemInput`,
        `IR${name}Item`,
        `${name}Artifact`,
        `${name}Definition`,
        `${name}Provider`,
        ...extras,
      ],
      pairs: [[`create${name}`, `${name}Input`]],
    },
  ];
  return owners.map(owner => {
    const packageDirectory = `packages/library/layout${owner.suffix}`;
    const packageName = `@retikz/layout${owner.suffix}${owner.entry}`;
    return {
      packageName,
      packageDirectory,
      tsconfigPath: path.resolve(repositoryRoot, packageDirectory, 'tsconfig.json'),
      entries: [
        {
          source: path.resolve(repositoryRoot, packageDirectory, `src${owner.entry}/index.ts`),
          title: { zh: `\`${packageName}\``, en: `\`${packageName}\`` },
          symbols: owner.symbols,
          symbolPairs: owner.pairs.map(([entry, input]) => [entry, input] as const),
        },
      ],
      translate: translateLayoutComponentApiReference,
      schemaLocalizations: layoutComponentSchemaLocalizations,
    };
  });
};

/** 按公开导出生成双语参考，不将内部模块导出当作公开入口 */
export const writeLayoutComponentApiReferences = async (outputRoot: string): Promise<void> => {
  for (const name of ['FlexLayout', 'GridLayout', 'OverlayLayout'] as const) {
    const slug = name.replace('Layout', '-layout').toLowerCase();
    const directory = path.resolve(outputRoot, slug, 'api-reference/_includes');
    mkdirSync(directory, { recursive: true });
    for (const lang of ['zh', 'en'] as const) {
      const sections: Array<string> = [];
      for (const config of layoutComponentApiReferenceConfigs(name))
        sections.push(await createApiReferenceMdx(config, lang));
      writeFileSync(
        path.resolve(directory, `generated.${lang}.mdx`),
        `{/* Generated by pnpm generate:layout-api-reference. Do not edit manually. */}\n\n${sections.join('\n\n')}\n`,
        'utf8',
      );
    }
  }
};
