/** 布局输入与产物字段的中文说明；默认值仍从公开 Schema 读取 */
export const layoutComponentSchemaLocalizations = {
  OverlayLayoutInspectOptionsSchema: {
    descriptions: {
      bounds: 'false 关闭全部边界，true 恢复默认边界组合，对象形式逐项覆盖。',
      spacing: '独立控制 padding 与 margin 纹理。',
      overflow: '是否显示溢出阴影。',
      alignmentGuides: '是否显示对齐参考线。',
      labels: '是否显示辅助标签。',
      placements: '是否显示对齐或局部定位后的分配区域；默认开启。',
      anchors: '是否显示 positioned 子项的目标点与锚点；默认开启。',
      stacking: '是否显示稳定绘制顺序标签；默认关闭。',
    },
  },
  OverlayLayoutArtifactSchema: {
    descriptions: {
      kind: 'OverlayLayout 产物的判别字段。',
      container: '已求解的容器几何。',
      'container.allocationBounds': '容器最终的分配矩形。',
      'container.allocationBounds.x': '容器分配矩形的水平原点。',
      'container.allocationBounds.y': '容器分配矩形的垂直原点。',
      'container.allocationBounds.width': '容器分配矩形的非负宽度。',
      'container.allocationBounds.height': '容器分配矩形的非负高度。',
      'container.contentBounds': '扣除内边距后的容器内容矩形。',
      'container.contentBounds.x': '容器内容矩形的水平原点。',
      'container.contentBounds.y': '容器内容矩形的垂直原点。',
      'container.contentBounds.width': '容器内容矩形的非负宽度。',
      'container.contentBounds.height': '容器内容矩形的非负高度。',
      'container.visualBounds': '所有已平移子项视觉边界的并集。',
      'container.visualBounds.x': '视觉边界并集的水平原点。',
      'container.visualBounds.y': '视觉边界并集的垂直原点。',
      'container.visualBounds.width': '视觉边界并集的非负宽度。',
      'container.visualBounds.height': '视觉边界并集的非负高度。',
      'container.visibleBounds': '容器内仍可见的视觉并集；没有正面积时为 null。',
      items: '按作者声明顺序排列的子项结果。',
      paintOrder: '包含全部子项 key 的稳定绘制顺序。',
    },
  },
  OverlayLayoutSchema: {
    descriptions: {
      size: '包含内边距的容器双轴分配尺寸策略。',
      padding: '从容器分配区域到内容区域的内边距。',
      overflow: '视觉溢出保持可见或裁切到容器分配区域的策略。',
      namespace: 'Layout 排版能力的复合组件命名空间。',
      type: '确定性叠加布局的复合组件类型。',
      justifyItems: '对齐或定位子项默认继承的水平对齐方式。',
      alignItems: '对齐或定位子项默认继承的垂直对齐方式。',
      children: '按稳定标识顺序排列、由作者声明的叠加子项。',
    },
  },
  GridLayoutInspectOptionsSchema: {
    descriptions: {
      bounds: 'false 关闭全部边界，true 恢复默认边界组合，对象形式逐项覆盖。',
      spacing: '独立控制 padding 与 margin 纹理。',
      overflow: '是否显示溢出阴影。',
      alignmentGuides: '是否显示对齐参考线。',
      labels: '是否显示辅助标签。',
      tracks: '是否显示已求解的行列轨道；默认开启。',
      cells: '是否显示每个网格单元格；默认关闭。',
      gaps: '是否显示作者声明的固定轨道 gap；默认开启。',
      distributedSpace: '是否以虚线边界显示内容分布产生的正自由空间；内部不填色，默认开启。',
      spans: '是否显示跨轨道子项的范围；默认开启。',
    },
  },
  GridLayoutArtifactSchema: {
    descriptions: {
      kind: 'GridLayout 产物的判别字段。',
      container: '已求解的容器几何。',
      'container.allocationBounds': '容器最终的分配矩形。',
      'container.allocationBounds.x': '容器分配矩形的水平原点。',
      'container.allocationBounds.y': '容器分配矩形的垂直原点。',
      'container.allocationBounds.width': '容器分配矩形的非负宽度。',
      'container.allocationBounds.height': '容器分配矩形的非负高度。',
      'container.contentBounds': '扣除内边距后的容器内容矩形。',
      'container.contentBounds.x': '容器内容矩形的水平原点。',
      'container.contentBounds.y': '容器内容矩形的垂直原点。',
      'container.contentBounds.width': '容器内容矩形的非负宽度。',
      'container.contentBounds.height': '容器内容矩形的非负高度。',
      'container.visualBounds': '所有已平移子项视觉边界的并集。',
      'container.visualBounds.x': '视觉边界并集的水平原点。',
      'container.visualBounds.y': '视觉边界并集的垂直原点。',
      'container.visualBounds.width': '视觉边界并集的非负宽度。',
      'container.visualBounds.height': '视觉边界并集的非负高度。',
      'container.visibleBounds': '容器内仍可见的视觉并集；没有正面积时为 null。',
      items: '按作者声明顺序排列的子项结果。',
      columns: '按物理起点顺序排列的已求解列轨道。',
      rows: '按物理起点顺序排列的已求解行轨道。',
      spacing: '按 canonical 物理顺序排列的固定 gap 与内容分布区域。',
      'spacing.kind': '固定 gap 或内容对齐产生的自由空间。',
      'spacing.axis': '该间距区域的物理主轴。',
      'spacing.bounds': '当前容器分配坐标中的间距矩形。',
      'spacing.bounds.x': '间距矩形的水平原点。',
      'spacing.bounds.y': '间距矩形的垂直原点。',
      'spacing.bounds.width': '间距矩形的非负宽度；x 主轴时必须为正。',
      'spacing.bounds.height': '间距矩形的非负高度；y 主轴时必须为正。',
    },
  },
  GridLayoutSchema: {
    descriptions: {
      size: '包含内边距的容器双轴分配尺寸策略。',
      padding: '从容器分配区域到内容区域的内边距。',
      overflow: '视觉溢出保持可见或裁切到容器分配区域的策略。',
      namespace: 'Layout 排版能力的复合组件命名空间。',
      type: '确定性二维轨道布局的复合组件类型。',
      columns: '显式声明的物理列轨道。',
      rows: '显式声明的物理行轨道。',
      implicitColumn: '隐式列使用的轨道定义。',
      implicitRow: '隐式行使用的轨道定义。',
      autoFlow: '完全自动放置子项的非密集流向。',
      overlap: '完全显式放置的子项发生重叠时采用的策略。',
      columnGap: '列轨道之间的水平间距。',
      rowGap: '行轨道之间的垂直间距。',
      justifyItems: '网格区域内子项默认的水平对齐方式。',
      alignItems: '网格区域内子项默认的垂直对齐方式。',
      justifyContent: '已求解列组的水平分布方式。',
      alignContent: '已求解行组的垂直分布方式。',
      children: '按稳定绘制顺序排列、由作者声明的网格子项。',
    },
  },
  FlexLayoutInspectOptionsSchema: {
    descriptions: {
      bounds: 'false 关闭全部边界，true 恢复默认边界组合，对象形式逐项覆盖。',
      spacing: '独立控制 padding 与 margin 纹理。',
      overflow: '是否显示溢出阴影。',
      alignmentGuides: '是否显示对齐参考线。',
      labels: '是否显示辅助标签。',
      lines: '是否显示每条弹性布局行的区域；默认开启。',
      gaps: '是否显示作者声明的固定 gap；默认开启。',
      distributedSpace: '是否以虚线边界显示内容分布产生的正自由空间；内部不填色，默认开启。',
    },
  },
  FlexLayoutArtifactSchema: {
    descriptions: {
      kind: 'FlexLayout 产物的判别字段。',
      container: '已求解的容器几何。',
      'container.allocationBounds': '容器最终的分配矩形。',
      'container.allocationBounds.x': '容器分配矩形的水平原点。',
      'container.allocationBounds.y': '容器分配矩形的垂直原点。',
      'container.allocationBounds.width': '容器分配矩形的非负宽度。',
      'container.allocationBounds.height': '容器分配矩形的非负高度。',
      'container.contentBounds': '扣除内边距后的容器内容矩形。',
      'container.contentBounds.x': '容器内容矩形的水平原点。',
      'container.contentBounds.y': '容器内容矩形的垂直原点。',
      'container.contentBounds.width': '容器内容矩形的非负宽度。',
      'container.contentBounds.height': '容器内容矩形的非负高度。',
      'container.visualBounds': '所有已平移子项视觉边界的并集。',
      'container.visualBounds.x': '视觉边界并集的水平原点。',
      'container.visualBounds.y': '视觉边界并集的垂直原点。',
      'container.visualBounds.width': '视觉边界并集的非负宽度。',
      'container.visualBounds.height': '视觉边界并集的非负高度。',
      'container.visibleBounds': '容器内仍可见的视觉并集；没有正面积时为 null。',
      items: '按作者声明顺序排列的子项结果。',
      lines: '按最终物理交叉轴顺序排列的布局行。',
      spacing: '按 canonical 物理顺序排列的固定 gap 与自由空间分布区域。',
      'spacing.kind': '固定 gap 或对齐产生的自由空间。',
      'spacing.axis': '该间距区域的物理主轴。',
      'spacing.bounds': '当前容器分配坐标中的间距矩形。',
      'spacing.bounds.x': '间距矩形的水平原点。',
      'spacing.bounds.y': '间距矩形的垂直原点。',
      'spacing.bounds.width': '间距矩形的非负宽度；x 主轴时必须为正。',
      'spacing.bounds.height': '间距矩形的非负高度；y 主轴时必须为正。',
    },
  },
  LayoutArtifactSchema: {
    descriptions: {
      kind: '间距片段的语义判别字段。',
      axis: '间距片段的物理主轴。',
      bounds: '当前容器 allocation 坐标中的最终矩形。',
      'bounds.x': '间距矩形的水平原点。',
      'bounds.y': '间距矩形的垂直原点。',
      'bounds.width': '间距矩形的非负宽度；x 主轴时必须为正。',
      'bounds.height': '间距矩形的非负高度；y 主轴时必须为正。',
    },
  },
  BaseLayoutInspectOptionsSchema: {
    descriptions: {
      bounds: 'false 关闭全部边界，true 恢复默认边界组合，对象形式逐项覆盖容器、内容、父级分配、真实占用与视觉边界。',
      spacing: 'false 关闭 padding 与 margin 纹理，true 恢复默认组合，对象形式逐项覆盖两种盒模型间距。',
      overflow: '是否显示真实占用或视觉包络超出父级分配区域的阴影。',
      alignmentGuides: '是否显示容器最终采用的对齐参考线。',
      labels: '是否显示辅助层文字标签；默认关闭。',
    },
  },
  LayoutInspectSpacingOptionsSchema: {
    descriptions: {
      padding: '是否为容器已解析的 padding 绘制阴影。',
      margin: '是否为子项已解析的 margin 绘制阴影。',
    },
  },
  LayoutInspectBoundsOptionsSchema: {
    descriptions: {
      container: '是否显示容器最终分配边界。',
      content: '是否显示扣除内边距后的内容边界。',
      slot: '是否显示父级给子项分配的 slot。',
      allocation: '是否显示子项真实布局占用。',
      visual: '是否显示包含描边与标签等效果的视觉包络。',
    },
  },
  FlexLayoutSchema: {
    descriptions: {
      namespace: 'Layout 排版能力的复合组件命名空间。',
      type: '确定性一维盒布局的复合组件类型。',
      size: '包含内边距的容器双轴分配尺寸策略。',
      padding: '从容器分配区域到内容区域的内边距。',
      overflow: '视觉溢出保持可见或裁切到容器分配区域的策略。',
      direction: '主轴的物理方向。',
      wrap: '换行与交叉轴遍历策略。',
      gap: '数字同时设置两个物理轴的间距；对象分别设置 column 与 row。',
      justifyContent: '每条布局行内主轴剩余空间的分布方式。',
      alignItems: '弹性子项默认的交叉轴对齐方式。',
      alignContent: '多条布局行之间交叉轴剩余空间的分布方式。',
      children: '按稳定绘制顺序排列、由作者声明的弹性子项。',
    },
  },
  FlexLayoutItemSchema: {
    descriptions: {
      kind: '子项判别字段；可使用 `LayoutItemKind.Flex`',
      key: '可选的容器局部稳定身份；省略时按 source index 生成',
      child: '参与布局的任意可 JSON 序列化 Core 子图形',
      margin: '分配区域外边距；不进入子图形的空间提案',
      basis: '自然主轴贡献，或作者给出的有限非负基础分配尺寸',
      grow: '接收正剩余空间的有限非负系数',
      shrink: '与未约束基础尺寸相乘，用于回收负剩余空间',
      min: '显式值替代自动最小值；子图形拒绝时以真实占用溢出表达',
      max: '作者给出的主轴分配尺寸硬上限',
      alignSelf: '覆盖当前子项的交叉轴对齐',
    },
  },
  GridLayoutItemSchema: {
    descriptions: {
      kind: '网格布局子项判别字段',
      key: '可选稳定身份；省略时按 source index 生成',
      child: '任意可 JSON 序列化的 Core 子图形',
      column: '列放置范围',
      row: '行放置范围',
      margin: '轨道区域内缩前的子项外边距',
      justifySelf: '覆盖水平对齐',
      alignSelf: '覆盖垂直对齐',
    },
  },
  OverlayLayoutItemSchema: {
    descriptions: {
      kind: '叠加布局子项判别字段',
      key: '可选稳定身份；省略时按 source index 生成',
      child: '任意可 JSON 序列化的 Core 子图形',
      placement: '对齐或内容区域局部定位',
      offset: '放置后的偏移',
      margin: '对齐或定位分配区域的外边距',
      justifySelf: '覆盖水平对齐',
      alignSelf: '覆盖垂直对齐',
      sizeParticipation: '是否参与固有尺寸轮廓计算',
      zIndex: '整数绘制层级；相同值保持作者声明顺序',
    },
  },
  LayoutAxisSizeSchema: {
    descriptions: {
      kind: '尺寸或放置形式的判别字段',
      value: '固定非负尺寸',
      min: '可选最小尺寸，不大于 max',
      max: '可选最大尺寸，不小于 min',
    },
  },
  LayoutSizeSchema: {
    descriptions: {
      x: '物理水平方向的尺寸策略',
      y: '物理垂直方向的尺寸策略',
    },
  },
  GridPlacementSchema: {
    descriptions: {
      start: '从零开始的显式轨道起点；省略时自动放置',
      span: '跨越的正整数轨道数量',
    },
  },
  GridTrackBreadthSchema: {
    descriptions: {
      kind: '尺寸或放置形式的判别字段',
      value: '固定非负尺寸',
      mode: '使用 minimum 最小贡献或 natural 自然贡献',
      factor: '有限剩余空间中的正份额权重',
    },
  },
  GridTrackSchema: {
    descriptions: {
      kind: '尺寸或放置形式的判别字段',
      value: '固定非负尺寸',
      min: '固定或内容下界，不接受份额轨道',
      max: '固定、内容或份额上界；固定上下界时 max 不小于 min',
      mode: '使用 minimum 最小贡献或 natural 自然贡献',
      factor: '有限剩余空间中的正份额权重',
    },
  },
  OverlayPlacementSchema: {
    descriptions: {
      kind: '尺寸或放置形式的判别字段',
      at: '相对内容区域起点的局部目标点',
      anchor: '分配区域上的归一化锚点，两个轴范围均为 0 到 1',
      width: '可选精确分配宽度',
      height: '可选精确分配高度',
    },
  },
  LayoutTrackArtifactSchema: {
    descriptions: {
      index: '从零开始且连续的轨道序号',
      start: '轨道的物理起点',
      size: '已求解的非负轨道尺寸',
      sourceKind: '轨道最外层的尺寸策略',
      implicit: '是否为超出显式列表后生成的隐式轨道',
    },
  },
};
