/** 所有 API 属性表共用的短分组名 */
export const apiReferenceGroupLabels = {
  Main: { zh: '主要', en: 'Main' },
  Input: { zh: '输入', en: 'Input' },
  Output: { zh: '输出', en: 'Output' },
  Data: { zh: '数据', en: 'Data' },
  Geometry: { zh: '几何', en: 'Geometry' },
  Layout: { zh: '布局', en: 'Layout' },
  Style: { zh: '样式', en: 'Style' },
  Rendering: { zh: '渲染', en: 'Rendering' },
  Callbacks: { zh: '回调', en: 'Callbacks' },
  Animation: { zh: '动画', en: 'Animation' },
  Runtime: { zh: '运行时', en: 'Runtime' },
  Extensions: { zh: '扩展', en: 'Extensions' },
} as const;

/** 属性分组的固定英文键 */
export type ApiReferenceGroupName = keyof typeof apiReferenceGroupLabels;

/** LLM 审阅后的字段归属；字段类型、说明和组内顺序仍来自源码 */
export type ApiReferenceGroupPlan = {
  order: ReadonlyArray<ApiReferenceGroupName>;
  members: Readonly<Record<string, ApiReferenceGroupName>>;
};

/** React、Vanilla 与 Core 节点输入共享的字段用途 */
const nodeMemberGroups = {
  animations: 'Animation',
  boundary: 'Geometry',
  cornerRadius: 'Geometry',
  id: 'Main',
  label: 'Main',
  layout: 'Geometry',
  meta: 'Runtime',
  position: 'Geometry',
  rotate: 'Geometry',
  scale: 'Geometry',
  shape: 'Geometry',
  style: 'Style',
  text: 'Main',
  zIndex: 'Style',
} as const satisfies Readonly<Record<string, ApiReferenceGroupName>>;

/** 以公开包名和符号名定位分组，不在各 API 页面脚本中设置条件 */
export const apiReferenceMemberGroups: Readonly<Partial<Record<string, ApiReferenceGroupPlan>>> = {
  '@retikz/react#LayoutProps': {
    order: ['Main', 'Layout', 'Style', 'Rendering', 'Callbacks', 'Animation', 'Runtime', 'Output', 'Extensions'],
    members: {
      children: 'Main',
      ir: 'Main',
      nodeDistance: 'Layout',
      fontSize: 'Style',
      rootScope: 'Style',
      theme: 'Style',
      width: 'Rendering',
      height: 'Rendering',
      viewBox: 'Rendering',
      className: 'Rendering',
      style: 'Rendering',
      renderer: 'Rendering',
      idPrefix: 'Rendering',
      handlers: 'Callbacks',
      onArtifacts: 'Callbacks',
      onCompileResult: 'Callbacks',
      animations: 'Animation',
      animate: 'Animation',
      snapshotAt: 'Animation',
      animationRef: 'Animation',
      easings: 'Animation',
      animationProperties: 'Animation',
      runtime: 'Runtime',
      authoring: 'Runtime',
      compileDriver: 'Runtime',
      artifacts: 'Output',
      extensions: 'Extensions',
      lowerTex: 'Extensions',
    },
  },
  '@retikz/react#ScopeProps': {
    order: ['Main', 'Geometry', 'Style', 'Callbacks', 'Animation', 'Runtime'],
    members: {
      children: 'Main',
      id: 'Main',
      localNamespace: 'Main',
      boundingShape: 'Geometry',
      clip: 'Geometry',
      placement: 'Geometry',
      transforms: 'Geometry',
      defaults: 'Style',
      frame: 'Style',
      style: 'Style',
      theme: 'Style',
      zIndex: 'Style',
      onClick: 'Callbacks',
      onDoubleClick: 'Callbacks',
      onPointerDown: 'Callbacks',
      onPointerEnter: 'Callbacks',
      onPointerLeave: 'Callbacks',
      onPointerMove: 'Callbacks',
      onPointerUp: 'Callbacks',
      onRightClick: 'Callbacks',
      onWheel: 'Callbacks',
      animations: 'Animation',
      authoring: 'Runtime',
      meta: 'Runtime',
    },
  },
  '@retikz/react#PathProps': {
    order: ['Main', 'Geometry', 'Style', 'Callbacks', 'Animation', 'Runtime'],
    members: {
      children: 'Main',
      id: 'Main',
      kind: 'Main',
      kindOptions: 'Main',
      label: 'Main',
      way: 'Main',
      arrow: 'Geometry',
      arrowDetail: 'Geometry',
      arrowPlacement: 'Geometry',
      marks: 'Geometry',
      rotate: 'Geometry',
      roundedCorners: 'Geometry',
      scale: 'Geometry',
      style: 'Style',
      thickness: 'Style',
      zIndex: 'Style',
      onClick: 'Callbacks',
      onDoubleClick: 'Callbacks',
      onPointerDown: 'Callbacks',
      onPointerEnter: 'Callbacks',
      onPointerLeave: 'Callbacks',
      onPointerMove: 'Callbacks',
      onPointerUp: 'Callbacks',
      onRightClick: 'Callbacks',
      onWheel: 'Callbacks',
      animations: 'Animation',
      authoring: 'Runtime',
      meta: 'Runtime',
    },
  },
  '@retikz/vanilla#InputPath': {
    order: ['Main', 'Geometry', 'Style', 'Animation', 'Runtime'],
    members: {
      children: 'Main',
      id: 'Main',
      kind: 'Main',
      kindOptions: 'Main',
      label: 'Main',
      type: 'Main',
      way: 'Main',
      arrow: 'Geometry',
      arrowDetail: 'Geometry',
      arrowPlacement: 'Geometry',
      marks: 'Geometry',
      rotate: 'Geometry',
      roundedCorners: 'Geometry',
      scale: 'Geometry',
      style: 'Style',
      thickness: 'Style',
      zIndex: 'Style',
      animations: 'Animation',
      authoring: 'Runtime',
      meta: 'Runtime',
    },
  },
  '@retikz/react#NodeProps': {
    order: ['Main', 'Geometry', 'Style', 'Callbacks', 'Animation', 'Runtime'],
    members: {
      ...nodeMemberGroups,
      authoring: 'Runtime',
      children: 'Main',
      onClick: 'Callbacks',
      onDoubleClick: 'Callbacks',
      onPointerDown: 'Callbacks',
      onPointerEnter: 'Callbacks',
      onPointerLeave: 'Callbacks',
      onPointerMove: 'Callbacks',
      onPointerUp: 'Callbacks',
      onRightClick: 'Callbacks',
      onWheel: 'Callbacks',
    },
  },
  '@retikz/vanilla#InputNode': {
    order: ['Main', 'Geometry', 'Style', 'Animation', 'Runtime'],
    members: { ...nodeMemberGroups, authoring: 'Runtime', type: 'Main' },
  },
  '@retikz/core#IRNode': {
    order: ['Main', 'Geometry', 'Style', 'Animation', 'Runtime'],
    members: { ...nodeMemberGroups, type: 'Main' },
  },
};
