import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { translateNodeApiReference } from './node.en';
import type { ApiReferenceLanguage, ApiReferencePackageConfig } from './tex';
import { createApiReferenceMdx } from './tex';

const repositoryRoot = path.resolve(import.meta.dirname, '../../../..');

/** 节点家族的公开入口切片；类型和说明仍从源码提取 */
export const nodeApiConfigs: ReadonlyArray<ApiReferencePackageConfig> = [
  { owner: 'react', symbols: ['Node', 'NodeProps', 'Text', 'TextProps', 'Coordinate', 'CoordinateProps'] },
  {
    owner: 'vanilla',
    symbols: [
      'node',
      'coordinate',
      'InputNode',
      'InputCoordinate',
      'InputNodeLabel',
      'InputNodeLabelPosition',
      'InputNodeLabelBoundaryPosition',
    ],
  },
  {
    owner: 'core',
    symbols: [
      'IRNode',
      'IRNodeStyle',
      'IRNodeLayout',
      'IRNodeLabel',
      'IRCoordinate',
      'NodeTextColor',
      'defineBoundary',
      'BoundaryDefinition',
      'BoundaryDefinitionInput',
      'BoundaryFitContext',
      'BoundaryAnchorName',
      'BUILTIN_BOUNDARIES',
    ],
  },
].map(({ owner, symbols }) => ({
  packageName: `@retikz/${owner}`,
  packageDirectory: `packages/kernel/${owner}`,
  tsconfigPath: path.resolve(repositoryRoot, `packages/kernel/${owner}/tsconfig.json`),
  entries: [
    {
      source: path.resolve(repositoryRoot, `packages/kernel/${owner}/src/index.ts`),
      title: { zh: `\`@retikz/${owner}\``, en: `\`@retikz/${owner}\`` },
      symbols,
    },
  ],
  translate: translateNodeApiReference,
}));

/** 按真实 package 入口分别解析，再合并为组件参考 */
export const createNodeApiReferenceMdx = async (lang: ApiReferenceLanguage): Promise<string> => {
  const sections: Array<string> = [];
  for (const config of nodeApiConfigs) sections.push(await createApiReferenceMdx(config, lang));
  return sections.join('\n\n');
};

/** 写出可重复生成的节点双语 API include */
export const writeNodeApiReferenceMdx = async (outputDirectory: string): Promise<void> => {
  mkdirSync(outputDirectory, { recursive: true });
  for (const lang of ['zh', 'en'] as const) {
    const source = await createNodeApiReferenceMdx(lang);
    writeFileSync(
      path.resolve(outputDirectory, `generated.${lang}.mdx`),
      `{/* Generated by pnpm generate:api-reference. Do not edit manually. */}\n\n${source}\n`,
      'utf8',
    );
  }
};
