import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { translateRibbonApiReference } from './ribbon.en';
import { createApiReferenceMdx } from './tex';

const repositoryRoot = path.resolve(import.meta.dirname, '../../../..');
const packageDirectory = 'packages/library/extension';

/** 只投影 Extension 包根真实公开导出的 Ribbon 成员 */
export const writeRibbonApiReferenceMdx = async (outputDirectory: string): Promise<void> => {
  mkdirSync(outputDirectory, { recursive: true });
  for (const lang of ['zh', 'en'] as const) {
    const content = await createApiReferenceMdx(
      {
        packageName: '@retikz/extension',
        packageDirectory,
        tsconfigPath: path.resolve(repositoryRoot, packageDirectory, 'tsconfig.json'),
        entries: [
          {
            source: path.resolve(repositoryRoot, packageDirectory, 'src/index.ts'),
            title: { zh: '`@retikz/extension` · Ribbon', en: '`@retikz/extension` · Ribbon' },
            symbols: [
              'RibbonPathKindDefinition',
              'createRibbonPathKindDefinition',
              'defineRibbonWidthProfile',
              'defineRibbonCap',
              'RibbonCapDefinition',
              'RibbonCapContext',
              'RibbonCapGeometry',
              'createRibbonProviderContribution',
              'RibbonWidthProfileDefinitionInput',
              'RibbonWidthProfileContext',
            ],
          },
        ],
        translate: translateRibbonApiReference,
      },
      lang,
    );
    writeFileSync(
      path.resolve(outputDirectory, `generated.${lang}.mdx`),
      `{/* Generated by pnpm generate:ribbon-api-reference. Do not edit manually. */}\n\n${content}\n`,
      'utf8',
    );
  }
};
