import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { translateDrawApiReference } from './draw.en';
import { createApiReferenceMdx } from './tex';
import type { ApiReferencePackageConfig } from './tex';

const repositoryRoot = path.resolve(import.meta.dirname, '../../../..');
const pages = {
  Grid: {
    react: ['Grid', 'GridProps'],
    vanilla: ['grid', 'GridInputEmbedAdapter'],
    core: ['GridInput', 'GridLineInput', 'IRGrid', 'createGrid', 'GridDefinition', 'GridProvider'],
  },
} as const;

/** 公开声明的英文文案；通用字段沿用已有翻译，缺译由生成器拒绝 */
const translatePresentationApiReference = (source: string): string =>
  translateDrawApiReference(
    source
      .replace('可省略默认值的包络装饰', 'Envelope decoration with optional defaults')
      .replace(/React (\w+) 组件接受的 Standard authoring 输入/g, 'Standard authoring input accepted by React $1')
      .replace(/Standard (\w+) 的 React Tier 2 authoring 组件/g, 'React Tier 2 authoring component for Standard $1')
      .replace(/Standard (\w+) 的 InputEmbed adapter/g, 'InputEmbed adapter for Standard $1')
      .replace(
        /创建由 (\w+)InputEmbedAdapter 下沉的 Standard (\w+) embed/g,
        'Create a Standard $2 embed lowered by $1InputEmbedAdapter',
      )
      .replace(/组装持久化的 Standard (\w+) composite/g, 'Assemble a persistent Standard $1 composite')
      .replace(/持久化的 Standard (\w+) composite/g, 'Persistent Standard $1 composite')
      .replace(
        /创建 (\w+) 时允许省略固定 discriminator 的输入/g,
        'Input for creating $1 with fixed discriminators omitted',
      )
      .replace(/Standard (\w+) 的官方 Core composite definition/g, 'Official Core composite definition for Standard $1')
      .replace(/(\w+) 的 Core Composite dependency provider/g, 'Core composite dependency provider for $1')
      .replace('单个 Grid 方向的线条输入配置', 'Line configuration for one Grid direction'),
  );

/** 按组件合页生成呈现家族的三个公开入口 */
export const writeStandardPresentationApiReferences = async (
  outputRoot: string,
  names: ReadonlyArray<keyof typeof pages> = Object.keys(pages) as Array<keyof typeof pages>,
): Promise<void> => {
  for (const name of names) {
    const page = pages[name];
    const owners = [
      { suffix: '-react', symbols: page.react },
      { suffix: '-vanilla', symbols: page.vanilla },
      { suffix: '', symbols: page.core },
    ];
    const directory = path.resolve(outputRoot, name.toLowerCase(), '_includes');
    mkdirSync(directory, { recursive: true });
    for (const lang of ['zh', 'en'] as const) {
      const sections: Array<string> = [];
      for (const owner of owners) {
        const packageName = `@retikz/standard${owner.suffix}`;
        const packageDirectory = `packages/library/standard${owner.suffix}`;
        const config: ApiReferencePackageConfig = {
          packageName: `${packageName}/presentation`,
          packageDirectory,
          tsconfigPath: path.resolve(repositoryRoot, packageDirectory, 'tsconfig.json'),
          translate: translatePresentationApiReference,
          entries: [
            {
              source: path.resolve(repositoryRoot, packageDirectory, 'src/presentation/index.ts'),
              title: { zh: `\`${packageName}\``, en: `\`${packageName}\`` },
              symbols: owner.symbols,
              declarationOnlySymbols: [`${name}Definition`, `${name}Provider`, `${name}InputEmbedAdapter`],
              ...(owner.suffix === '-react' ? { symbolPairs: [[name, `${name}Props`] as const] } : {}),
            },
          ],
        };
        sections.push((await createApiReferenceMdx(config, lang)).replace(/^(#{2,4}) /gm, '#$1 '));
      }
      writeFileSync(
        path.resolve(directory, `generated.${lang}.mdx`),
        `{/* Generated by pnpm generate:api-reference. Do not edit manually. */}\n\n${sections.join('\n\n')}\n`,
        'utf8',
      );
    }
  }
};
