import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import type { ApiReferencePackageConfig } from './tex';
import { createApiReferenceMdx } from './tex';
import { translateVisualApiReference } from './visual.en';

/** 从 Standard 根入口生成效果工厂与选项的参考 */
export const writeStandardAnimationApiReference = async (directory: string): Promise<void> => {
  const repositoryRoot = path.resolve(import.meta.dirname, '../../../..');
  const config: ApiReferencePackageConfig = {
    packageName: '@retikz/standard',
    packageDirectory: 'packages/library/standard',
    tsconfigPath: path.resolve(repositoryRoot, 'packages/library/standard/tsconfig.json'),
    entries: [
      {
        source: path.resolve(repositoryRoot, 'packages/library/standard/src/index.ts'),
        title: { zh: '效果预设', en: 'Effect presets' },
        symbols: [
          'grow',
          'growUp',
          'pulse',
          'spin',
          'flash',
          'blink',
          'wiggle',
          'GrowUpOptions',
          'PulseOptions',
          'SpinOptions',
          'FlashOptions',
          'BlinkOptions',
          'WiggleOptions',
        ],
      },
    ],
    translate: translateVisualApiReference,
  };
  mkdirSync(directory, { recursive: true });
  for (const lang of ['zh', 'en'] as const) {
    writeFileSync(
      path.resolve(directory, `generated.${lang}.mdx`),
      `{/* Generated by pnpm generate:api-reference. Do not edit manually. */}\n\n${await createApiReferenceMdx(config, lang)}\n`,
      'utf8',
    );
  }
};
