import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { translateDrawApiReference } from './draw.en';
import { createApiReferenceMdx } from './tex';
import type { ApiReferencePackageConfig } from './tex';

const repositoryRoot = path.resolve(import.meta.dirname, '../../../..');
const groups = {
  'circle-ellipse': ['Circle', 'Ellipse'],
  rectangle: ['Rectangle'],
  'regular-polygon': ['RegularPolygon'],
  star: ['Star'],
  'arc-sector': ['Arc', 'Sector'],
} as const;

/** 翻译形状公开入口的注释，通用 Path 字段复用既有词典 */
const translateShapeApiReference = (source: string): string => {
  const translated = source
    .replace(/React (\w+) 的作者输入与宿主事件/g, 'React $1 authoring input and host events')
    .replace(/通过 Vanilla adapter 声明 Standard (\w+)/g, 'Declare a Standard $1 through its Vanilla adapter')
    .replace(/(\w+) 的 Vanilla 作者输入/g, '$1 Vanilla authoring input')
    .replace(
      /将 (\w+) 作者输入归一为持久化的 Standard 意图/g,
      'Normalize $1 authoring input into persistent Standard intent',
    )
    .replace(/创建保留几何意图的 (\w+) Source/g, 'Create a $1 Source preserving geometry intent')
    .replace(/持久化的 (\w+) 形状/g, 'Persistent $1 shape')
    .replace(/(\w+) 的 Core composite 注册项/g, '$1 Core composite registration')
    .replace(/(\w+) 的按需依赖贡献/g, '$1 on-demand dependency contribution')
    .replace(/显式路径身份/g, 'Explicit path identity');
  return translateDrawApiReference(translated);
};

/** 按五篇形状文档生成其所属的公开 API，不复制 Kernel 参考 */
export const writeStandardShapeApiReferences = async (outputRoot: string): Promise<void> => {
  for (const [slug, names] of Object.entries(groups)) {
    const configs: Array<ApiReferencePackageConfig> = [
      {
        packageName: '@retikz/standard-react/shape',
        packageDirectory: 'packages/library/standard-react',
        tsconfigPath: path.resolve(repositoryRoot, 'packages/library/standard-react/tsconfig.json'),
        entries: [
          {
            source: path.resolve(repositoryRoot, 'packages/library/standard-react/src/shape/index.ts'),
            title: { zh: 'React 入口', en: 'React entry' },
            symbols: names.flatMap(name => [name, `${name}Props`]),
          },
        ],
        translate: translateShapeApiReference,
      },
      {
        packageName: '@retikz/standard-vanilla/shape',
        packageDirectory: 'packages/library/standard-vanilla',
        tsconfigPath: path.resolve(repositoryRoot, 'packages/library/standard-vanilla/tsconfig.json'),
        entries: [
          {
            source: path.resolve(repositoryRoot, 'packages/library/standard-vanilla/src/shape/index.ts'),
            title: { zh: 'Vanilla 输入与适配器', en: 'Vanilla inputs and adapters' },
            symbols: names.flatMap(name => [`Input${name}`, `${name}InputEmbedAdapter`]),
          },
        ],
        translate: translateShapeApiReference,
      },
      {
        packageName: '@retikz/standard/shape',
        packageDirectory: 'packages/library/standard',
        tsconfigPath: path.resolve(repositoryRoot, 'packages/library/standard/tsconfig.json'),
        entries: [
          {
            source: path.resolve(repositoryRoot, 'packages/library/standard/src/shape/index.ts'),
            title: { zh: 'Source 与能力装配', en: 'Source and capability assembly' },
            symbols: names.flatMap(name => [`IR${name}`, `create${name}`, `${name}Definition`, `${name}Provider`]),
          },
        ],
        translate: translateShapeApiReference,
      },
    ];
    const directory = path.resolve(outputRoot, slug, '_includes');
    mkdirSync(directory, { recursive: true });
    for (const lang of ['zh', 'en'] as const) {
      const sections: Array<string> = [];
      for (const config of configs) sections.push(await createApiReferenceMdx(config, lang));
      writeFileSync(
        path.resolve(directory, `generated.${lang}.mdx`),
        `{/* Generated by pnpm generate:api-reference. Do not edit manually. */}\n\n${sections.join('\n\n')}\n`,
        'utf8',
      );
    }
  }
};
