import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import type { ApiReferencePackageConfig } from './tex';
import { createApiReferenceMdx } from './tex';
import { translateVisualApiReference } from './visual.en';

const repositoryRoot = path.resolve(import.meta.dirname, '../../../..');

/** 动画工厂与编排工具独立于数据类型展示 */
const animationPresetSymbols: ReadonlySet<string> = new Set([
  'cameraTo',
  'colorShift',
  'drawOn',
  'fadeIn',
  'loop',
  'scaleIn',
  'slideIn',
  'stagger',
]);

/** 视觉参考只投影各能力拥有的公开导出 */
export const visualApiSymbols = {
  pattern: [
    'PatternShape',
    'IRPatternPaint',
    'IRPatternLineStyle',
    'IRPatternLineStyleCycle',
    'definePattern',
    'PatternDefinition',
    'PatternEmitContext',
    'PatternEmitResult',
    'PatternEmitOutput',
  ],
  shadow: ['ShadowPreset', 'ShadowPresetValue', 'IRDropShadow'],
  blend: ['BlendMode', 'BlendModeValue'],
  animation: [
    'IRAnimationTrack',
    'IRKeyframe',
    'AnimationPresetOptions',
    'AnimationProperty',
    'AnimationEasing',
    'AnimationDirection',
    'AnimationFill',
    'AnimationTrigger',
    'fadeIn',
    'scaleIn',
    'slideIn',
    'drawOn',
    'colorShift',
    'loop',
    'stagger',
    'cameraTo',
    'ScaleInOptions',
    'SlideInOptions',
    'ColorShiftOptions',
    'CameraToOptions',
    'LoopOptions',
  ],
} as const;

/** 构建公开入口分析配置，渲染器动画扩展使用独立子入口 */
export const createVisualApiConfig = (
  symbols: ReadonlyArray<string>,
  renderer = false,
  title?: { zh: string; en: string },
): ApiReferencePackageConfig => {
  const owner = renderer ? 'render' : 'core';
  const source = path.resolve(repositoryRoot, `packages/kernel/${owner}/src/${renderer ? 'animation/' : ''}index.ts`);
  const presets = !renderer && symbols.every(symbol => animationPresetSymbols.has(symbol));
  return {
    packageName: renderer ? '@retikz/render/animation' : '@retikz/core',
    packageDirectory: `packages/kernel/${owner}`,
    tsconfigPath: path.resolve(repositoryRoot, `packages/kernel/${owner}/tsconfig.json`),
    entries: [
      {
        source,
        title: title ?? {
          zh: renderer ? '播放与扩展' : presets ? '预设与编排' : '公开契约',
          en: renderer ? 'Playback and extensions' : presets ? 'Presets and orchestration' : 'Public contracts',
        },
        symbols: [...symbols],
      },
    ],
    translate: translateVisualApiReference,
  };
};

/** 动画参考按数据契约、预设与编排、播放扩展组织 */
export const createAnimationApiConfigs = (): Array<ApiReferencePackageConfig> => [
  createVisualApiConfig(visualApiSymbols.animation.filter(symbol => !animationPresetSymbols.has(symbol))),
  createVisualApiConfig(visualApiSymbols.animation.filter(symbol => animationPresetSymbols.has(symbol))),
  createVisualApiConfig(
    ['AnimationControls', 'EasingRegistry', 'AnimationPropertyDefinition', 'AnimationPropertyRegistry'],
    true,
  ),
];

/** 从真实公开入口生成四组视觉 API 参考 */
/** 生成 style 的三组公开 API，同页按图案、阴影与混合分节 */
export const writeStyleApiReference = async (outputRoot: string): Promise<void> => {
  const configs = [
    createVisualApiConfig(visualApiSymbols.pattern, false, { zh: 'pattern · 图案', en: 'pattern · Patterns' }),
    createVisualApiConfig(visualApiSymbols.shadow, false, { zh: 'shadow · 阴影', en: 'shadow · Shadows' }),
    createVisualApiConfig(visualApiSymbols.blend, false, { zh: 'blend · 混合', en: 'blend · Blending' }),
  ];
  mkdirSync(outputRoot, { recursive: true });
  for (const lang of ['zh', 'en'] as const) {
    const sections = await Promise.all(configs.map(config => createApiReferenceMdx(config, lang)));
    writeFileSync(
      path.resolve(outputRoot, `generated.${lang}.mdx`),
      `{/* Generated by pnpm generate:api-reference. Do not edit manually. */}\n\n${sections.join('\n\n')}\n`,
      'utf8',
    );
  }
};

/** 生成动画 API 参考 */
export const writeAnimationApiReference = async (outputRoot: string): Promise<void> => {
  const configs = createAnimationApiConfigs();
  mkdirSync(outputRoot, { recursive: true });
  for (const lang of ['zh', 'en'] as const) {
    const sections = await Promise.all(configs.map(config => createApiReferenceMdx(config, lang)));
    writeFileSync(
      path.resolve(outputRoot, `generated.${lang}.mdx`),
      `{/* Generated by pnpm generate:api-reference. Do not edit manually. */}\n\n${sections.join('\n\n')}\n`,
      'utf8',
    );
  }
};
