/** UCI Iris 数据集页面 */
export const IRIS_REGRESSION_SOURCE_URL = 'https://archive.ics.uci.edu/dataset/53/iris';

/** UCI Iris 数据集 DOI */
export const IRIS_REGRESSION_SOURCE_DOI = '10.24432/C56C76';

/** UCI Iris 数据集许可 */
export const IRIS_REGRESSION_LICENSE = 'CC BY 4.0';

/** Regression Showcase 使用的 Iris 观测 */
export type IrisRegressionDatum = {
  /** 萼片长度，单位为厘米 */
  sepalLengthCm: number;
  /** 花瓣长度，单位为厘米 */
  petalLengthCm: number;
  /** Iris 物种 */
  species: 'setosa' | 'versicolor' | 'virginica';
};

/**
 * UCI Iris 的 150 行静态快照
 *
 * @remarks 数据来自 UCI Machine Learning Repository 的 Iris 数据集，DOI 为
 * `10.24432/C56C76`，许可为 CC BY 4.0。本示例保留全部 150 行且不筛选观测，
 * 只选择萼片长度、花瓣长度与物种三个字段并改为 camelCase
 */
export const irisRegressionData: Array<IrisRegressionDatum> = [
  { sepalLengthCm: 5.1, petalLengthCm: 1.4, species: 'setosa' },
  { sepalLengthCm: 4.9, petalLengthCm: 1.4, species: 'setosa' },
  { sepalLengthCm: 4.7, petalLengthCm: 1.3, species: 'setosa' },
  { sepalLengthCm: 4.6, petalLengthCm: 1.5, species: 'setosa' },
  { sepalLengthCm: 5, petalLengthCm: 1.4, species: 'setosa' },
  { sepalLengthCm: 5.4, petalLengthCm: 1.7, species: 'setosa' },
  { sepalLengthCm: 4.6, petalLengthCm: 1.4, species: 'setosa' },
  { sepalLengthCm: 5, petalLengthCm: 1.5, species: 'setosa' },
  { sepalLengthCm: 4.4, petalLengthCm: 1.4, species: 'setosa' },
  { sepalLengthCm: 4.9, petalLengthCm: 1.5, species: 'setosa' },
  { sepalLengthCm: 5.4, petalLengthCm: 1.5, species: 'setosa' },
  { sepalLengthCm: 4.8, petalLengthCm: 1.6, species: 'setosa' },
  { sepalLengthCm: 4.8, petalLengthCm: 1.4, species: 'setosa' },
  { sepalLengthCm: 4.3, petalLengthCm: 1.1, species: 'setosa' },
  { sepalLengthCm: 5.8, petalLengthCm: 1.2, species: 'setosa' },
  { sepalLengthCm: 5.7, petalLengthCm: 1.5, species: 'setosa' },
  { sepalLengthCm: 5.4, petalLengthCm: 1.3, species: 'setosa' },
  { sepalLengthCm: 5.1, petalLengthCm: 1.4, species: 'setosa' },
  { sepalLengthCm: 5.7, petalLengthCm: 1.7, species: 'setosa' },
  { sepalLengthCm: 5.1, petalLengthCm: 1.5, species: 'setosa' },
  { sepalLengthCm: 5.4, petalLengthCm: 1.7, species: 'setosa' },
  { sepalLengthCm: 5.1, petalLengthCm: 1.5, species: 'setosa' },
  { sepalLengthCm: 4.6, petalLengthCm: 1, species: 'setosa' },
  { sepalLengthCm: 5.1, petalLengthCm: 1.7, species: 'setosa' },
  { sepalLengthCm: 4.8, petalLengthCm: 1.9, species: 'setosa' },
  { sepalLengthCm: 5, petalLengthCm: 1.6, species: 'setosa' },
  { sepalLengthCm: 5, petalLengthCm: 1.6, species: 'setosa' },
  { sepalLengthCm: 5.2, petalLengthCm: 1.5, species: 'setosa' },
  { sepalLengthCm: 5.2, petalLengthCm: 1.4, species: 'setosa' },
  { sepalLengthCm: 4.7, petalLengthCm: 1.6, species: 'setosa' },
  { sepalLengthCm: 4.8, petalLengthCm: 1.6, species: 'setosa' },
  { sepalLengthCm: 5.4, petalLengthCm: 1.5, species: 'setosa' },
  { sepalLengthCm: 5.2, petalLengthCm: 1.5, species: 'setosa' },
  { sepalLengthCm: 5.5, petalLengthCm: 1.4, species: 'setosa' },
  { sepalLengthCm: 4.9, petalLengthCm: 1.5, species: 'setosa' },
  { sepalLengthCm: 5, petalLengthCm: 1.2, species: 'setosa' },
  { sepalLengthCm: 5.5, petalLengthCm: 1.3, species: 'setosa' },
  { sepalLengthCm: 4.9, petalLengthCm: 1.5, species: 'setosa' },
  { sepalLengthCm: 4.4, petalLengthCm: 1.3, species: 'setosa' },
  { sepalLengthCm: 5.1, petalLengthCm: 1.5, species: 'setosa' },
  { sepalLengthCm: 5, petalLengthCm: 1.3, species: 'setosa' },
  { sepalLengthCm: 4.5, petalLengthCm: 1.3, species: 'setosa' },
  { sepalLengthCm: 4.4, petalLengthCm: 1.3, species: 'setosa' },
  { sepalLengthCm: 5, petalLengthCm: 1.6, species: 'setosa' },
  { sepalLengthCm: 5.1, petalLengthCm: 1.9, species: 'setosa' },
  { sepalLengthCm: 4.8, petalLengthCm: 1.4, species: 'setosa' },
  { sepalLengthCm: 5.1, petalLengthCm: 1.6, species: 'setosa' },
  { sepalLengthCm: 4.6, petalLengthCm: 1.4, species: 'setosa' },
  { sepalLengthCm: 5.3, petalLengthCm: 1.5, species: 'setosa' },
  { sepalLengthCm: 5, petalLengthCm: 1.4, species: 'setosa' },
  { sepalLengthCm: 7, petalLengthCm: 4.7, species: 'versicolor' },
  { sepalLengthCm: 6.4, petalLengthCm: 4.5, species: 'versicolor' },
  { sepalLengthCm: 6.9, petalLengthCm: 4.9, species: 'versicolor' },
  { sepalLengthCm: 5.5, petalLengthCm: 4, species: 'versicolor' },
  { sepalLengthCm: 6.5, petalLengthCm: 4.6, species: 'versicolor' },
  { sepalLengthCm: 5.7, petalLengthCm: 4.5, species: 'versicolor' },
  { sepalLengthCm: 6.3, petalLengthCm: 4.7, species: 'versicolor' },
  { sepalLengthCm: 4.9, petalLengthCm: 3.3, species: 'versicolor' },
  { sepalLengthCm: 6.6, petalLengthCm: 4.6, species: 'versicolor' },
  { sepalLengthCm: 5.2, petalLengthCm: 3.9, species: 'versicolor' },
  { sepalLengthCm: 5, petalLengthCm: 3.5, species: 'versicolor' },
  { sepalLengthCm: 5.9, petalLengthCm: 4.2, species: 'versicolor' },
  { sepalLengthCm: 6, petalLengthCm: 4, species: 'versicolor' },
  { sepalLengthCm: 6.1, petalLengthCm: 4.7, species: 'versicolor' },
  { sepalLengthCm: 5.6, petalLengthCm: 3.6, species: 'versicolor' },
  { sepalLengthCm: 6.7, petalLengthCm: 4.4, species: 'versicolor' },
  { sepalLengthCm: 5.6, petalLengthCm: 4.5, species: 'versicolor' },
  { sepalLengthCm: 5.8, petalLengthCm: 4.1, species: 'versicolor' },
  { sepalLengthCm: 6.2, petalLengthCm: 4.5, species: 'versicolor' },
  { sepalLengthCm: 5.6, petalLengthCm: 3.9, species: 'versicolor' },
  { sepalLengthCm: 5.9, petalLengthCm: 4.8, species: 'versicolor' },
  { sepalLengthCm: 6.1, petalLengthCm: 4, species: 'versicolor' },
  { sepalLengthCm: 6.3, petalLengthCm: 4.9, species: 'versicolor' },
  { sepalLengthCm: 6.1, petalLengthCm: 4.7, species: 'versicolor' },
  { sepalLengthCm: 6.4, petalLengthCm: 4.3, species: 'versicolor' },
  { sepalLengthCm: 6.6, petalLengthCm: 4.4, species: 'versicolor' },
  { sepalLengthCm: 6.8, petalLengthCm: 4.8, species: 'versicolor' },
  { sepalLengthCm: 6.7, petalLengthCm: 5, species: 'versicolor' },
  { sepalLengthCm: 6, petalLengthCm: 4.5, species: 'versicolor' },
  { sepalLengthCm: 5.7, petalLengthCm: 3.5, species: 'versicolor' },
  { sepalLengthCm: 5.5, petalLengthCm: 3.8, species: 'versicolor' },
  { sepalLengthCm: 5.5, petalLengthCm: 3.7, species: 'versicolor' },
  { sepalLengthCm: 5.8, petalLengthCm: 3.9, species: 'versicolor' },
  { sepalLengthCm: 6, petalLengthCm: 5.1, species: 'versicolor' },
  { sepalLengthCm: 5.4, petalLengthCm: 4.5, species: 'versicolor' },
  { sepalLengthCm: 6, petalLengthCm: 4.5, species: 'versicolor' },
  { sepalLengthCm: 6.7, petalLengthCm: 4.7, species: 'versicolor' },
  { sepalLengthCm: 6.3, petalLengthCm: 4.4, species: 'versicolor' },
  { sepalLengthCm: 5.6, petalLengthCm: 4.1, species: 'versicolor' },
  { sepalLengthCm: 5.5, petalLengthCm: 4, species: 'versicolor' },
  { sepalLengthCm: 5.5, petalLengthCm: 4.4, species: 'versicolor' },
  { sepalLengthCm: 6.1, petalLengthCm: 4.6, species: 'versicolor' },
  { sepalLengthCm: 5.8, petalLengthCm: 4, species: 'versicolor' },
  { sepalLengthCm: 5, petalLengthCm: 3.3, species: 'versicolor' },
  { sepalLengthCm: 5.6, petalLengthCm: 4.2, species: 'versicolor' },
  { sepalLengthCm: 5.7, petalLengthCm: 4.2, species: 'versicolor' },
  { sepalLengthCm: 5.7, petalLengthCm: 4.2, species: 'versicolor' },
  { sepalLengthCm: 6.2, petalLengthCm: 4.3, species: 'versicolor' },
  { sepalLengthCm: 5.1, petalLengthCm: 3, species: 'versicolor' },
  { sepalLengthCm: 5.7, petalLengthCm: 4.1, species: 'versicolor' },
  { sepalLengthCm: 6.3, petalLengthCm: 6, species: 'virginica' },
  { sepalLengthCm: 5.8, petalLengthCm: 5.1, species: 'virginica' },
  { sepalLengthCm: 7.1, petalLengthCm: 5.9, species: 'virginica' },
  { sepalLengthCm: 6.3, petalLengthCm: 5.6, species: 'virginica' },
  { sepalLengthCm: 6.5, petalLengthCm: 5.8, species: 'virginica' },
  { sepalLengthCm: 7.6, petalLengthCm: 6.6, species: 'virginica' },
  { sepalLengthCm: 4.9, petalLengthCm: 4.5, species: 'virginica' },
  { sepalLengthCm: 7.3, petalLengthCm: 6.3, species: 'virginica' },
  { sepalLengthCm: 6.7, petalLengthCm: 5.8, species: 'virginica' },
  { sepalLengthCm: 7.2, petalLengthCm: 6.1, species: 'virginica' },
  { sepalLengthCm: 6.5, petalLengthCm: 5.1, species: 'virginica' },
  { sepalLengthCm: 6.4, petalLengthCm: 5.3, species: 'virginica' },
  { sepalLengthCm: 6.8, petalLengthCm: 5.5, species: 'virginica' },
  { sepalLengthCm: 5.7, petalLengthCm: 5, species: 'virginica' },
  { sepalLengthCm: 5.8, petalLengthCm: 5.1, species: 'virginica' },
  { sepalLengthCm: 6.4, petalLengthCm: 5.3, species: 'virginica' },
  { sepalLengthCm: 6.5, petalLengthCm: 5.5, species: 'virginica' },
  { sepalLengthCm: 7.7, petalLengthCm: 6.7, species: 'virginica' },
  { sepalLengthCm: 7.7, petalLengthCm: 6.9, species: 'virginica' },
  { sepalLengthCm: 6, petalLengthCm: 5, species: 'virginica' },
  { sepalLengthCm: 6.9, petalLengthCm: 5.7, species: 'virginica' },
  { sepalLengthCm: 5.6, petalLengthCm: 4.9, species: 'virginica' },
  { sepalLengthCm: 7.7, petalLengthCm: 6.7, species: 'virginica' },
  { sepalLengthCm: 6.3, petalLengthCm: 4.9, species: 'virginica' },
  { sepalLengthCm: 6.7, petalLengthCm: 5.7, species: 'virginica' },
  { sepalLengthCm: 7.2, petalLengthCm: 6, species: 'virginica' },
  { sepalLengthCm: 6.2, petalLengthCm: 4.8, species: 'virginica' },
  { sepalLengthCm: 6.1, petalLengthCm: 4.9, species: 'virginica' },
  { sepalLengthCm: 6.4, petalLengthCm: 5.6, species: 'virginica' },
  { sepalLengthCm: 7.2, petalLengthCm: 5.8, species: 'virginica' },
  { sepalLengthCm: 7.4, petalLengthCm: 6.1, species: 'virginica' },
  { sepalLengthCm: 7.9, petalLengthCm: 6.4, species: 'virginica' },
  { sepalLengthCm: 6.4, petalLengthCm: 5.6, species: 'virginica' },
  { sepalLengthCm: 6.3, petalLengthCm: 5.1, species: 'virginica' },
  { sepalLengthCm: 6.1, petalLengthCm: 5.6, species: 'virginica' },
  { sepalLengthCm: 7.7, petalLengthCm: 6.1, species: 'virginica' },
  { sepalLengthCm: 6.3, petalLengthCm: 5.6, species: 'virginica' },
  { sepalLengthCm: 6.4, petalLengthCm: 5.5, species: 'virginica' },
  { sepalLengthCm: 6, petalLengthCm: 4.8, species: 'virginica' },
  { sepalLengthCm: 6.9, petalLengthCm: 5.4, species: 'virginica' },
  { sepalLengthCm: 6.7, petalLengthCm: 5.6, species: 'virginica' },
  { sepalLengthCm: 6.9, petalLengthCm: 5.1, species: 'virginica' },
  { sepalLengthCm: 5.8, petalLengthCm: 5.1, species: 'virginica' },
  { sepalLengthCm: 6.8, petalLengthCm: 5.9, species: 'virginica' },
  { sepalLengthCm: 6.7, petalLengthCm: 5.7, species: 'virginica' },
  { sepalLengthCm: 6.7, petalLengthCm: 5.2, species: 'virginica' },
  { sepalLengthCm: 6.3, petalLengthCm: 5, species: 'virginica' },
  { sepalLengthCm: 6.5, petalLengthCm: 5.2, species: 'virginica' },
  { sepalLengthCm: 6.2, petalLengthCm: 5.4, species: 'virginica' },
  { sepalLengthCm: 5.9, petalLengthCm: 5.1, species: 'virginica' },
];
