/** Chart 展示与类型解析默认值使用的确定令牌键 */
export const ChartThemeToken = {
  ChartCanvasFill: 'chart.canvas.fill',
  ChartPadding: 'chart.padding',
  ChartGap: 'chart.gap',
  ChartFontFamily: 'chart.font.family',
  ChartTitleForeground: 'chart.title.foreground',
  ChartTitleFontSize: 'chart.title.font.size',
  ChartTitleFontWeight: 'chart.title.font.weight',
  ChartTitleLineHeight: 'chart.title.lineHeight',
  ChartTitleAlign: 'chart.title.align',
  ChartSubtitleForeground: 'chart.subtitle.foreground',
  ChartSubtitleFontSize: 'chart.subtitle.font.size',
  ChartSubtitleFontWeight: 'chart.subtitle.font.weight',
  ChartSubtitleLineHeight: 'chart.subtitle.lineHeight',
  ChartSubtitleAlign: 'chart.subtitle.align',
  ChartNoteForeground: 'chart.note.foreground',
  ChartNoteFontSize: 'chart.note.font.size',
  ChartNoteFontWeight: 'chart.note.font.weight',
  ChartNoteLineHeight: 'chart.note.lineHeight',
  ChartNoteAlign: 'chart.note.align',
  ChartSourceForeground: 'chart.source.foreground',
  ChartSourceFontSize: 'chart.source.font.size',
  ChartSourceFontWeight: 'chart.source.font.weight',
  ChartSourceLineHeight: 'chart.source.lineHeight',
  ChartSourceAlign: 'chart.source.align',
  ChartAxisEnabled: 'chart.axis.enabled',
  ChartAxisGridEnabled: 'chart.axis.grid.enabled',
  ChartLegendEnabled: 'chart.legend.enabled',
} as const;
