import type { PreviewControlContract } from '@/modules/docs/preview';

import { definePreviewControls } from '@/modules/docs/preview';

import { tableLayoutPlaygroundRows } from './table-layout-playground.zh.data';

/** DetailTable alpha.2 布局试验场的中文控件 */
export const tableLayoutPlaygroundControls = definePreviewControls({
  presentation: 'panel',
  title: '明细表布局',
  defaultSize: 34,
  sections: [
    {
      label: '输入数据',
      defaultCollapsed: true,
      controls: [
        {
          kind: 'table',
          id: 'rows',
          label: '记录',
          rows: tableLayoutPlaygroundRows,
          columns: [
            { key: 'name', label: '姓名' },
            { key: 'group', label: '分组' },
            { key: 'score', label: '分数' },
            { key: 'status', label: '状态' },
            { key: 'note', label: '备注' },
          ],
        },
      ],
    },
    {
      label: '轨道',
      controls: [
        {
          kind: 'select',
          id: 'columnMode',
          label: '备注列尺寸',
          defaultValue: 'fixed',
          options: [
            { value: 'auto', label: '内容自然宽度' },
            { value: 'fixed', label: '固定宽度' },
            { value: 'minmax', label: '最小与最大宽度' },
          ],
        },
        {
          kind: 'range',
          id: 'columnWidth',
          label: '固定宽度',
          defaultValue: 148,
          min: 80,
          max: 188,
          step: 4,
          visibleWhen: { controlId: 'columnMode', oneOf: ['fixed'] },
        },
        {
          kind: 'range',
          id: 'columnMinWidth',
          label: '最小宽度',
          defaultValue: 96,
          min: 64,
          max: 128,
          step: 4,
          visibleWhen: { controlId: 'columnMode', oneOf: ['minmax'] },
        },
        {
          kind: 'range',
          id: 'columnMaxWidth',
          label: '最大宽度',
          defaultValue: 176,
          min: 132,
          max: 208,
          step: 4,
          visibleWhen: { controlId: 'columnMode', oneOf: ['minmax'] },
        },
        {
          kind: 'select',
          id: 'rowMode',
          label: '正文行尺寸',
          defaultValue: 'fixed',
          options: [
            { value: 'auto', label: '内容自然高度' },
            { value: 'fixed', label: '固定高度' },
          ],
        },
        {
          kind: 'range',
          id: 'rowHeight',
          label: '正文行高',
          defaultValue: 44,
          min: 28,
          max: 48,
          step: 4,
          visibleWhen: { controlId: 'rowMode', oneOf: ['fixed'] },
        },
        { kind: 'range', id: 'columnGap', label: '列间距', defaultValue: 6, min: 0, max: 16, step: 2 },
        { kind: 'range', id: 'rowGap', label: '行间距', defaultValue: 4, min: 0, max: 6, step: 2 },
      ],
    },
    {
      label: '备注 Cell',
      controls: [
        { kind: 'range', id: 'padding', label: '内边距', defaultValue: 6, min: 0, max: 12, step: 2 },
        {
          kind: 'select',
          id: 'horizontalAlign',
          label: '横向对齐',
          defaultValue: 'start',
          options: [
            { value: 'start', label: '起始侧' },
            { value: 'center', label: '居中' },
            { value: 'end', label: '结束侧' },
          ],
        },
        {
          kind: 'select',
          id: 'verticalAlign',
          label: '纵向对齐',
          defaultValue: 'center',
          options: [
            { value: 'start', label: '起始侧' },
            { value: 'center', label: '居中' },
            { value: 'end', label: '结束侧' },
          ],
          visibleWhen: { controlId: 'rowMode', oneOf: ['fixed'] },
        },
        {
          kind: 'switch',
          id: 'wrap',
          label: '按列宽换行',
          defaultValue: true,
          visibleWhen: { controlId: 'columnMode', oneOf: ['fixed', 'minmax'] },
        },
        {
          kind: 'select',
          id: 'fit',
          label: '内容适配',
          defaultValue: 'none',
          options: [
            { value: 'none', label: '保持原尺寸' },
            { value: 'contain', label: '完整包含' },
            { value: 'cover', label: '完整覆盖' },
            { value: 'stretch', label: '分轴拉伸' },
          ],
        },
        {
          kind: 'select',
          id: 'overflow',
          label: '溢出处理',
          defaultValue: 'clip',
          options: [
            { value: 'visible', label: '保持可见' },
            { value: 'clip', label: '裁进内容框' },
          ],
        },
      ],
    },
    {
      label: 'Border Graph',
      controls: [
        {
          kind: 'select',
          id: 'borderMode',
          label: '共享边模式',
          defaultValue: 'collapse',
          options: [
            { value: 'collapse', label: '合并共享边' },
            { value: 'separate', label: '保留各 Cell 边' },
          ],
        },
        { kind: 'range', id: 'gridWidth', label: '默认线宽', defaultValue: 1, min: 0.5, max: 3, step: 0.5 },
        { kind: 'switch', id: 'cellBorderEnabled', label: '强调备注列左边', defaultValue: true },
        {
          kind: 'range',
          id: 'cellBorderPriority',
          label: '强调边优先级',
          defaultValue: 1,
          min: -1,
          max: 2,
          step: 1,
          visibleWhen: { controlId: 'cellBorderEnabled', oneOf: [true] },
        },
      ],
    },
  ],
});

/** DetailTable alpha.2 布局试验场的稳定文档契约 */
export const previewControlContract = {
  controls: tableLayoutPlaygroundControls,
  canonicalValues: {
    columnMode: 'fixed',
    columnWidth: 148,
    columnMinWidth: 96,
    columnMaxWidth: 176,
    rowMode: 'fixed',
    rowHeight: 44,
    columnGap: 6,
    rowGap: 4,
    padding: 6,
    horizontalAlign: 'start',
    verticalAlign: 'center',
    wrap: true,
    fit: 'none',
    overflow: 'clip',
    borderMode: 'collapse',
    gridWidth: 1,
    cellBorderEnabled: true,
    cellBorderPriority: 1,
  },
  presets: [
    {
      id: 'content',
      label: '内容优先',
      values: {
        columnMode: 'auto',
        columnWidth: 148,
        columnMinWidth: 96,
        columnMaxWidth: 176,
        rowMode: 'auto',
        rowHeight: 44,
        columnGap: 6,
        rowGap: 4,
        padding: 6,
        horizontalAlign: 'start',
        verticalAlign: 'center',
        wrap: true,
        fit: 'none',
        overflow: 'visible',
        borderMode: 'collapse',
        gridWidth: 1,
        cellBorderEnabled: true,
        cellBorderPriority: 1,
      },
    },
    {
      id: 'compact',
      label: '固定紧凑',
      values: {
        columnMode: 'fixed',
        columnWidth: 104,
        columnMinWidth: 96,
        columnMaxWidth: 176,
        rowMode: 'fixed',
        rowHeight: 32,
        columnGap: 0,
        rowGap: 0,
        padding: 2,
        horizontalAlign: 'start',
        verticalAlign: 'center',
        wrap: false,
        fit: 'none',
        overflow: 'clip',
        borderMode: 'collapse',
        gridWidth: 1,
        cellBorderEnabled: false,
        cellBorderPriority: 0,
      },
    },
  ],
  presetSelector: { label: '场景', customLabel: '自定义' },
  relatedApis: [
    'IRTableLayout.columns',
    'IRTableLayout.rowSize',
    'IRTableLayout.columnGap',
    'IRTableLayout.rowGap',
    'TableDetailColumnInput.bodyLayout',
    'IRTableCellLayout.padding',
    'IRTableCellLayout.horizontalAlign',
    'IRTableCellLayout.verticalAlign',
    'IRTableCellLayout.wrap',
    'IRTableCellLayout.fit',
    'IRTableCellLayout.overflow',
    'IRTableLayout.borders',
  ],
} satisfies PreviewControlContract;
