import type { PreviewControlContract } from '@/modules/docs/preview';

import { definePreviewControls } from '@/modules/docs/preview';

import { tableLayoutPlaygroundRows } from './table-layout-playground.en.data';

/** English controls for the DetailTable alpha.2 layout playground */
export const tableLayoutPlaygroundControls = definePreviewControls({
  presentation: 'panel',
  title: 'Detail table layout',
  defaultSize: 34,
  sections: [
    {
      label: 'Input data',
      defaultCollapsed: true,
      controls: [
        {
          kind: 'table',
          id: 'rows',
          label: 'Records',
          rows: tableLayoutPlaygroundRows,
          columns: [
            { key: 'name', label: 'Name' },
            { key: 'group', label: 'Group' },
            { key: 'score', label: 'Score' },
            { key: 'status', label: 'Status' },
            { key: 'note', label: 'Note' },
          ],
        },
      ],
    },
    {
      label: 'Tracks',
      controls: [
        {
          kind: 'select',
          id: 'columnMode',
          label: 'Note width',
          defaultValue: 'fixed',
          options: [
            { value: 'auto', label: 'Intrinsic width' },
            { value: 'fixed', label: 'Fixed width' },
            { value: 'minmax', label: 'Minimum and maximum' },
          ],
        },
        {
          kind: 'range',
          id: 'columnWidth',
          label: 'Fixed width',
          defaultValue: 148,
          min: 80,
          max: 188,
          step: 4,
          visibleWhen: { controlId: 'columnMode', oneOf: ['fixed'] },
        },
        {
          kind: 'range',
          id: 'columnMinWidth',
          label: 'Minimum width',
          defaultValue: 96,
          min: 64,
          max: 128,
          step: 4,
          visibleWhen: { controlId: 'columnMode', oneOf: ['minmax'] },
        },
        {
          kind: 'range',
          id: 'columnMaxWidth',
          label: 'Maximum width',
          defaultValue: 176,
          min: 132,
          max: 208,
          step: 4,
          visibleWhen: { controlId: 'columnMode', oneOf: ['minmax'] },
        },
        {
          kind: 'select',
          id: 'rowMode',
          label: 'Row size',
          defaultValue: 'fixed',
          options: [
            { value: 'auto', label: 'Intrinsic height' },
            { value: 'fixed', label: 'Fixed height' },
          ],
        },
        {
          kind: 'range',
          id: 'rowHeight',
          label: 'Row height',
          defaultValue: 44,
          min: 28,
          max: 48,
          step: 4,
          visibleWhen: { controlId: 'rowMode', oneOf: ['fixed'] },
        },
        { kind: 'range', id: 'columnGap', label: 'Column gap', defaultValue: 6, min: 0, max: 16, step: 2 },
        { kind: 'range', id: 'rowGap', label: 'Row gap', defaultValue: 4, min: 0, max: 6, step: 2 },
      ],
    },
    {
      label: 'Note Cells',
      controls: [
        { kind: 'range', id: 'padding', label: 'Padding', defaultValue: 6, min: 0, max: 12, step: 2 },
        {
          kind: 'select',
          id: 'horizontalAlign',
          label: 'Horizontal',
          defaultValue: 'start',
          options: [
            { value: 'start', label: 'Start' },
            { value: 'center', label: 'Center' },
            { value: 'end', label: 'End' },
          ],
        },
        {
          kind: 'select',
          id: 'verticalAlign',
          label: 'Vertical',
          defaultValue: 'center',
          options: [
            { value: 'start', label: 'Start' },
            { value: 'center', label: 'Center' },
            { value: 'end', label: 'End' },
          ],
          visibleWhen: { controlId: 'rowMode', oneOf: ['fixed'] },
        },
        {
          kind: 'switch',
          id: 'wrap',
          label: 'Wrap text',
          defaultValue: true,
          visibleWhen: { controlId: 'columnMode', oneOf: ['fixed', 'minmax'] },
        },
        {
          kind: 'select',
          id: 'fit',
          label: 'Fit',
          defaultValue: 'none',
          options: [
            { value: 'none', label: 'Original size' },
            { value: 'contain', label: 'Contain' },
            { value: 'cover', label: 'Cover' },
            { value: 'stretch', label: 'Stretch axes' },
          ],
        },
        {
          kind: 'select',
          id: 'overflow',
          label: 'Overflow',
          defaultValue: 'clip',
          options: [
            { value: 'visible', label: 'Keep visible' },
            { value: 'clip', label: 'Clip to content box' },
          ],
        },
      ],
    },
    {
      label: 'Border Graph',
      controls: [
        {
          kind: 'select',
          id: 'borderMode',
          label: 'Edge mode',
          defaultValue: 'collapse',
          options: [
            { value: 'collapse', label: 'Collapse shared edges' },
            { value: 'separate', label: 'Keep per-Cell edges' },
          ],
        },
        { kind: 'range', id: 'gridWidth', label: 'Line width', defaultValue: 1, min: 0.5, max: 3, step: 0.5 },
        { kind: 'switch', id: 'cellBorderEnabled', label: 'Highlight note edge', defaultValue: true },
        {
          kind: 'range',
          id: 'cellBorderPriority',
          label: 'Priority',
          defaultValue: 1,
          min: -1,
          max: 2,
          step: 1,
          visibleWhen: { controlId: 'cellBorderEnabled', oneOf: [true] },
        },
      ],
    },
  ],
});

/** Stable documentation contract for the DetailTable alpha.2 layout playground */
export const previewControlContract = {
  controls: tableLayoutPlaygroundControls,
  canonicalValues: {
    columnMode: 'fixed',
    columnWidth: 148,
    columnMinWidth: 96,
    columnMaxWidth: 176,
    rowMode: 'fixed',
    rowHeight: 44,
    columnGap: 6,
    rowGap: 4,
    padding: 6,
    horizontalAlign: 'start',
    verticalAlign: 'center',
    wrap: true,
    fit: 'none',
    overflow: 'clip',
    borderMode: 'collapse',
    gridWidth: 1,
    cellBorderEnabled: true,
    cellBorderPriority: 1,
  },
  presets: [
    {
      id: 'content',
      label: 'Content first',
      values: {
        columnMode: 'auto',
        columnWidth: 148,
        columnMinWidth: 96,
        columnMaxWidth: 176,
        rowMode: 'auto',
        rowHeight: 44,
        columnGap: 6,
        rowGap: 4,
        padding: 6,
        horizontalAlign: 'start',
        verticalAlign: 'center',
        wrap: true,
        fit: 'none',
        overflow: 'visible',
        borderMode: 'collapse',
        gridWidth: 1,
        cellBorderEnabled: true,
        cellBorderPriority: 1,
      },
    },
    {
      id: 'compact',
      label: 'Fixed compact',
      values: {
        columnMode: 'fixed',
        columnWidth: 104,
        columnMinWidth: 96,
        columnMaxWidth: 176,
        rowMode: 'fixed',
        rowHeight: 32,
        columnGap: 0,
        rowGap: 0,
        padding: 2,
        horizontalAlign: 'start',
        verticalAlign: 'center',
        wrap: false,
        fit: 'none',
        overflow: 'clip',
        borderMode: 'collapse',
        gridWidth: 1,
        cellBorderEnabled: false,
        cellBorderPriority: 0,
      },
    },
  ],
  presetSelector: { label: 'Scenario', customLabel: 'Custom' },
  relatedApis: [
    'IRTableLayout.columns',
    'IRTableLayout.rowSize',
    'IRTableLayout.columnGap',
    'IRTableLayout.rowGap',
    'TableDetailColumnInput.bodyLayout',
    'IRTableCellLayout.padding',
    'IRTableCellLayout.horizontalAlign',
    'IRTableCellLayout.verticalAlign',
    'IRTableCellLayout.wrap',
    'IRTableCellLayout.fit',
    'IRTableCellLayout.overflow',
    'IRTableLayout.borders',
  ],
} satisfies PreviewControlContract;
